### ISSUE TITLE
clarify when Broker.Close should be called

### ISSUE THREAD

**Issue by rogpeppe** [IBM/sarama#1496]
The sarama package documentation doesn't clarify when [Broker.Close](https://godoc.org/github.com/Shopify/sarama#Broker.Close) is expected to be called, and usage in the code doesn't make it clear either.

For example, here's a Client method [in the code](https://github.com/Shopify/sarama/blob/2af3badd8c04a312157aa5d6a3382abdb54eef2f/client.go#L667-L698) that sometimes closes the returned broker and sometimes does not:
```
func (client *client) getOffset(topic string, partitionID int32, time int64) (int64, error) {
	broker, err := client.Leader(topic, partitionID)
	if err != nil {
		return -1, err
	}

	request := &OffsetRequest{}
	if client.conf.Version.IsAtLeast(V0_10_1_0) {
		request.Version = 1
	}
	request.AddBlock(topic, partitionID, time, 1)

	response, err := broker.GetAvailableOffsets(request)
	if err != nil {
		_ = broker.Close()
		return -1, err
	}

	block := response.GetBlock(topic, partitionID)
	if block == nil {
		_ = broker.Close()
		return -1, ErrIncompleteResponse
	}
	if block.Err != ErrNoError {
		return -1, block.Err
	}
	if len(block.Offsets) != 1 {
		return -1, ErrOffsetOutOfRange
	}

	return block.Offsets[0], nil
}
```

If I call `Client.Leader` in my code, should I close the returned Broker or not? Given that brokers are shared and cached, it seems maybe not, but the fact that `getOffset` does close them in some circumstances means that I can't be sure.

**Comment by rogpeppe** [comment]
@probot-shopify yup, it would indeed be nice to have some kind of response here.

**Comment by rogpeppe** [comment]
I guess no-one knows. Sigh.

**Comment by dnwe** [comment]
@rogpeppe in the example code you posted it is only closing the Broker in what would be considered protocol error cases where we think the broker has become unusable and so is closed to cause it to be re-opened if a request is attempted to the same broker again. 

As a consumer of the Sarama client you wouldn't be expected to close Brokers yourself unless you explicitly wanted to disconnect from every broker and tear everything down

**Comment by rogpeppe** [comment]
That's useful information, thanks!

Would this be a fair suggestion for a more informative doc comment?

```
// Close closes the broker resources.
//
// It is not necessary for the client to close a Broker instance
// returned from a Client method - it will be closed when the Client is
// closed.
//
// However, it is OK to close a Broker explicitly anyway (for example to
// invalidate it when the connection is known to be bad). It is also OK
// to close a Broker more than once.
func (b *Broker) Close() error
```

**Comment by dnwe** [comment]
@rogpeppe yes looks like a reasonable idea to me, apart from the comment "it is also OK to close a Broker more than once" — it is OK to call b.Close() more than once in that it doesn't have side-effects, but the follow-on attempts would return an `err` of `sarama.ErrNotConnected` to the caller so you would need to either discard or handle that

**Comment by rogpeppe** [comment]
Better like this?

```
// Close closes the broker resources.
//
// It is not necessary for the client to close a Broker instance
// returned from a Client method - it will be closed when the Client is
// closed.
//
// However, it is OK to close a Broker explicitly anyway (for example to
// invalidate it when the connection is known to be bad). It is also OK
// to close a Broker more than once, although a repeated Close will
// return a sarama.ErrNotConnected error.
func (b *Broker) Close() error
```

**Comment by dnwe** [comment]
Thanks 😊 LGTM
