### ISSUE TITLE
Kafka Client is not able to join broker coordinator

### ISSUE THREAD

**Issue by dhbarman** [IBM/sarama#1503]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.23.1 | 2.0.0  |  1.12.7 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        config.Consumer.Return.Errors = true
	config.Version = sarama.V2_0_0_0
	config.Consumer.Offsets.Initial = sarama.OffsetNewest
```

We have a topic with 40 partitions. We have 10 Kafka client sessions connecting to these partitions. The 10 kafka clients are part of a consumer group.

##### Logs

<details><summary>logs: CLICK ME</summary>
The error messages are received on client.Errors() channel.
<p> 

``` go
        msg="error received on error channel" err="kafka: error while consuming device_telemetry/15: kafka server: The provided member is not known in the current generation."
```
</p>
</details>

##### Problem Description

We have a deployment of Kafka in production system. In one deployment we are seeing that after changes in broker cluster, Sarama based client is NOT able to connect back to updated/correct broker coordinator. We keep seeing the error messages - "kafka server: The provided member is not known in the current generation." As a result, we are losing messages in production. The situation persists and does not mitigate by items. Only restarting the Kafka client sessions help.

**Comment by d1egoaz** [comment]
@dhbarman this might work for you https://github.com/Shopify/sarama/issues/1310#issuecomment-478570166
tl/dr increase `.Group.Session.Timeout`

**Comment by dnwe** [comment]
Assuming this was resolved by session config
