### ISSUE TITLE
The gopkg.in import path can't be used with recent Go versions while the README file claims otherwise

### ISSUE THREAD

**Issue by babolivier** [IBM/sarama#1510]
Because the [go.mod](https://github.com/Shopify/sarama/blob/master/go.mod#L1) file mentions `github.com/Shopify/sarama` as the package's canonical import path, `go get gopkg.in/Shopify/sarama.v1` results in the following with Go 1.13:

```
[11:43:33] brendan@Noah:/home/brendan$ go get gopkg.in/Shopify/sarama.v1
go: finding gopkg.in/Shopify/sarama.v1 v1.24.0
go get gopkg.in/Shopify/sarama.v1: gopkg.in/Shopify/sarama.v1@v1.24.0: invalid version: go.mod has non-....v1 module path "github.com/Shopify/sarama" at revision v1.24.0
[11:43:38] brendan@Noah:/home/brendan$ 
```

The README file claims that the `gopkg.in` is usable with all recent versions of Go, while it's apparently not.

**Comment by babolivier** [comment]
Still haven't been resolved apparently :/

**Comment by yanuarxnc** [comment]
I have same error.

**Comment by babolivier** [comment]
Apparently the fix for this is to use `github.com/Shopify/sarama` as the import path.

**Comment by d1egoaz** [comment]
@babolivier thanks!

I'm wondering if we should remove the references to `gopkg.in` and only mention the official go mod.

Thoughts @dnwe @bai

**Comment by bai** [comment]
I think gopkg.in should go away, I see no reason for using it anymore.

**Comment by babolivier** [comment]
Yeah same, now that Go natively supports versioning dependencies gokpg.in has no real use anymore.

**Comment by d1egoaz** [comment]
@babolivier want to give it a try and send a PR?

**Comment by babolivier** [comment]
Sure, will do that tomorrow :)

**Comment by gbbr** [comment]
@babolivier this would help

**Comment by gbbr** [comment]
Most people use this package as instructed by the README, using the `gopkg.in` import path. It was an oversight and until now that it was ok within the repository to use the `github.com` import path. IMHO changing the README is a breaking change (breaking import path) and the right answer is changing the import path within this repository to `gopkg.in/Shopify/sarama.v1` and getting rid of it with `v2`.

**Comment by babolivier** [comment]
Ugh, looks like I got distracted by work and forgot about this. I'll try to get something out soon.

**Comment by fezho** [comment]
One workaround is using `replace` in go.mod:

```
require (
    ...
    gopkg.in/Shopify/sarama.v1 v1.27.2
    ...
)

replace gopkg.in/Shopify/sarama.v1 v1.27.2 => github.com/Shopify/sarama v1.27.2

```
