### ISSUE TITLE
Lack of MockJoinGroupResponse in mockresponses.go

### ISSUE THREAD

**Issue by liuxin-reg** [IBM/sarama#1577]
master
I haven't found struct MockJoinGroupResponse in mockresponses.go, will we support that?

**Comment by liuxin-reg** [comment]
I have supplement some kind of mock responses to make group consumer work, but not enough to submit a commit. Will try and continue working on it.

**Comment by carldunham** [comment]
@liuxin-reg any luck with this? Happy to help out if you want.

**Comment by carldunham** [comment]
I submitted a PR with a few mocks, but I think consumer group mocking will take a bit more than just that.

**Comment by liuxin-reg** [comment]
@carldunham Thanks for your response and PR. I had add some basic mocks for consumer group responses too, it can works now, but without enough detailed considerations contained. Now, I removed this modification from folder vendor, since I don't think this kind of mock is necessary for normal consumer client.

**Comment by gunturaf** [comment]
Any updates on this one @carldunham @liuxin-reg ?

**Comment by dnwe** [comment]
Fixed by https://github.com/IBM/sarama/pull/1750
