### ISSUE TITLE
ByteEncoder vs. StringEncoder problems

### ISSUE THREAD

**Issue by Glagnar** [IBM/sarama#1625]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.26.1 | 2.4 | 1.13.4 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	config.Producer.Return.Successes = false
	config.Producer.Return.Errors = true
	config.Producer.Retry.Max = 5
```

##### Problem Description
I am sending binary messages to kafka, that have this format:
[60 0 34 147 249 175 183 0 0 3 174 0 0 7 209 94 77 83 104 0 0 1 248 0 0 0 0 0 0 0 0 1 253 62]
( They start with < and end with > )

When I use the byte encoder, messages are 'mixed up' i.e. if I consume the stream of data back from Kafka things work fine, but the individual messages are broken in seemingly random places.

If I use the StringEncoder, I get the expected behaviour where each kafka message is complete. Is this an error ?

**Comment by cheesedosa** [comment]
Sounds like an ownership issue. Are you reusing the `[]byte` after you call send? The `ByteEncoder` does not make a copy. `strings` in golang are always copies.

**Comment by dnwe** [comment]
Closing as believed to have been fixed. Issue due to []byte re-use
