### ISSUE TITLE
Clarification on golang context, pointers and docs

### ISSUE THREAD

**Issue by RobinKamps** [IBM/sarama#1636]
Are the arguments against sarama stated on https://github.com/segmentio/kafka-go (no context, pointers, no docs) still valid?

**Comment by cheesedosa** [comment]
* There's context support only for consumer groups, which was merged from [sarama-cluster](https://github.com/bsm/sarama-cluster).
* I found the documentation to be adequate (mostly comments from godoc). 
* Pointers are an issue. Most of the API as well as the internals (metadata, admin clients, etc) make heavy use of pointers. The concerns raised by segmentio are valid. That many pointers will add gc pressure. This is something that is subjective to the application that you are building (If you are okay with the gc pressure and a higher heap size).
