### ISSUE TITLE
non-positive interval for NewTicker

### ISSUE THREAD

**Issue by soouCc** [IBM/sarama#1638]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
v1.26.1 | Amazon MSK 2.2.0 | 1.13.5
-- | -- | --

|  |  |  |
panic:  non-positive interval for NewTicker

ticker := time.NewTicker(c.client.config.Consumer.Offsets.CommitInterval)

// Deprecated: CommitInterval exists for historical compatibility
// and should not be used. Please use Consumer.Offsets.AutoCommit
CommitInterval time.Duration

How can I set this CommitInterval？

**Comment by Arnasnn** [comment]
seems like a bug, got similar issue. I've solved it by doing this:
clusterConfig.Consumer.Offsets.CommitInterval = time.Second

**Comment by daniel-cohen** [comment]
I have the same issue. Seems like a regression in 1.26.1 
Setting Consumer.Offsets.CommitInterval to 1 seems to get it running again.

**Comment by pathbox** [comment]
Me too.  I use  "github.com/bsm/sarama-cluster"  with  kafka consumer group feature

**Comment by soouCc** [comment]
Use this    github.com/bsm/sarama-cluster v2.1.15+incompatible

**Comment by d1egoaz** [comment]
@soouCc have you tried using the following with a recent Sarama release?
```
	config.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
```

**Comment by pathbox** [comment]
> @soouCc have you tried using the following with a recent Sarama release?
> 
> ```
> 	config.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
> ```

Hello, I try it, but it doesn't work. 
```go
  clusterConfig.Consumer.Offsets.CommitInterval = time.Second
```
This works

**Comment by pathbox** [comment]
@d1egoaz 

config.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
Hello, I try it, but it doesn't work.

  clusterConfig.Consumer.Offsets.CommitInterval = time.Second
This works

**Comment by dink10** [comment]
clusterConfig.Consumer.Offsets.CommitInterval is deprecated

You need to use next one for fixing problem

cfg.Consumer.Offsets.AutoCommit.Enable = true
cfg.Consumer.Offsets.AutoCommit.Interval = time.Second

**Comment by dink10** [comment]
> @d1egoaz
> 
> ```go
>   config.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
> ```
> 
> Hello, I try it, but it doesn't work.
> 
> ```go
>   clusterConfig.Consumer.Offsets.CommitInterval = time.Second
> ```
> 
> This works

It works if you turn on flag `cfg.Consumer.Offsets.AutoCommit.Enable = true`

**Comment by Jason5Lee** [comment]
I met this issue.
The panic result shows that

```
panic: non-positive interval for NewTicker

goroutine 43 [running]:
time.NewTicker(0x0, 0x0)
        <GOPATH>/src/time/tick.go:24 +0x151
github.com/Shopify/sarama.(*consumerGroup).loopCheckPartitionNumbers(0xc000196480, 0xc000238400, 0x1, 0x4, 0xc0002b2400)
        <GOPATH>/pkg/mod/github.com/!shopify/sarama@v1.26.1/consumer_group.go:442 +0x66
created by github.com/Shopify/sarama.(*consumerGroup).Consume
        <GOPATH>/pkg/mod/github.com/!shopify/sarama@v1.26.1/consumer_group.go:176 +0x259
```

The 176 line of the `consumer_group.go` is

```
pause := time.NewTicker(c.config.Metadata.RefreshFrequency)
```

The argument should be 10m by default, and the corresponding field in the configuration passed in to create the producer is 10m. But it somehow becomes 0 on runtime.

![image](https://user-images.githubusercontent.com/25118271/130066899-c5b4e95a-6b23-4fde-9305-9aff7af8be02.png)

**Comment by Jason5Lee** [comment]
I met this issue.
The panic result shows that

```
panic: non-positive interval for NewTicker

goroutine 43 [running]:
time.NewTicker(0x0, 0x0)
        <GOPATH>/src/time/tick.go:24 +0x151
github.com/Shopify/sarama.(*consumerGroup).loopCheckPartitionNumbers(0xc000196480, 0xc000238400, 0x1, 0x4, 0xc0002b2400)
        <GOPATH>/pkg/mod/github.com/!shopify/sarama@v1.26.1/consumer_group.go:442 +0x66
created by github.com/Shopify/sarama.(*consumerGroup).Consume
        <GOPATH>/pkg/mod/github.com/!shopify/sarama@v1.26.1/consumer_group.go:176 +0x259
The 176 line of the consumer_group.go is

pause := time.NewTicker(c.config.Metadata.RefreshFrequency)
```

After troubleshooting I found that a package is constructing sarama client using the following code:

```
saramaConfig = sarama.NewConfig()
saramaConfig.Consumer.Return.Errors = true
saramaConfig.ChannelBufferSize = defaultBufferSize
saramaConfig.Net.MaxOpenRequests = defaultConnectionNum
saramaConfig.Metadata.RefreshFrequency = 0 // disable metadata fetching; it will be re-fetched on-demand
saramaConfig.Version = sarama.V1_1_1_0
```

And the documentation of `RefreshFrequency` states:

> How frequently to refresh the cluster metadata in the background. Defaults to 10 minutes. Set to 0 to disable. Similar to `topic.metadata.refresh.interval.ms` in the JVM version.

But it seems it doesn't handle the `0` case correctly.

**Comment by Jason5Lee** [comment]
#1999

**Comment by rahulkarmore** [comment]
> ```go
> clusterConfig
> ```

In which file we need to set **config.Consumer.Offsets.CommitInterval=time.Second**

**Comment by dnwe** [comment]
Fixed by https://github.com/IBM/sarama/pull/2329
