### ISSUE TITLE
Refresh client metadata regularly for the Producer 

### ISSUE THREAD

**Issue by lebaptiste** [IBM/sarama#1642]
The producer when dispatching a message check that the partition assigned by the Partitioner is a valid partition number. To do this it fetches the partitions info for the topic from the client.
However the metadata and the number of partitions are cached by the client.
In the situation where new partitions for the topic got created on the Kafka cluster, the producer is never aware of this change and the Partitioners will therefore not assign any message to these new partitions.
Should the producer by default periodically refresh the client metadata to check the current number of partitions for a topic? Or this should be left to the end developer to implement?

**Comment by vincentbernat** [comment]
I am also running in this issue and would be interested to know if there is something preventing Sarama to handle that automatically (other than someone writing the code, which is something I could look at if there is nothing fundamentally wrong with the concept).
