### ISSUE TITLE
Using MockBroker with v0.11+

### ISSUE THREAD

**Issue by gm42** [IBM/sarama#1665]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.21.0 | - | 1.13.8 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	cfg := sarama.NewConfig()
	cfg.Producer.Return.Successes = true
        // this causes the the sync producer test to hang
	cfg.Version = sarama.V0_11_0_0
```

##### Problem Description

Forgive me the slightly old `sarama` version; I am having issues to create a test like `TestSyncProducer` that would also test for **message headers** functionality usage.

My test is a copy of `TestSyncProducer` with the above configuration added&used here: https://github.com/Shopify/sarama/blob/v1.21.0/sync_producer_test.go#L24

v0.11+ is necessary for the headers, however when specifying it the mock broker will not work (I assume because of the version requirement).

Is there a way to make the mock broker satisfy the requirement? Shall we add some test to `sarama` to cover this use-case?

**Comment by adw1n** [comment]
Newest Sarama version still suffers from the same problem.

**Comment by dnwe** [comment]
Unless I'm misunderstanding the description, this shouldn't be a problem on recent versions of Sarama. Please re-open if it is
