### ISSUE TITLE
How to obtain consumer groups detail messages by sarama

### ISSUE THREAD

**Issue by KinYu668** [IBM/sarama#1674]
### Problem Description
I'd like to get information about the consumer group。like this：（./kafka-consumer-groups.sh --describe --group XX --bootstrap-server XX）
GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                 HOST            CLIENT-ID
price-group     price           2          2145            3404636         3402491         sarama-00084857-dae4-478b-a302-b42f6e76cb23 /172.17.2.167   sarama
price-group     price           1          4032            4916799         4912767         sarama-00084857-dae4-478b-a302-b42f6e76cb23 /172.17.2.167   sarama
price-group     price           4          10274           3401565         3391291         sarama-00084857-dae4-478b-a302-b42f6e76cb23 /172.17.2.167   sarama
price-group     price           0          12707           4921711         4909004         sarama-00084857-dae4-478b-a302-b42f6e76cb23 /172.17.2.167   sarama
price-group     price           3          11612           4916577         4904965         sarama-00084857-dae4-478b-a302-b42f6e76cb23 /172.17.2.167   sarama

through sarama，how to achieve？

**Comment by cheesedosa** [comment]
You need to fetch is using [cluster admin](https://godoc.org/github.com/Shopify/sarama#ClusterAdmin).

**Comment by sayan1886** [comment]
@cheesedosa @Dom921  there is no scope of getting **LOG-END-OFFSET** using [cluster admin](https://godoc.org/github.com/Shopify/sarama#ClusterAdmin). it only provides the **CURRENT-OFFSET**, do you have any future plans to expose it using Sarama.
