### ISSUE TITLE
Is there a way to set batch.size and max.block.ms for kafka version V2.5.x in producer?

### ISSUE THREAD

**Issue by al8n** [IBM/sarama#1690]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 2 | 2.5.0 | 1.13.7 |

##### Configuration

Is there a way to set `batch.size`,`max.block.ms`, `max.in.flight.requests.per.connection` and `buffer.memory` for kafka version V2.5.x in producer?

**Comment by andresmijares** [comment]
Interested in this answer as well

**Comment by 97arushisharma** [comment]
Facing same issue. Want to set batch.size. But cant figure out any such property from Producer configs.

**Comment by golango-cn** [comment]
Same issue

**Comment by kwenZh** [comment]
the same issue, want to set `batch.size` and `linger.ms`

**Comment by yitian108** [comment]
Same issue, any update? Thanks @dnwe @cch123
