### ISSUE TITLE
Using package github.com/Shopify/sarama

### ISSUE THREAD

**Issue by ghost** [IBM/sarama#1713]
When using using the command
go test 123_test.go 

I get 

# command-line-arguments
package command-line-arguments (test)
        imports github.com/Shopify/sarama: found packages main (123.go) and test (123_test.go) in C:\Gocode\src\123
FAIL    command-line-arguments [setup failed]
FAIL

I have used go mod init github.com/Shopify/sarama 
and 
go get -u -d github.com/Shopify/sarama 
and 
go get github.com/Shopify/sarama

and it is returning the same error. Please help me fix this error

**Comment by dnwe** [comment]
@AwesomeAlpha this looks like a mistake in your local files rather than a problem with Sarama

> found packages main (123.go) and test (123_test.go)

You’ve put your test file in a package called “test” rather than “main”. Make both files the same package.

**Comment by AwesomeAlpha** [comment]
if I use same package names, it throws cyclic dependency issue.

**Comment by dnwe** [comment]
@AwesomeAlpha upload all your files to a git repo and share the link, but it doesn’t sound like Sarama issue

**Comment by AwesomeAlpha** [comment]
Thank you but even if i try 

go list or go fix 

can't load package: import cycle not allowed
package github.com/Shopify/sarama
        imports github.com/Shopify/sarama

same kind of error popping up
