### ISSUE TITLE
Doesn't work in k8s, but Docker is available

### ISSUE THREAD

**Issue by wangxin0814** [IBM/sarama#1723]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.26.4 | 2.1  | 1.14.2  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
```	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.NoResponse
	config.Producer.Retry.Max = 0
	config.Producer.Partitioner = sarama.NewRoundRobinPartitioner
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
```

</p>
</details>

**Comment by d1egoaz** [comment]
Hey @wangxin0814 
are you sure the kafka bootstrap brokers are available?
can you do a `nc -v broker port` to see if they are reachable?

This doesn't look like a Sarama issue.
