### ISSUE TITLE
Add kafka producer/consumer pipeline diagrams

### ISSUE THREAD

**Issue by d1egoaz** [IBM/sarama#1727]
@bai @dnwe do you guys think it would worth adding some diagrams like this to the wiki?
specifically here: https://github.com/Shopify/sarama/wiki/Producer-implementation

I've been digging on the producer, and I needed to make some diagrams to get an understanding about how things were connected.

if yes, I'd add the `.dot` files to the repo and the `.svg` produced, or maybe only the dotfiles and include the png so the link can use this repo as the img source.

![sarama-producer-pipeline](https://screenshot.click/2020-06-18_09-50-42_xzvko.png)

**Comment by d1egoaz** [comment]
I also made this, but this might have too much detail in some parts, and might get outdated with changes

![image](https://user-images.githubusercontent.com/950087/85050030-5467b380-b14a-11ea-9f01-0b3e1ca91e6a.png)

**Comment by varun06** [comment]
I like the first one as that one is high level and gives enough info.
