### ISSUE TITLE
ErrUnknownProducerID should be retried

### ISSUE THREAD

**Issue by cweerasooriya** [IBM/sarama#1737]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.24.1 | 2.1.0 | 1.13.1 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	saramaConfig := sarama.NewConfig()
	saramaConfig.Version = sarama.V2_1_0_0
	saramaConfig.Net.TLS.Enable = true
	saramaConfig.Net.TLS.Config = tls

	saramaConfig.Net.MaxOpenRequests = 1
	saramaConfig.Net.KeepAlive = 30*time.Second

	saramaConfig.Producer.Partitioner = sarama.NewReferenceHashPartitioner
	saramaConfig.Producer.Compression = sarama.CompressionSnappy
	saramaConfig.Producer.RequiredAcks = sarama.WaitForAll

	saramaConfig.Producer.Idempotent = true

	saramaConfig.Producer.Return.Successes = true
	saramaConfig.Producer.Return.Errors = true

	saramaConfig.Producer.Retry.Max = 300
	saramaConfig.Producer.Retry.Backoff = 100*time.Millisecond

	saramaConfig.Producer.Flush.Bytes = 100000
	saramaConfig.Producer.Flush.Frequency = 100*time.Millisecond

	if config.SaramaConfigCallback != nil {
		saramaConfig = config.SaramaConfigCallback(saramaConfig)
	}
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
kafka server: The broker could not locate the producer metadata associated with the Producer ID.
```

</p>
</details>

##### Problem Description
We are publishing to a low traffic topic. Our producer encountered this error yesterday.
According to https://issues.apache.org/jira/browse/KAFKA-7190 this error could happen in low traffic topics and the producer should retry on the error.

We observed that Sarama is not retrying on this error which causes the producer to fail.

**Comment by twmb** [comment]
Unless I'm mistaken, [KIP-360](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=89068820) (mentioned in that ticket) implies that it's fundamentally unsafe to retry on UnknownProducerID. UnknownProducerID was originally intended to allow clients to recover sending records, but the way to retry when a client sees UnknownProducerID is for the client to reset the sequence numbers of records. This effectively makes the client act as if it is publishing to the partition anew. KIP-360 explains that this is fundamentally unsafe and can lead to mistaken duplicates. The key line: "For the idempotent producer, the user can choose to fail or they can continue (with the possibility of duplication or reordering). If the user continues, the epoch will be bumped locally and the sequence number will be reset."

I think a fix for this in Sarama would be a config knob where users can opt in to unsafe recovery (this is similar to the path I chose on my own client, where instead users need to [opt out](https://godoc.org/github.com/twmb/kafka-go/pkg/kgo#StopOnDataLoss) of automatically continuing on potential data loss).

**Comment by varun06** [comment]
I agree with @twmb above. It is definitely unsafe to retry on UnknownProducerID. 

If we feel that fix is to provide a config option to understand the consequence and keep going, let's talk more about that. Pinging @d1egoaz @bai
