### ISSUE TITLE
There is a Flaky test in CI

### ISSUE THREAD

**Issue by varun06** [IBM/sarama#1742]
##### Problem Description

I am seeing `##[error]    TestAsyncProducerRecoveryWithRetriesDisabled/non-retriable_error: async_producer_test.go:50: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)` error in bunch of CI failures. It is a flaky test and need to be looked into. Any idea? if not, I will look into it.

@bai  @dnwe @d1egoaz

**Comment by dnwe** [comment]
This has been fixed and is no longer a flakey test
