### ISSUE TITLE
Behavior : Messages marked for deletion 

### ISSUE THREAD

**Issue by harshana-pickme** [IBM/sarama#1745]
##### Problem Description

Hi all,

On a compacted topic, kafka will first mark duplicate messages for deletion and then physically remove them later.

1. Does sarama consumers receive these marked for deletion messages ?
2. if so how can the application know if a messages is marked for deletion ?

Thanks,
Harshana

**Comment by harshana-pickme** [comment]
Can someone enlighten me on this ?

**Comment by dnwe** [comment]
A FetchRequest to a compacted topic will only ever retrieve the most recent value for a given key on a compacted topic. The marking for deletion / tombstoning of the superseded older values and their eventual removal is transparent to a client
