### ISSUE TITLE
filebeat can not push to kafka

### ISSUE THREAD

**Issue by ClementeGao** [IBM/sarama#1749]
filebeat version 6.6.0
kafka version 2.11
env: docker 
the follow is my Dockerfile
![image](https://user-images.githubusercontent.com/16145998/87221698-94643400-c3a0-11ea-8c11-1489efd4b58a.png)
l use command docker run -d  --restart always --name=filebeat nx_filebeat setup filebeat
the follow is my filebeat.yml 
![image](https://user-images.githubusercontent.com/16145998/87221731-d8efcf80-c3a0-11ea-9865-6110f5f95d3b.png)
![image](https://user-images.githubusercontent.com/16145998/87221762-19e7e400-c3a1-11ea-9807-c0b78d3215e1.png)

**Comment by dnwe** [comment]
@ClementeGao we can’t really help on this without the logging output from Sarama

If you add the following block to your filebeat config you should get some debug output from Sarama to show what’s happening with kafka

```yaml
logging:
  level: debug
  to_files: false
  to_syslog: false
```

**Comment by ClementeGao** [comment]
![image](https://user-images.githubusercontent.com/16145998/87221941-67b11c00-c3a2-11ea-8b5f-42f6117236a7.png)
here?

**Comment by ClementeGao** [comment]
do not create topic in kafka i guess the filebeat dot have connect to kafka   but l do not know why  l really ping kafka host

**Comment by ClementeGao** [comment]
@dnwe 
![image](https://user-images.githubusercontent.com/16145998/87222105-95e32b80-c3a3-11ea-97cd-941372f9c9af.png)
