### ISSUE TITLE
producer create by sarama.NewSyncProducer is thread safe ?

### ISSUE THREAD

**Issue by widon1104** [IBM/sarama#1761]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.23.0 |  |  1.14 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

I just want to know is the producer create by sarama.NewSyncProducer is thread safe ?
In java api，
http://people.apache.org/~nehanarkhede/kafka-0.9-producer-javadoc/doc/org/apache/kafka/clients/producer/KafkaProducer.html
"The producer is thread safe and should generally be shared among all threads for best performance. "

I want to if the go api for create producer has the same features.
If the producer is thread safe and shared by all threads I do not need to create link pool now.

**Comment by d1egoaz** [comment]
what do you mean by `shared by all threads` in your program?

Go has goroutines, and channels, which is what the SyncProducer uses.

In go, you can share the producer reference, and when `SendMessage` is called from any go routine, it'll put a message in the  *single* `Input` channel.

**Comment by d1egoaz** [comment]
this might help understand the difference between java thread and Go communication sequential processes 

https://dev.to/napicella/go-for-java-developers-or-is-the-java-concurrency-that-bad-6ff#:~:text=In%20the%20Java%20example%20there,go%20routines%20to%20an%20array.

not sure if this answers your question.

**Comment by auhlik** [comment]
There is some information in FAQ regarding the question asked: https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#is-it-safe-to-send-messages-to-the-synchronous-producer-concurrently-from-multiple-goroutines

**Comment by dnwe** [comment]
Closing as believed to have been fixed
