### ISSUE TITLE
Since allow the consumer to disable auto-commit offsets, so how to commit offset manually?

### ISSUE THREAD

**Issue by bglmmz** [IBM/sarama#1764]
| Sarama | Kafka | Go |
|--------|-------|----|
|  1.26.4|  2.5.0|  1.10.4|

refer to the PR #1164.

I want to commit offsets manually, but I cannot find any API or sample? Could anyone give me a hand? Thanks!

**Comment by xwi88** [comment]
> Sarama	Kafka	Go
> 1.26.4	2.5.0	1.10.4
> refer to the PR #1164.
> 
> I want to commit offsets manually, but I cannot find any API or sample? Could anyone give me a hand? Thanks!

**sarama.NewConfig().Consumer.Offsets.AutoCommit.Enable = false**

**Comment by qiangmzsx** [comment]
I am using v1.27.0 and have set up:
```
mqConfig.Consumer.Offsets.AutoCommit.Enable = true
	mqConfig.Consumer.Offsets.AutoCommit.Interval = 100* time.Millisecond

```
But sarama doesn't automatically submit the offset as expected.

**Comment by qiangmzsx** [comment]
> I am using v1.27.0 and have set up:
> 
> ```
> mqConfig.Consumer.Offsets.AutoCommit.Enable = true
> 	mqConfig.Consumer.Offsets.AutoCommit.Interval = 100* time.Millisecond
> ```
> 
> But sarama doesn't automatically submit the offset as expected.

I see, it still requires a manual process to submit, but the submissions are spaced out.

**Comment by Gypsying** [comment]
```
Consumer.Offsets.AutoCommit.Enable = false

consumerGroupSession.ResetOffset(Topic, Partition, Offset, "")
consumerGroupSession.Commit()
```
i test the settings like that, but the kafka' CURRENT-OFFSET does't change, 
i don't why, it seems not work...

@wclaeys @dnwe @d1egoaz 
Can you give some samples? 
Thanks.

**Comment by dnwe** [comment]
Fixed by https://github.com/IBM/sarama/pull/1699
