### ISSUE TITLE
How to add delay to processing of message?

### ISSUE THREAD

**Issue by aksJain0** [IBM/sarama#1768]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|1.26.4|1.0.0|1.13.12|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

Is there a way to delay consumption from kafka queue, if there is a failure in the processing of message read from kafka queue, so that the same message can be tried to process after the delay?

One solution I am trying is by turning the auto commit off, here I would be able to receive the same message again off the queue but I wan to know how to control when I will receive it again.

Another solution that I am trying is, introduce the delay and retry loop inside the ConsumerClaim() for each message, but this increases the processing time for each consumer,  so I had to configure consumer.MaxProcessingTime accordingly, Do I need to make some more changes in configuration? And does it seem like a viable approach?

**Comment by dnwe** [comment]
It should be possible to achieve the desired behaviour using the Pause and Resume functionality in the consumer now
