### ISSUE TITLE
More cpu usage for publishing a message using sarama

### ISSUE THREAD

**Issue by VijayBhaskar** [IBM/sarama#1773]
##### Versions sarama

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|---1.26-----|--2.6-----|-1.14---|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
Default configurations

##### Problem Description
Hi we are seeing much CPU usage while publishing 2.5 kb protobuf compressed data using sarama package.
here we are sending 2.5 kb compressed data @1000 messages for 5 seconds in span of 30 minutes

Code snippet
-------------
go func() {
		for {
			select {
			case err := <-consumer.Errors():
				fmt.Println(err)
			case msg := <-consumer.Messages():
				go processReceivedData(msg)
				msgCount++
				fmt.Println("Received 100")
			case <-signals:
				fmt.Println("Interrupt is detected")
				doneCh <- struct{}{}
			}
		}
	}()

![image](https://user-images.githubusercontent.com/2493998/89566165-4aeef380-d83d-11ea-9acb-4704e68c9e23.png)

**Comment by varun06** [comment]
Hey Vijay,
> we are seeing much CPU usage while publishing 2.5 kb protobuf compressed data using sarama package.
Are you comparing it with some other kafka client? What do you mean by CPU usage is high?

**Comment by VijayBhaskar** [comment]
yes comparing go-lang, kafka with java kafka.
----------------------------------------------------
so we see less cpu usage like 3% for the above case for java kafka
but if we are taking go lang and kafka we are seeing much usage - 70% cpu usage

publisher-subscriber(default kafka configurations)
=================================
Message size - 2.5 kb
we are doing zipping, marshalling at publisher side and un zip and un marshal at subscriber side
we are sending 1000(each 2.5kb data) messages in the span of 5 seconds for 30 minutes
in this case the cpu usage is 70% using go-lang sarama 


is it the default behavior of go-lang with sarama package ? like eating more cpu
or do we need to do kafka-server configurations for fixing this

Please help me here if you have any ideas


Thanks
Vijay Bhaskar

**Comment by gonejack** [comment]
CPU的差异没那么大才对，能否展示一下用法，也可以用CPU Profile查看一下占用高的地方。

Could you show some code or CPU profile results since 70% different is far from normal cases.
