### ISSUE TITLE
Getting runtime: invalid pc-encoded table f=runtime.goexit with sarama package

### ISSUE THREAD

**Issue by VijayBhaskar** [IBM/sarama#1777]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|---1.26-----|--2.6-----|-1.14---|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
Default kafka and zookeeper configurations

##### Logs

%%%%%%%%%% published 1000 values data %%%%%%%%%% %s 2020-08-12 16:03:47.6712749 -0400 EDT m=+5995.608367901
16:03:52 client/metadata fetching metadata for all topics from broker localhost:9092
16:03:52 client/metadata got error from broker -1 while fetching metadata: read tcp [::1]:64562->[::1]:9092: wsarecv: An established connection was aborted by the software in your host machine.

runtime: invalid pc-encoded table f=runtime.goexit pc=0x466f97 targetpc=0x466f97 tab=[0/0]0x0
        value=0 until pc=0x466f97
fatal error: invalid runtime symbol table

runtime stack:
----------------
runtime.throw(0x9485d3, 0x1c)
        c:/go/src/runtime/panic.go:1116 +0x79
runtime.pcvalue(0xa77d60, 0xcf43e0, 0x6db17, 0x466f97, 0x2792f068, 0xa45201, 0x8)
        c:/go/src/runtime/symtab.go:790 +0x548
runtime.funcspdelta(0xa77d60, 0xcf43e0, 0x466f97, 0x2792f068, 0x8)
        c:/go/src/runtime/symtab.go:844 +0x66
runtime.gentraceback(0x468a6e, 0x282dfb20, 0x0, 0xc00044c180, 0x0, 0x2792f2c0, 0x40, 0x0, 0x0, 0x6, ...)
        c:/go/src/runtime/traceback.go:220 +0x15bc
runtime.sigprof(0x468a6e, 0x282dfb20, 0x0, 0xc00044c180, 0xc00015d880)
        c:/go/src/runtime/proc.go:3890 +0x460
runtime.profilem(0xc00015d880, 0x38c)
        c:/go/src/runtime/os_windows.go:1038 +0xdf
runtime.profileloop1(0x0, 0x0)
        c:/go/src/runtime/os_windows.go:1085 +0x196
runtime.externalthreadhandler(0x2792fbe8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/sys_windows_amd64.s:263 +0x95

**Comment by d1egoaz** [comment]
is there a way to replicate this error? do you have some example code?

**Comment by VijayBhaskar** [comment]
Publisher
-----------
`func main() {
	 // CPU Profile
	cpuProfile, err := os.Create("producer-cpu.prof")
    if err != nil {
        log.Fatal(err)
    }
    pprof.StartCPUProfile(cpuProfile)
	defer pprof.StopCPUProfile()

	startTime := time.Now()
	publishIData()
	
	// Memory Profile
    runtime.GC()
    memProfile, err := os.Create("producer-mem.prof")
    if err != nil {
        log.Fatal(err)
    }
    defer memProfile.Close()
    if err := pprof.WriteHeapProfile(memProfile); err != nil {
        log.Fatal(err)
    }
}

func publishIData() {
	// create producer
	producer, err := initProducer()
	if err != nil {
		fmt.Println("Error producer: ", err.Error())
		os.Exit(1)
	}
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)
	data11 := setIData(setData())
	//Timeout 30 minutes	
	timeout := time.After(30*time.Hour)
	tick := time.Tick(5*time.Second)
	for {
		select {
		case <-timeout:
			return
		case <-tick:
			processAndPublish(producer, data11)
		case <-signals:
			fmt.Println("Interrupt is detected")
			return
		}
	}
}

func initProducer() (sarama.SyncProducer, error) {
	// setup sarama log to stdout
	sarama.Logger = log.New(os.Stdout, "", log.Ltime)

	// producer config
	config := sarama.NewConfig()
	config.Producer.Retry.Max = 5
	//config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.RequiredAcks = sarama.NoResponse 
	config.Producer.Return.Successes = true

	// sync producer
	prd, err := sarama.NewSyncProducer([]string{"localhost:9092"}, config)

	return prd, err
}

func processAndPublish(producer sarama.SyncProducer, iDataSet []*ipb.IData) {
	for i := 0; i < 1000; i++ {
		marshalData1:=marshalData(iDataSet)
		compressData1:=compressData(marshalData1)
		publish(compressData1, producer) 
	}
}

func publish(message []byte, producer sarama.SyncProducer) {
	
	// publish sync
	msg := &sarama.ProducerMessage{
		Topic: "test-topic",
		Value: sarama.ByteEncoder(message),
	}
	p, o, err := producer.SendMessage(msg)
	if err != nil {
		fmt.Println("Error publish: ", err.Error())
		fmt.Println("Partition: ", p)
		fmt.Println("Offset: ", o)
	}
}`

Subscriber
------------
`func main() {
	 // CPU Profile
	 cpuProfile, err := os.Create("subscriber-cpu.prof")
	 if err != nil {
		 log.Fatal(err)
	 }
	 pprof.StartCPUProfile(cpuProfile)
	 defer pprof.StopCPUProfile()
	 
	 processSubscribe()

	 // Memory Profile
	 runtime.GC()
	 memProfile, err := os.Create("subscriber-mem.prof")
	 if err != nil {
		 log.Fatal(err)
	 }
	 defer memProfile.Close()
	 if err := pprof.WriteHeapProfile(memProfile); err != nil {
		 log.Fatal(err)
	 }
	
}

func processSubscribe() {
	config := sarama.NewConfig()
	config.Consumer.Return.Errors = true
	//config.Consumer.Offsets.AutoCommit.Enable = true
	//config.Consumer.Offsets.AutoCommit.Interval = 5*time.Second
	// Specify brokers address.
	brokers := []string{"localhost:9092"}

	// Create new consumer
	master, err := sarama.NewConsumer(brokers, config)
	if err != nil {
		panic(err)
	}

	defer func() {
		if err := master.Close(); err != nil {
			panic(err)
		}
	}()

	topic := "pub-1000-100-50-1dy"
	// set partition
	consumer, err := master.ConsumePartition(topic, 0, sarama.OffsetOldest)
	if err != nil {
		panic(err)
	}

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	msgCount := 0
	startTime := time.Now()
	doneCh := make(chan struct{})
	
	go func() {
		for {
			select {
			case err := <-consumer.Errors():
				fmt.Println(err)
			case msg := <-consumer.Messages():
				msgCount++
				fmt.Println("## Received Message ",msgCount, time.Now())
				processReceivedData(msg)
			case <-signals:
				fmt.Println("Interrupt is detected")
				doneCh <- struct{}{}
			}
		}
	}()

	<-doneCh
			fmt.Println("%%%%%%%%%%Start Time%%%%%%%%%%",startTime)
			fmt.Println("%%%%%%%%%%End time%%%%%%%%%%", time.Now())
}`

**Comment by VijayBhaskar** [comment]
Complete log
---------------

runtime: invalid pc-encoded table f=runtime.goexit pc=0x466f97 targetpc=0x466f97 tab=[0/0]0x0
        value=0 until pc=0x466f97
fatal error: invalid runtime symbol table

runtime stack:
runtime.throw(0x93ff20, 0x1c)
        c:/go/src/runtime/panic.go:1116 +0x79
runtime.pcvalue(0xa6e030, 0xce53e0, 0x6d827, 0x466f97, 0x277ef068, 0xcceb01, 0x8)
        c:/go/src/runtime/symtab.go:790 +0x548
runtime.funcspdelta(0xa6e030, 0xce53e0, 0x466f97, 0x277ef068, 0x8)
        c:/go/src/runtime/symtab.go:844 +0x66
runtime.gentraceback(0x468a6e, 0x2932fb20, 0x0, 0xc000394a80, 0x0, 0x277ef2c0, 0x40, 0x0, 0x0, 0x6, ...)
        c:/go/src/runtime/traceback.go:220 +0x15bc
runtime.sigprof(0x468a6e, 0x2932fb20, 0x0, 0xc000394a80, 0xc0003ce700)
        c:/go/src/runtime/proc.go:3890 +0x460
runtime.profilem(0xc0003ce700, 0x2f4)
        c:/go/src/runtime/os_windows.go:1038 +0xdf
runtime.profileloop1(0x0, 0x0)
        c:/go/src/runtime/os_windows.go:1085 +0x196
runtime.externalthreadhandler(0x277efbe8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/sys_windows_amd64.s:263 +0x95

goroutine 1 [chan receive, 345 minutes]:
main.processSubscribe()
        D:/Vijay/go/go-codebase-metrics/Async/1day-1000msg-5pub-5sub-2topic-100-50/consumer1/go-consumer1.go:102 +0x28a
main.main()
        D:/Vijay/go/go-codebase-metrics/Async/1day-1000msg-5pub-5sub-2topic-100-50/consumer1/go-consumer1.go:34 +0xe6

goroutine 6 [sleep]:
time.Sleep(0x5f5e100)
        c:/go/src/runtime/time.go:188 +0xc8
runtime/pprof.profileWriter(0x9dd6e0, 0xc000006068)
        c:/go/src/runtime/pprof/pprof.go:765 +0x6d
created by runtime/pprof.StartCPUProfile
        c:/go/src/runtime/pprof/pprof.go:750 +0x126

goroutine 24 [select, 6 minutes]:
github.com/Shopify/sarama.(*client).backgroundMetadataUpdater(0xc000156120)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/client.go:779 +0x13a
github.com/Shopify/sarama.withRecover(0xc00008a290)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.NewClient
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/client.go:178 +0x54d

goroutine 22 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0xd0bc20)
        D:/Vijay/go/go-workspace/src/github.com/rcrowley/go-metrics/meter.go:239 +0x38
created by github.com/rcrowley/go-metrics.NewMeter
        D:/Vijay/go/go-workspace/src/github.com/rcrowley/go-metrics/meter.go:46 +0x119

goroutine 23 [chan receive, 6 minutes]:
github.com/Shopify/sarama.(*Broker).responseReceiver(0xc00016e380)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/broker.go:846 +0x9f
github.com/Shopify/sarama.withRecover(0xc00008a250)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*Broker).Open.func1
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/broker.go:211 +0x869

goroutine 12 [chan receive]:
github.com/Shopify/sarama.(*Broker).responseReceiver(0xc000080380)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/broker.go:846 +0x9f
github.com/Shopify/sarama.withRecover(0xc00005ee20)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*Broker).Open.func1
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/broker.go:211 +0x869

goroutine 34 [chan receive, 345 minutes]:
github.com/Shopify/sarama.(*partitionConsumer).dispatcher(0xc0000d8000)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:337 +0x61
github.com/Shopify/sarama.withRecover(0xc000392000)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*consumer).ConsumePartition
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:157 +0x2b2

goroutine 35 [select]:
github.com/Shopify/sarama.(*partitionConsumer).responseFeeder(0xc0000d8000)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:458 +0x1be
github.com/Shopify/sarama.withRecover(0xc000392010)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*consumer).ConsumePartition
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:158 +0x304

goroutine 36 [select]:
github.com/Shopify/sarama.(*brokerConsumer).subscriptionManager(0xc000398000)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:748 +0x389
github.com/Shopify/sarama.withRecover(0xc000392020)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*consumer).newBrokerConsumer
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:721 +0x155

goroutine 37 [semacquire]:
sync.runtime_Semacquire(0xc000398038)
        c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc000398030)
        c:/go/src/sync/waitgroup.go:130 +0x6b
github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer(0xc000398000)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:793 +0x21b
github.com/Shopify/sarama.withRecover(0xc000392030)
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/utils.go:43 +0x50
created by github.com/Shopify/sarama.(*consumer).newBrokerConsumer
        D:/Vijay/go/go-workspace/src/github.com/Shopify/sarama/consumer.go:722 +0x1a3

goroutine 38 [syscall, 345 minutes]:
os/signal.signal_recv(0x0)
        c:/go/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1
        c:/go/src/os/signal/signal.go:127 +0x4b

goroutine 39 [runnable]:
reflect.Value.Set(0x8af4c0, 0xc001f0a028, 0x194, 0x89dec0, 0xc0016d3050, 0x16)
        c:/go/src/reflect/value.go:1525 +0x13f
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOneofFieldCoders.func1(0xc001d2627b, 0x14, 0x19b85, 0xc001f0a028, 0xce5302, 0xc000136508, 0x449500, 0x9dfe60, 0xc000110a80, 0x8f2080, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/codec_field.go:66 +0x2f1
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc00015f4e0, 0xc001d2627b, 0x15, 0x19b85, 0xc001f0a000, 0x0, 0x0, 0x9dfe60, 0xc000110a80, 0x2030007, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/decode.go:137 +0x5cf
google.golang.org/protobuf/internal/impl.consumeMessageInfo(0xc001d26279, 0x1d, 0x19b87, 0xc001f09fe8, 0xce5302, 0xc000072000, 0x449500, 0x9dfe60, 0xc000110a80, 0x8f1fa0, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/codec_field.go:250 +0x1b5
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc00015f3a8, 0xc001d26279, 0x1e, 0x19b87, 0xc001f09fc0, 0xc000000000, 0x0, 0x9dfe60, 0xc000110a80, 0x1e, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/decode.go:137 +0x5cf
google.golang.org/protobuf/internal/impl.consumeMessageSliceInfo(0xc001d26277, 0xbf, 0x19b89, 0xc0016e6200, 0xce5302, 0xc00005d698, 0x449500, 0x9dfe60, 0xc000110a80, 0x1f, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/codec_field.go:501 +0x248
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc00015f138, 0xc001d26277, 0x65b, 0x19b89, 0xc0016e61c0, 0xc000000000, 0x600, 0x9dfe60, 0xc000110a80, 0x65b, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/decode.go:137 +0x5cf
google.golang.org/protobuf/internal/impl.consumeMessageSliceInfo(0xc001d25cd9, 0x1fd5, 0x1a127, 0xc001ac1928, 0x2, 0xc0000ee120, 0xd3d100, 0x9dfe60, 0xc000110a80, 0x65d, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/codec_field.go:501 +0x248
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshalPointer(0xc00015f000, 0xc001d25cd9, 0x27cae, 0x1a127, 0xc001ac1900, 0xc000000000, 0x8a4100, 0x9dfe60, 0xc000110a80, 0x9dd020, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/decode.go:137 +0x5cf
google.golang.org/protobuf/internal/impl.(*MessageInfo).unmarshal(0xc00015f000, 0x9ed0e0, 0xc001ac1900, 0xc001d00000, 0x27cae, 0x3fe00, 0x0, 0x9dfe60, 0xc000110a80, 0x82098f, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/internal/impl/decode.go:60 +0xb9
google.golang.org/protobuf/proto.UnmarshalOptions.unmarshal(0x101, 0x9dfe60, 0xc000110a80, 0xc001d00000, 0x27cae, 0x3fe00, 0x9ed0e0, 0xc001ac1900, 0xc000649080, 0xc000649080, ...)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/proto/decode.go:91 +0x29e
google.golang.org/protobuf/proto.Unmarshal(0xc001d00000, 0x27cae, 0x3fe00, 0x9dd020, 0xc001ac1900, 0x3fe00, 0x0)
        D:/Vijay/go/go-workspace/src/google.golang.org/protobuf/proto/decode.go:49 +0x90
main.processReceivedData(0xc000d760a0)
        D:/Vijay/go/go-codebase-metrics/Async/1day-1000msg-5pub-5sub-2topic-100-50/consumer1/go-consumer1.go:114 +0x131
main.processSubscribe.func2(0x9e67e0, 0xc0000d8000, 0xc000382020, 0xc0003800c0, 0xc000396120)
        D:/Vijay/go/go-codebase-metrics/Async/1day-1000msg-5pub-5sub-2topic-100-50/consumer1/go-consumer1.go:92 +0x1f7
created by main.processSubscribe
        D:/Vijay/go/go-codebase-metrics/Async/1day-1000msg-5pub-5sub-2topic-100-50/consumer1/go-consumer1.go:86 +0x273
exit status 2

**Comment by dnwe** [comment]
@VijayBhaskar this looks like an issue with the Go toolchain on Windows in the 1.14 release rather than an issue with Sarama. Please re-open if you still see the problem with 1.21
