### ISSUE TITLE
Write an consumer with consumer group and manually commit offset by partition (example)

### ISSUE THREAD

**Issue by ut0mt8** [IBM/sarama#1780]
Hello,

I search for an example on google but don't find it for the moment; this is why I asking here.
So I have an application that consume from a kafka topic. The goal of this app is to read msg from kafka, to group them according to a partition key (let say in theory each group of message should be already in the same partition), and then accumulate them by group, at a point, let say when each group is either too or too big write the group to a secure location (let say s3). The tricks is I only want to commit a message once I'm sure he is definitively stored in my secure location.
So I need to have the ability to manually commit on a specific partition up to a specific message number.
Do we have example for that ?

Thks.

**Comment by i7tsov** [comment]
Somewhat late here, but hope this helps. See example in https://godoc.org/github.com/Shopify/sarama#ConsumerGroup

```go
sess.MarkMessage(msg, "")
```
Marks message as consumed.

**Comment by ut0mt8** [comment]
Yes ended with a custom ConsumeClaim function not calling sess.MarkMessage after receiving each message, but rather having a structure storing low watermark for each partition, and calling session.MarkOffset when my message were safe.

**Comment by joselsegura** [comment]
I used a similar approach. I want to perform the offset commit when I'm sure of the correct handling of the received messages, so I created a second implementation of `ConsumerGroupHandler` that is only used to mark offsets from a data structure that I defined (more or less, a `map[str]map[int64]int32`

**Comment by joselsegura** [comment]
You can always reset the offset using `sess.ResetOffset(topic, partition, desiredOffset, "")`

**Comment by dnwe** [comment]
@ut0mt8 yes so a combination of disabling AutoCommit in your sarama.Config (`conf.Consumer.Offsets.AutoCommit.Enable = false`) and then either `session.MarkMessage(message, "")` or `session.MarkOffset(topic, partition, msgOffset+1, "")` when you want to mark a given partition's offset to be included in the next offset commit for the consumer. Finally when you want to persist your offsets to Kafka you'd call `session.Commit()` which is a synchronous blocking call
