### ISSUE TITLE
Exporting decoders

### ISSUE THREAD

**Issue by pkositsyn** [IBM/sarama#1786]
##### Problem Description

Currently I'm working on a kafka-sniffer and it's very useful to have the decode functions exported, otherwise it's necessary to copy a lot of code.
Maybe my case is very individual, but actually I don't quite understand what is the purpose of request decoders, except for testing and why shouldn't they be exposed. What do you think about it and maybe the opportunity to include sniffer in your project? It can provide useful information from brokers about all clients using it, which can be very helpful in major projects

**Comment by twmb** [comment]
Maybe [this package](https://pkg.go.dev/github.com/twmb/kafka-go/pkg/kmsg?tab=doc) can help you?

**Comment by Vemmy124** [comment]
This could be helpful if it was working. I will leave the issues I found there, but I would prefer at least tested solutions

**Comment by twmb** [comment]
Thanks, it is tested. Please see [this](https://github.com/twmb/kcl/) for extensive usage. I'm curious to know what isn't working from your perspective.
