### ISSUE TITLE
how to set max.poll.interval.ms

### ISSUE THREAD

**Issue by NessGo** [IBM/sarama#1795]
how to set the value of max.poll.interval.ms
| Sarama | Kafka | Go |
|--------|-------|----|
| 1.26.1 | 0.10.2.1 | 1.13.7 |

**Comment by nikolaydimitrov** [comment]
I'm also interested in this

**Comment by dnwe** [comment]
@NessGo  Sarama has `MaxProcessingTime` as a config parameter similar to the Java client's `max.poll.interval.ms` https://github.com/IBM/sarama/blob/d2dba29e9545c5af80169e541b1170c3dd34b3b9/config.go#L391-L408 

It is a locally enforced client timeout and is separate from the heartbeat to the server which keeps the session alive. See "Decoupling the processing timeout" in [KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread)
