### ISSUE TITLE
Encounter the error like ErrClosedConsumerGroup?

### ISSUE THREAD

**Issue by LWP-PING** [IBM/sarama#1806]
var ErrClosedConsumerGroup = errors.New("kafka: tried to use a consumer group that was closed")
if the above error cause by the kafka reblance or anything else?

**Comment by JDLK7** [comment]
@LWP-PING You get this error when you try call the method `Consume` on a consumer group that has been closed from the client's side: https://github.com/Shopify/sarama/blob/4e92ad6f0b7dfa78b2a64e0432d51c53f1e155ef/consumer_group.go#L12

**Comment by dnwe** [comment]
Closing as answered
