### ISSUE TITLE
Setting `config.Producer.Timeout` is not valid!

### ISSUE THREAD

**Issue by qiangmzsx** [IBM/sarama#1807]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|1.27.0  |1.1.0  |1.14.2  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
mqConfig.Metadata.Retry.Max = config.Retry
	log.Println("===========")
	mqConfig.Producer.Timeout = 1 
	mqConfig.Producer.Return.Errors = true
	mqConfig.Producer.RequiredAcks = 1
```

##### Logs
no error log

<details><summary>logs: CLICK ME</summary>
<p>

```

```

</p>
</details>

##### Problem Description
Set `config.Producer.Timeout` to run no matter how small, as long as it is not 0, then it will run normally, even if it takes significantly more time than the set `timeout`.

**Comment by genzgd** [comment]
it would be nice if someone could look at the producer timeout.  We occasionally see data corruption when there are network problems and it feels like it's because memory that Sarama has released is being overwritten with new data when the connection stays open indefinitely.

**Comment by dnwe** [comment]
@genzgd is that something you still see in recent versions? That’s not one I’ve heard of before. Please open an issue for it if you do

@qiangmzsx to check that I’m understanding the issue you describe, you’re saying that you’ve set Timeout to a very short value but find that your produce request carries on for as long as it needs to complete and doesn’t abort after the timeout elapses?

**Comment by genzgd** [comment]
I'm no longer associated with the project that used Sarama and I don't remember anything about this issue other than what I commented above.  :)
