### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by reallocf** [IBM/sarama#1829]
Hey all,

Looking at https://github.com/Shopify/sarama/issues/901 I see that @buyology got pretty far with supporting Kafka Transactions, but I don't see the related code so maybe it didn't make it all the way in? Am I getting that right from the docs/code? Not seeing any A/SyncProducer `Begin()`, `CommitOffsets(...)`, `Commit()`, or `Abort()` methods, for example - though I do see a TransactionManager that maybe does some of the heavy lifting?

If it isn't currently supported, would love to know if anybody is working on it currently (@buyology are you interested in digging up your old code? 😃 ). If not, let me know if contributions are welcome and I might be able to throw some spare cycles at it.

**Comment by tony-clarke-amdocs** [comment]
Also interested to know the state of this?
