### ISSUE TITLE
Why different assignment data types for CreateTopic and AlterPartitionReassignments?

### ISSUE THREAD

**Issue by ppatierno** [IBM/sarama#1834]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 |2.6.0  |1.13.15  |

##### Problem Description

It's more a question than a problem. Is there any specific reason why the `CreateTopic` through the `TopicDetail.ReplicaAssignment` gets the replicas assignment as a `map[int32][]int32` while the `AlterPartitionReassignments` gets it as `[][]int32`?

**Comment by random-dwi** [comment]
There is no specific reason behind it. When we implemented `AlterPartitionReassignments` we just did not think about aligning those two parameter types.
It would be more consistent though.

**Comment by ppatierno** [comment]
If I would contribute to this. What's the idea behind Sarama community about breaking changes? Do we need a new method with the `map` parameter and deprecating the previous one (that will be removed in the new version)? Or just breaking for the new coming version?

**Comment by random-dwi** [comment]
This can perhaps be answered by @dnwe ?

**Comment by dnwe** [comment]
Yes in the v1 series we’d have to extend and deprecate. In the. 2 series we have take api breaking changes
