### ISSUE TITLE
Improve SASL implementation

### ISSUE THREAD

**Issue by matzew** [IBM/sarama#1837]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.x | 2.x  | 1.14  |

##### Configuration

For doing SASL most clients have similar code to this:

```go
	if *algorithm == "sha512" {
		conf.Net.SASL.SCRAMClientGeneratorFunc = func() sarama.SCRAMClient { return &XDGSCRAMClient{HashGeneratorFcn: SHA512} }
		conf.Net.SASL.Mechanism = sarama.SASLTypeSCRAMSHA512
	} else if *algorithm == "sha256" {
		conf.Net.SASL.SCRAMClientGeneratorFunc = func() sarama.SCRAMClient { return &XDGSCRAMClient{HashGeneratorFcn: SHA256} }
		conf.Net.SASL.Mechanism = sarama.SASLTypeSCRAMSHA256

	} else {
		log.Fatalf("invalid SHA algorithm \"%s\": can be either \"sha256\" or \"sha512\"", *algorithm)
	}
```

##### Problem Description

The problem is that each implementation seems to "copy" / "borrow" the code for the actual `SCRAMClientGeneratorFunc`. Mostly copying this file:
https://github.com/Shopify/sarama/blob/master/examples/sasl_scram_client/scram_client.go

I am wondering if it makes sense to bake this util into the sarama client itself. So that developers could have some better reuse?

**Comment by 4lt1** [comment]
I've been facing the same problem trying to add sasl/scram-sha-(256|512) support on https://github.com/open-telemetry/opentelemetry-collector.
In my point of view would be great to have this implementation in the sarama client side.

**Comment by AlbertoPeon** [comment]
great idea to add it to the library!
