### ISSUE TITLE
Client.RefreshMetadata doesn't trigger consumer rebalance when new partitions exist

### ISSUE THREAD

**Issue by ppatierno** [IBM/sarama#1839]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|1.27.2  |2.7.0  | 1.13.15 |

##### Problem Description

I am using a `Client` to create a sync producer and a consumer group and they are exchanging messages through a topic with N partitions; the producer is sending messages to specific partitions for my purpose.
There is a use case where I increase the partitions. At this point, I need to refresh metadata from the `Client` (using `RefreshMetadata` function) otherwise the producer is not aware of the new partitions. It works fine and producer starts to send messages to the new partitions.
The same doesn't work on the consumer side. The client is common but when refreshing metadata, it seems that the consumer group still see older metadata and doesn't receive messages sent by the producer on the new partitions.
Why?

Just as a note, the consumer metadata are correctly updated if I don't force through the `RefreshMetadata` function but set a metadata timeout to something short (2 secs for example) but of course it's not what I want.
I want to refresh metadata when I know that something is changed in the cluster (I have an admin part in my application checking the cluster and partitions topology periodically).

**Comment by ppatierno** [comment]
I think I got it. Refreshing metadata is not enough, of course, a rebalance is needed to be triggered and as far as I can see from the code it's done when the session is exited and a new one created.
So the only way I see in my case is detecting the partitions change, then calling `<-session.ctx.Done()` to allow the session to exit and finally calling `Consume` again in order to init a new session and rejoining the group with new partitions.
Did I get it right? Or is there a simpler way?

**Comment by ppatierno** [comment]
Reading the code I need something like the `loopCheckPartitionNumbers` so being able to cancel the session from outside allowing to call the consume again and refreshing the metadata (not periodically as it works) but on purpose.

**Comment by ppatierno** [comment]
Reading more about the Sarama source code, the metadata are refreshed every metadata refresh timeout because it justs end the current session and exits the `Consume` function. The application needs to call `Consume` again (as described in the doc/examples) in order to refresh metadata, creating a new session, and joining the group again.

**Comment by yuzhichang** [comment]
I have the same issue. 
Sarama: v1.29.1
