### ISSUE TITLE
Consume and ack messages in parallel out of order

### ISSUE THREAD

**Issue by longquanzheng** [IBM/sarama#1840]
Hi what is the recommended way to consume and ack messages in parallel out of order? (to improve throughput) 
At first glance of this `MarkMessage` I thought it's supported but looking into the implementation, it simply call `MarkOffset` inside it:  
https://github.com/Shopify/sarama/blob/0616f68815691527d3b6ab4d95a2881e09400fe3/consumer_group.go#L643

So I think if I directly use `MarkMessage` to ack messages out of order, I may lose messages during some deployment/rebalances. Is that correct? 

Any help is appreciated! Thanks in advance.

**Comment by dnwe** [comment]
Yep, If they’re for the same topic-partition then yes you may potentially lose messages as you commit newer offsets . Committing offsets in Kafka is always committing “this is the latest offset I’ve processed” for a given topic partition. You’re not individually ACKing each record
