### ISSUE TITLE
Invalid CRC on Multi-Record RecordBatches 

### ISSUE THREAD

**Issue by jaxonpickett** [IBM/sarama#1841]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.26.4 | 2.12-2.0.1 | 1.12.17 |

##### Problem Description

When attempting to produce a batch of records, the broker is responding with ErrInvalidMessage and the messages are not being written to the topic. If only a single-record batch is sent, the response is successful and the data reaches the topic.

Example Code:
```
package kafka

import (
	"github.com/Shopify/sarama"
	"github.com/stretchr/testify/require"
	"testing"
	"time"
)

func TestBatchProduce(t *testing.T) {
	cfg := sarama.NewConfig()
	cfg.Version = sarama.V2_0_1_0

	client, err := sarama.NewClient([]string{"0.0.0.0:9092"}, cfg)
	require.NoError(t, err, "NewClient() failed")

	broker, err := client.Leader("sandbox", 0)
	require.NoError(t, err, "client.Leader() failed")

	req := &sarama.ProduceRequest{
		RequiredAcks: sarama.WaitForLocal,
		Timeout:      int32(10 * time.Second / time.Millisecond),
		Version:      3,
	}

	start := time.Now()

	batch := &sarama.RecordBatch{
		Version:        2, // only supported version of RecordBatch
		ProducerID:     -1,
		FirstTimestamp: start,
		Records: []*sarama.Record{
			{
				TimestampDelta: 2 * time.Millisecond,
				Value:          []byte("test message one"),
			},
			{
				TimestampDelta: 2 * time.Millisecond,
				Value:          []byte("test message two"),
			},
		},
	}

	req.AddBatch("sandbox", 0, batch)

	resp, err := broker.Produce(req)
	require.NoError(t, err, "broker.Produce() failed")

	block := resp.GetBlock("sandbox", 0)
	if block != nil && block.Err != sarama.ErrNoError {
		require.Fail(t, "Response Error", block.Err.Error())
	}
}

```

Running kafka in docker locally, the results of the test are:
```
--- FAIL: TestBatchProduce (0.02s)
    batch_producer_send_test.go:57: 
                Error Trace:    batch_producer_send_test.go:57
                Error:          Response Error
                Test:           TestBatchProduce
                Messages:       kafka server: Message contents does not match its CRC.
FAIL
FAIL    command-line-arguments  0.467s
```
I've tried every possible permutation of field values for the Request, RecordBatch, and Record with no success. I've also tried using the v2 request pattern of using MessageBlock and MessageSet, which works just fine. 

Surely I'm missing something, this seems like such a straightforward use case.

Thanks for taking a look!

**Comment by dnwe** [comment]
Hmmm. Is this something you can still reproduce on recent versions? Is there a reason why you’re calling broker.Produce directly rather than using the Producer?
