### ISSUE TITLE
Acception context for sync produce message

### ISSUE THREAD

**Issue by longquanzheng** [IBM/sarama#1849]
##### Problem Description
https://github.com/Shopify/sarama/blob/0616f68815691527d3b6ab4d95a2881e09400fe3/sync_producer.go#L20

Please allow passing in context.Context
https://blog.golang.org/context

It's important for error handling.

**Comment by r-novel** [comment]
@dnwe Hello, Dominic. Do you have any updates about your investigation? I think support context.Context in produce methods is very actual.
