### ISSUE TITLE
Static membership = cooperative-sticky

### ISSUE THREAD

**Issue by syepes** [IBM/sarama#1854]
Since kafka 2.3 it has been possible to use static membership across multiple group generations.
If a consumer goes down, a rebalance does not occur right away allowing for the crashed instance to pick up the same partitions when its back up again.

[KIP-345](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances)

`"partition.assignment.strategy" =  "cooperative-sticky",`

Is this consumer feature currently supported?

**Comment by lizthegrey** [comment]
Dupe of #1858

**Comment by lavoiesl** [comment]
The linked [KIP-345](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances) is about static membership, but AFAICT, `"partition.assignment.strategy" = "cooperative-sticky"` is about [KIP-341](https://cwiki.apache.org/confluence/display/KAFKA/KIP-341%3A+Update+Sticky+Assignor%27s+User+Data+Protocol), which is implemented in https://github.com/Shopify/sarama/pull/1416.
