### ISSUE TITLE
client/metadata got error from broker -1 while fetching metadata

### ISSUE THREAD

**Issue by jectpro7** [IBM/sarama#1865]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 | 2.11 | 1.15.6 |

##### Configuration
Sarama config
``` 
config := sarama.NewConfig()
sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)
config.Producer.RequiredAcks = sarama.WaitForAll
config.Producer.Return.Successes = true
config.Producer.Partitioner = sarama.NewRandomPartitioner
msg := &sarama.ProducerMessage{}
fmt.Println("connecting...")
producer, err := sarama.NewSyncProducer([]string{"192.168.13.128:9092"}, config)
```

##### Logs
<details><summary>sarama logs: CLICK ME</summary>
<p>

```
[sarama] 2020/12/28 21:33:44 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2020/12/28 21:33:44 client/metadata fetching metadata for all topics from broker 192.168.13.128:9092
[sarama] 2020/12/28 21:33:44 Connected to broker at 192.168.13.128:9092 (unregistered)
[sarama] 2020/12/28 21:34:14 client/metadata got error from broker -1 while fetching metadata: read tcp 192.168.13.1:62343->192.168.13.128:9092: i/o timeout
[sarama] 2020/12/28 21:34:14 Closed connection to broker 192.168.13.128:9092
[sarama] 2020/12/28 21:34:14 client/metadata no available broker to send metadata request to
[sarama] 2020/12/28 21:34:14 client/brokers resurrecting 1 dead seed brokers
[sarama] 2020/12/28 21:34:14 client/metadata retrying after 250ms... (3 attempts remaining)
```

</p>
</details>

##### Problem Description
Hi, I cannot send msg by using sarama. Neither can I recieve msg from kafka. I am pretty sure my cofiguration of kafka and zookeeper are correct, because I have successfully sent msg to kafka by using python-kafka.
I installed kafka and zookeeper in a virtual machine, Centos7. And I ran sarama with my PC, Win10.
Thanks

**Comment by dfriel** [comment]
We are seeing the same issue


Sarama | Kafka | Go
-- | -- | --
2a5254c |  kafka_2.10-0.9.0.0 | go1.15.6 darwin/amd64

**Comment by DiaosX** [comment]
i meet  the same issue

Sarama | Kafka | Go
-- | -- | --
1.27.2 | 2.11 | 1.15.4

i aslo try to  the Sarama  v1.27.1, it has the same issue, but v1.27.0 it work well.

**Comment by dnwe** [comment]
@jectpro7 and you were definitely using the same TLS and SASL settings for both?
