### ISSUE TITLE
in the cluster case， only input single node config , can use full cluster ability ?

### ISSUE THREAD

**Issue by Tokumicn** [IBM/sarama#1867]
ConsumePartition：partitionConsumer.consumer.client

1. client.seedBrokers ===> {192.168.1.1:9092,192.168.1.1:9093,192.168.1.1:9094}
    at this time: client.brokers ===>  {192.168.1.1:9092,192.168.1.1:9093,192.168.1.1:9094}

2. client.seedBrokers ===> {192.168.1.1:9092}   // only single node config but got full cluster brokers
    at this time: client.brokers ===>  {192.168.1.1:9092,192.168.1.1:9093,192.168.1.1:9094}

 in the cluster case， only input single node config , can use full cluster ability ?

**Comment by dnwe** [comment]
Yes like the Java client, Sarama just uses the bootstrap addresses in order to fetch the cluster metadata. After that point it uses whatever advertised listener addresses returned in the metadata response
