### ISSUE TITLE
Telegraf - How does Sarama select which broker to connect to when a list is supplied

### ISSUE THREAD

**Issue by clever-trevor** [IBM/sarama#1872]
Question

The Telegraf monitoring agent has an output plugin which posts metrics to Kafka, utilising the Sarama project.
[https://github.com/influxdata/telegraf/tree/master/plugins/outputs/kafka](url)

Within the Telegraf config, you specify a variable containing a string of one or more Brokers as follows 
`brokers = ["localhost:9092","10.1.2.3:9092","1.2.3.4:9092"]`

What I'm not clear on is how the selection is made on which broker to connect to, and the behaviour when that broker becomes unavailable.

Additional Info
I took a quick look at the code and within the Telegraf kafka plugin, I believe this is the line which creates the Kafka connection 
`producerFunc: sarama.NewSyncProducer,`

(Forgive me if this is wrong, I'm not a Go programmer)

I initially raised this with InfluxData who support Telegraf (link below) in case that adds any additional info but they were unable to help as the Sarama code is not written by them
[https://community.influxdata.com/t/how-does-telegraf-kafka-output-determine-what-broker-to-use-when-multiple-are-speecified/17342](url)

**Comment by schmorgs** [comment]
Any update here?

**Comment by AnuragJ05** [comment]
It looks like sarama picks the first one from the list and ignores the rest, Is this a bug?

**Comment by dnwe** [comment]
That’s not the case. Sarama will shuffle those bootstrap addresses on request. It will cycle through them to gain connectivity and then uses the advertised listeners for each broker when determining how to connect to those
