### ISSUE TITLE
client has run out of available brokers to talk to 

### ISSUE THREAD

**Issue by zylixn** [IBM/sarama#1877]
##### Versions

client has run out of available brokers to talk to 

| Sarama | Kafka | Go |
|V1.27.2|0.11.0.3|----|

使用V1.26.2问题就解决了
##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by z2665** [comment]
from sarama 1.27.1, the default kafka version  set to 1.0.0
see [this diff](https://github.com/Shopify/sarama/pull/1791/files#diff-8b7f25bac2ae04c2ce2abb628c6aa28103fd113103a62f3e9d232fa995684915R195) 
so you should set the  sarama config
```golang
config.Version = sarama.V0_11_0_2
```

**Comment by dnwe** [comment]
Believed to be resolved by the above
