### ISSUE TITLE
no config related to max.poll.interval.ms ?

### ISSUE THREAD

**Issue by joshua0x** [IBM/sarama#1879]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by LucasDove** [comment]
as far as I know, MaxProcessingTime is equivalent to max.poll.interval.ms.

**Comment by dnwe** [comment]
@joshua0x  Sarama has `MaxProcessingTime` as a config parameter similar to the Java client's `max.poll.interval.ms` https://github.com/IBM/sarama/blob/d2dba29e9545c5af80169e541b1170c3dd34b3b9/config.go#L391-L408 

It is a locally enforced client timeout and is separate from the heartbeat to the server which keeps the session alive. See "Decoupling the processing timeout" in [KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread)
