### ISSUE TITLE
async producer does not recover after a short transport failure

### ISSUE THREAD

**Issue by mtirpak** [IBM/sarama#1884]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 |  2.7.0 |  1.14 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
    config := sarama.NewConfig()
    config.Producer.Idempotent = true
    config.Producer.RequiredAcks = sarama.WaitForAll
    config.Net.MaxOpenRequests = 1
    config.Producer.Return.Successes = true
```

##### Logs

[producer.log](https://github.com/Shopify/sarama/files/5982696/producer.log)

##### Problem Description
Almost all the messages sent by the asynchronous producer fail after a short network outage and the producer does not recover even after half an hour.

Various failures are indicated by the attached logs after reconnecting to the brokers:
 - When the state changes to flushing: `assertion failed: message out of sequence added to a batch`
 - Errors from the brokers: `kafka server: The broker received an out of order sequence number.`
 - Another broker error: `kafka server: Producer attempted an operation with an old epoch.`
 - The transaction manager keeps bumping the epoch: `rolling over epoch due to publish failure`
 - Producer error: `detected epoch rollover, waiting for new buffer`

After the network recovery, approximately 70% of the messages failed 1-2 minutes long, then all started to fail and the producer did not recover. The last 3 error messages from the above list kept repeating.

**Comment by maqdev** [comment]
Still happening in v1.37.2
