### ISSUE TITLE
GetMemberMetadata memory leak

### ISSUE THREAD

**Issue by brzyangg** [IBM/sarama#1895]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.27.0 | v2.2.1 | v1.15.0 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        config := sarama.NewConfig()
	config.Version = sarama.V2_0_0_0
	config.Metadata.RefreshFrequency = 5 * time.Minute
	config.Net.KeepAlive = 15 * time.Minute
	config.Net.MaxOpenRequests = 102
```

##### Problem Description

GroupMemberDescription.GetMemberMetadata() cause a memory leak

```
Type: alloc_space
Time: Mar 3, 2021 at 2:24pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 26735.95MB, 99.77% of 26798.87MB total
Dropped 290 nodes (cum <= 133.99MB)
      flat  flat%   sum%        cum   cum%
26735.45MB 99.76% 99.76% 26735.45MB 99.76%  github.com/Shopify/sarama.(*realDecoder).getStringArray
   26.11GB    26.11GB (flat, cum) 99.76% of Total
         .          .    335:
         .          .    336:	if n < 0 {
         .          .    337:		return nil, errInvalidArrayLength
         .          .    338:	}
         .          .    339:
   26.11GB    26.11GB    340:	ret := make([]string, n)
         .          .    341:	for i := range ret {
         .          .    342:		str, err := rd.getString()
         .          .    343:		if err != nil {
         .          .    344:			return nil, err
         .          .    345:		}
```
![image](https://user-images.githubusercontent.com/29059790/109766979-dee93800-7c31-11eb-818c-d01d06ae9ba2.png)

**Comment by dnwe** [comment]
@brzyangg GetMemberMetadata() on a DescribeGroupsResponse isn't something that Sarama calls internally. Yes memory is allocated as part of decoding the member metadata and returned in the `ConsumerGroupMemberMetadata` value. If the application code making that call is keeping references to those such that they aren't getting free'ed then that would appear as a memory leak in our code, but I think that ultimately the references to that memory would be in the application code and not something we could fix
