### ISSUE TITLE
Add warning logger for big requestLatency

### ISSUE THREAD

**Issue by j2gg0s** [IBM/sarama#1903]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 0eba6f6c0c31f37c3a7d4ee6c3ca22e1120ff7af |  2.6.x | 1.15  |

Can i add some warning log for requestLatency bigger than 1 or 5 second?

In my case, i consume message quickly and send too much fetch request.
This make heartbeat loop blocking on receive response, and consumer member be timeout.

**Comment by dnwe** [comment]
@j2gg0s I'm not sure that a log line would be appropriate for this — you'd be better off monitoring the requestLatency metric value yourself and alerting upon it

**Comment by j2gg0s** [comment]
Agree，And we change to jmx and prometheus
