### ISSUE TITLE
两个主题都是堆积消息,然后同时进行消费时,会发生阻塞.

### ISSUE THREAD

**Issue by wjw1758548031** [IBM/sarama#1907]
两个主题都是堆积消息
每个主题对应不同的group
每个主题都有n个消费端,以及24个分区。
kafka是单例模式(单机部署)
如果两个主题同时消费,那么就会有冲突,会造成有些主题的分区并没有活跃对象,
甚至整个主题都不会被消费了.

**Comment by dnwe** [comment]
Closing as no response — please re-open with the information if this is still a problem
