### ISSUE TITLE
Obtain the remote broker IP address corresponding to the sending message through Sarama

### ISSUE THREAD

**Issue by freemindLi** [IBM/sarama#1908]
Using Sarama to send messages to Kafka cluster asynchronously and receive the returned message from the successes channel, how can I know which blocker received the message and responded to it (yes, I want to know the broker IP address of receiving each message);
At present, when sending messages to Kafka cluster, some of the responses are very late, and some of the responses are very small. We need to know which brokers are slow in response or network delay. So we plan to type out the broker IP address of the response in the Success channel to locate the specific broker conveniently. But, we don't see that Sarama has this function. Please tell me how to solve it

**Comment by machicao2013** [comment]
Please tell me how to solve it

**Comment by machicao2013** [comment]
> > > Using Sarama to send messages to Kafka cluster asynchronously and receive the returned message from the successes channel, how can I know which blocker received the message and responded to it (yes, I want to know the blocker IP address of receiving each message);
> > > At present, when sending messages to Kafka cluster, some of the responses are very late, and some of the responses are very small. We need to know which blockers are slow in response or network delay. So we plan to type out the blocker IP address of the response in the Success channel to locate the specific blocker conveniently. But we don't see that Sarama has this function. Please tell me how to solve it
> > 
> > 
> > 请问这个问题解决了没
> 
> No,look at the Sarama source code, can't get the remote broker IP from the responses that from the success channel normally. Maybe you can set the timeout time a little bit smaller, so that requests that haven't responded for more than a little time will report an error（get error info from ERROR channel）. In this way, you can see which broker you are interacting with！

如果是把超时时间调小才能获取到ip，那就没有意义了。我希望获取到broker ip，然后进行上报。

**Comment by dnwe** [comment]
Closing as assumed to be fixed by the above comment
