### ISSUE TITLE
'SASL Authentication failed' during rolling restart after adding new nodes

### ISSUE THREAD

**Issue by Asthetic** [IBM/sarama#1940]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 |2.4.1.1|1.15.3|

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
conf := sarama.NewConfig()

conf.Metadata.Full = true
conf.Admin.Timeout = 6 * time.Second

conf.Producer.RequiredAcks = sarama.WaitForLocal
conf.Producer.Return.Successes = true

conf.Version = sarama.V2_4_0_0
conf.ClientID = "sasl_scram_client"
conf.Net.TLS.Enable = true
conf.Net.TLS.Config = &tls.Config{
	InsecureSkipVerify: true,
}

conf.Net.SASL.Enable = true
conf.Net.SASL.Handshake = true
conf.Net.SASL.Mechanism = sarama.SASLTypeSCRAMSHA512
conf.Net.SASL.SCRAMClientGeneratorFunc = ...
```

Kafka: 
```
auto.create.topics.enable=false
compression.type=zstd
default.replication.factor=3
min.insync.replicas=2
num.io.threads=8
num.network.threads=5
num.partitions=1
num.replica.fetchers=2
replica.lag.time.max.ms=30000
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
unclean.leader.election.enable=false
zookeeper.session.timeout.ms=18000
```
Everything else is default Kafka config values

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
2021/05/08 01:52:07 Connected to broker at b-3.clustername.kafka.us-west-2.amazonaws.com:9096 (registered as #3)
2021/05/08 01:52:07 SASL authentication succeeded
2021/05/08 01:52:07 Connected to broker at b-3.clustername.kafka.us-west-2.amazonaws.com:9096 (registered as #3)
2021/05/08 01:52:07 Closing Client
2021/05/08 01:52:07 Closed connection to broker b-1.clustername.kafka.us-west-2.amazonaws.com:9096
2021/05/08 01:52:07 Closed connection to broker b-3.clustername.kafka.us-west-2.amazonaws.com:9096
2021/05/08 01:52:07 Error while closing connection to broker b-3.clustername.kafka.us-west-2.amazonaws.com:9096: write tcp ip_here:37860->ip_here:9096: i/o timeout
2021/05/08 01:52:07 Error closing broker -1 : write tcp ip_here:37860->ip_here:9096: i/o timeout
2021/05/08 01:52:07 Closed connection to broker b-2.clustername.kafka.us-west-2.amazonaws.com:9096
```

Interesting that I don't see "client/metadata failed SASL authentication"

</p>
</details>

##### Problem Description
I'm using an MSK Kafka Cluster and have been getting a "SASL Authentication failed." error while upgrading the number of brokers in AWS. After contacting AWS support they confirmed that when adding additional brokers they will perform a rolling restart which will cause a broker to reject connections/auth/requests during this time. We have a replication factor of 3 nodes and a minISR of 1 (which is the default value) and therefore rolling restarts should have no impact on our operations and we should be able to make requests to the admin API, however it appears that sarama does not attempt a retry on a different broker [client.go](https://github.com/Shopify/sarama/blob/master/client.go#L911)

I'll try and update this issue with logs if necessary. I'm going to look through them and make sure there's no confidential information.

I'm by no means a Kafka expert and it's possible I have something misconfigured, I'd appreciate any insight.

**Comment by dnwe** [comment]
It would be worth making sure that you're using the latest Sarama and/or `config.Net.SASL.Version = sarama.SASLHandshakeV1` which should give you a proper error message when connectivity drops, rather than a generic 'SASL Authentication failed' which covered a variety of issues in older versions of Kafka before 0.9
