### ISSUE TITLE
Sticky producer partitioning

### ISSUE THREAD

**Issue by seizethedave** [IBM/sarama#1961]
We use the default hash+random partitioner with a multi-partition topic and we do not use keys, so we rely on the Sarama producer to randomly partition our messages. We also crank the batch/linger settings up in attempt to reduce processing overhead. I notice Sarama does not have a partitioner option to try to prefer partitions with room left in unsent batches. Is such a feature in the works? 

In fact, exactly what I'm after is written about here: https://www.confluent.io/blog/apache-kafka-producer-improvements-sticky-partitioner/

Thanks!

**Comment by corydolphin** [comment]
In the Java world, we've found the sticky partitioner to be incredibly effective for high throughput unkeyed messages. 
It does not look like, the current interface for `Partitioner` does not have access to the necessary access to the `Producer` and buffers to be able to implement this kind of logic.

Has anyone at Shopify seen a similar use case for unkeyed messages where you want to maximize throughput via large batches and minimal concurrent buffer filling?
