### ISSUE TITLE
Sarama batch consuming mode leads the 100% usage of CPU

### ISSUE THREAD

**Issue by xue610315921** [IBM/sarama#1972]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
|  v1.27.1 | v1.0 | 1.15 |

##### Configuration

``` 
saramaConfig.Version = sarama.V1_0_0_0
saramaConfig.Consumer.Return.Errors = true

saramaConfig.Net.SASL.Enable = true
saramaConfig.Net.SASL.User = xxxx
saramaConfig.Net.SASL.Password = xxxx
saramaConfig.Net.SASL.Mechanism = sarama.SASLTypeSCRAMSHA512

saramaClient, err := sarama.NewClient(brokers, saramaConfig)
saramaConsumer, err := sarama.NewConsumerGroupFromClient(group, saramaClient)
```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
no error log
```

</p>
</details>

##### Problem Description

Is this the correct way to implement the batch consuming? The code here:
```
func (c *Consumer) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) (err error) {
	rm = ratelimit.New(c.config.QpsLimitationPerPartition)
        msgArray := make([]*sarama.ConsumerMessage, 0, c.config.BatchNumber)
	for {
		select {
		case msg := <-claim.Messages():
			{
				if msg == nil {
					continue
				}

				rm.Take()
				msgArray = append(msgArray, msg)

				if len(msgArray) < c.config.BatchNumber {
					continue // not reach the batch number, continue to read from buffer
				}

				go c.executeBatchConsumeFunc(sess, msgArray) // pass last msg for batch commit
				msgArray = make([]*sarama.ConsumerMessage, 0, c.config.BatchNumber) // make new slice
			}
		default:
			{
				if len(msgArray) != 0 {
					// control goroutine num
					_, ok := <-c.channel
					if !ok { //channel maybe closed
						return
					}

					go c.executeBatchConsumeFunc(sess, msgArray) // pass last msg for batch commit
					msgArray = make([]*sarama.ConsumerMessage, 0, c.config.BatchNumber) // make new slice
				}
				// no new msg from channel, waiting for a period
				time.Sleep(time.Millisecond * time.Duration(c.config.BatchTimeInterval))
			}
		}
	}
}
```

Even I settled the rate limit to 50, the CPU usage of instance(docker) still would be 100%.
Here is the pprof, I don't know why so many chanrecv here, and the lock & unlock in it cost a lot of resources. 

![271624210345_ pic_hd](https://user-images.githubusercontent.com/19649503/122683244-8a91b480-d230-11eb-99d6-734d0d8ac310.jpg)

In my memory when I was debugging, seems that I received a lot of `nil` from the channel(clainm.Message()), will it lead this? because I just continue when receiving nil. But I can't reproduce it on debugging machine now.

Thanks a lot!

**Comment by fxrlv** [comment]
sometimes kafka decide to rebalance consumer group
doc says that in this case message channel will be closed
closed channel return nil

**Comment by bingoabs** [comment]
@fxrlv so we need to restart the consumer manually or not? Thanks.

**Comment by fxrlv** [comment]
if you get nil from the message channel, you should return from ConsumeClaim

then check returned error from Consume method you called before

nil error means you can recall Consume and get new claims

**Comment by dnwe** [comment]
i.e., https://github.com/IBM/sarama/blob/dedd86d84f2d56a7c3b604ea36da479c3d2a80bb/examples/consumergroup/main.go#L180-L204
