### ISSUE TITLE
Can sarama track some important indicators of Kafka?

### ISSUE THREAD

**Issue by staticLin** [IBM/sarama#1981]
##### Problem Description
I have a need to track some important indicators.
For example, the latest offset of the message or the offset of the message consumption, etc. And is there documentation for this part of the API?
Thank you so much for taking the time to answer my question!!

**Comment by LeandroFranciscato** [comment]
Hi there!
In my search for something like this, I've found this:

```go
func (c *ClientConsumer) GetLag(topic, consumerGroup string) (lagTotal int64, err error) {

	partitions, err := c.consumer.Partitions(topic)
	if err != nil {
		return 0, err
	}

	for partition := range partitions {

		manager, err := sarama.NewOffsetManagerFromClient(consumerGroup, c.client)
		if err != nil {
			return 0, err
		}

		partitionManager, err := manager.ManagePartition(topic, int32(partition))
		if err != nil {
			return 0, err
		}

		consumerGroupOffset, _ := partitionManager.NextOffset()

		topicOffset, err := c.client.GetOffset(topic, int32(partition), sarama.ReceiveTime)
		if err != nil {
			return 0, err
		}

		lagTotal += (topicOffset - consumerGroupOffset)
	}

	return lagTotal, nil

}
```

Still searching for different ways  to look at it.
Hope it helps you

**Comment by dnwe** [comment]
@staticLin are you still looking for further help in this area or did @LeandroFranciscato's answer solve this for you?
