### ISSUE TITLE
 When you manually ACK, different versions have different results

### ISSUE THREAD

**Issue by ruke318** [IBM/sarama#1993]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.29 |  |  1.16|

``` go
conf.Consumer.Offsets.AutoCommit.Enable = false

func (consumer *Consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {

	for message := range claim.Messages() {
                defer func () {
                        session.MarkMessage(message, "") // v1.27 just mark message
                        session.Commit() // But in v1.29, if I don't call commit (), the message will be consumed repeatedly
                }()
}


```

**Comment by crazytaxi824** [comment]
i guess defers in this infinite loop will never run

**Comment by dnwe** [comment]
As per the above, you're not actually marking messages and committing here because the defer won't run until the whole ConsumeClaim func returns
