### ISSUE TITLE
Goroutine leaks in zstd initialization

### ISSUE THREAD

**Issue by pkwarren** [IBM/sarama#2029]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.29.1 | n/a | 1.17.1 |

##### Configuration

What configuration values are you using for Sarama and Kafka?

n/a

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
 Goroutine 29 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
goroutine 29 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00020fa00)
        /Users/pkw/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
        /Users/pkw/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

 Goroutine 30 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
goroutine 30 [chan receive]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc00020fad0)
        /Users/pkw/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xec
created by github.com/klauspost/compress/zstd.newBlockDec
        /Users/pkw/go/pkg/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b1

```

</p>
</details>

##### Problem Description

The fix for https://github.com/Shopify/sarama/pull/1869 changed from initializing the zstd variables on demand (with sync.Once) to in init. Behind the scenes, this causes goroutines to be started (and calling `.Close()` on Sarama resources doesn't propagate through to calling `.Close()` on the zstd instances).

This causes tests that verify no leaked goroutines (i.e. using https://github.com/uber-go/goleak) to start to fail if they use Sarama.

**Comment by pkwarren** [comment]
With the default configuration, this causes a leak of runtime.NumCPU() goroutines.

**Comment by dnwe** [comment]
Yes, this was sort of a known problem flagged up under https://github.com/Shopify/sarama/issues/1937 and is something that we'd like to fix (by having the encoders/decoders owned on a per client basis).

However, the "leaked" goroutines aren't so much of a problem by themselves, they're not increasing in number and they are only created once at package initialization. We use github.com/fortytw2/leaktest ourselves and its per-test snapshot-based approach isn't concerned by them.
