### ISSUE TITLE
Broken pipe error when Admin API `DescribeCluster` is called during a Kafka brokers rolling

### ISSUE THREAD

**Issue by ppatierno** [IBM/sarama#2042]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|v1.29.0 |2.7.0|1.16.3|

##### Problem Description

In the Strimzi project we have a canary tool used to produce/receive messages to a Kafka instances to check it's working fine. The tool does it periodically and also uses the Admin API `DescribeCluster` function for getting some cluster info for its own purpose.
While everything works fine, if we do a rolling of the Kafka brokers in the cluster, so shutting down and restarting a broker one by one, sometimes it happens that the `DescribeCluster` operation returns with following error:

```shell
write tcp 10.130.44.71:58660->10.131.41.90:9093: write: broken pipe
```
At some point the tool seems to be able to recover and then failing again.
The only way to fix the issue is to restart the canary.

**Comment by ppatierno** [comment]
After some re-search, I discovered that this always happens in any case when Kafka brokers close connection to the admin client (so after an EOF). We are even using the `connections.max.reauth.ms` set a 5 mins, so this problem happens every 5 minutes because admin client is not able to re-connect and re-authenticate.
This issue seems to be related to https://github.com/Shopify/sarama/issues/1162 which sounds to be closed but not really fixed.
@dnwe any idea?

**Comment by dnwe** [comment]
Yes it looks like both #1796 and this are similar with the admin client not discarding cached connections that have been closed remotely

**Comment by ppatierno** [comment]
Yeah that's another one with same problem :-(

**Comment by dnwe** [comment]
Is this fixed now with https://github.com/IBM/sarama/pull/2197 and https://github.com/IBM/sarama/pull/2234 both merged?
