### ISSUE TITLE
Notify on consumer group re-balance

### ISSUE THREAD

**Issue by alexec** [IBM/sarama#2044]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.29.1 | N/A  | 1.16  |

##### Problem Description

I keen an in-memory data structure which follows data on partitions. I offload this data to Redis periodically. When the consumer group rebalances, the in-memory structure will become invalid. So I need to know when the re-balance occurs.

It is not clear to me as how I can be notified.

**Comment by dnwe** [comment]
You should find that [Setup](https://github.com/IBM/sarama/blob/503ade351d8a23044cf6bc7cd1a509344fb8ad1b/consumer_group.go#L1066) is called on rebalance/assignment
