### ISSUE TITLE
`HighWaterMarkOffset()` behaves differently for `mocks.Consumer`

### ISSUE THREAD

**Issue by jamslinger** [IBM/sarama#2050]
> Huh, ok. Unfortunately, consuming a message is the only way I know of to fetch the HighWatermark. If you find another, I'm happy to include it.
>
>_Originally posted by @eapache in https://github.com/Shopify/sarama/issues/1134#issuecomment-406704004_

I encountered the same issue where `HighWaterMarkOffset()` returns `0` if no messages have been consumed yet. I understand that there is no way to know the `HighWaterMarkOffset` before the first message has been consumed. However, my problem was that I had tests in place that did not cover that case because `mocks.Consumer` always returns the "true" `HighWaterMarkOffset`. 

I'd expect `mocks.Consumer` to also return `0` if no message has been consumed yet. What do you think about that? Otherwise it might be helpful to have that case documented in `HighWaterMarkOffset()`.

**Comment by dnwe** [comment]
I believe the two are in sync since https://github.com/IBM/sarama/pull/2082 but please reopen if that’s not correct
