### ISSUE TITLE
【sarama not suppot KIP-98 - Exactly Once Delivery and Transactional Messaging】

### ISSUE THREAD

**Issue by td-middleware** [IBM/sarama#2059]
##### Versions
Sarama is not supported Transaction ， and can not cosumer 【Consumer.IsolationLevel = sarama.ReadCommitted】 after Commit success according to【KIP-98】。

**Comment by dnwe** [comment]
This should be supported, see https://github.com/IBM/sarama/blob/86816212a7aca81d7d64c5603bb1aeb7f8248a7a/examples/exactly_once/main.go for an example

please open an issue if you see problems with this
