### ISSUE TITLE
Not supported KIP-368: Allow SASL Connections to Periodically Re-Authenticate

### ISSUE THREAD

**Issue by ppatierno** [IBM/sarama#2060]
Hi,
it seems that Sarama doesn't support [KIP-368](https://cwiki.apache.org/confluence/display/KAFKA/KIP-368%3A+Allow+SASL+Connections+to+Periodically+Re-Authenticate) which is about re-authenticating when on the broker the `connections.max.reauth.ms` is set as timeout.
Right now Sarama is able to handle the disconnection and reconnecting, even if it works for producer and consumer but not for the admin client as reported by https://github.com/Shopify/sarama/issues/2042.
Is there any plan/roadmap to add this feature to future Sarama version?

**Comment by dnwe** [comment]
@ppatierno this should not be available on main thanks to @k-wall and will be in the next upcoming release version of Sarama

**Comment by ppatierno** [comment]
@dnwe @k-wall thanks! that's great!

**Comment by bodypumper** [comment]
> 

thanks

**Comment by yhl25** [comment]
Hi, any update on this issue? is there a workaround?
