### ISSUE TITLE
Does any method support message produce connection pool?

### ISSUE THREAD

**Issue by wgqzlj** [IBM/sarama#2065]
Does sarama have connection pooling mechanism, we found that in case of high concurrency of production messages (ex:QPS> 10K), a lot of resources will be wasted on tcp links.

**Comment by yupeng2015** [comment]
> Does sarama have connection pooling mechanism, we found that in case of high concurrency of production messages (ex:QPS> 10K), a lot of resources will be wasted on tcp links.

你的问题解决了么，我这边打算用sarama，想确认下是否支持连接池

**Comment by dnwe** [comment]
@wgqzlj tcp connections should be mostly static and don’t drop and re-establish during the client’s lifetime, can you elaborate on what issue you’re seeing?
