### ISSUE TITLE
use UpsertUserScramCredentials method  err panic: kafka server: The version of API is not supported.

### ISSUE THREAD

**Issue by yangjy20169717** [IBM/sarama#2066]
Hello author：
        I got an error when using the method to set the user and password. Is there a version restriction for this method? The version of Kafka I currently use is 2.3.0. Below is a part of the log  
```go
[Sarama] 2021/11/11 23:35:59 Cannot encode an unknown resource pattern type, using Literal instead
[Sarama] 2021/11/11 23:35:59 Cannot encode an unknown resource pattern type, using Literal instead
panic: kafka server: The version of API is not supported.

goroutine 1 [running]:
main.main()
        /Users/yangjiyuan/go/src/product/kafka-manager/main.go:80 +0x905

```

**Comment by dnwe** [comment]
Correct yes, this api requires at least Kafka 2.7.0 at the backend. We should enforce that required version check in admin.go so it is rejected locally
