### ISSUE TITLE
Bug: cluster admin refresh medatadata report error when set `Metadata.Full` to false.

### ISSUE THREAD

**Issue by 3AceShowHand** [IBM/sarama#2069]
##### Versions

When there is no topic in the Kafka cluster, metadata cannot be reported, if we set `Metadata.Full` to false.

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.12.7 |3.0.0  |1.17.2  |

##### Configuration

```
Config.Metadata.Full = false
```

What configuration values are you using for Sarama and Kafka?
``` go
```

![Screen Shot 2021-11-19 at 11 20 33 PM](https://user-images.githubusercontent.com/7138436/142647376-a83e12a4-afe1-4eef-b9c4-d880dcd41b55.png)

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

**Comment by nkostoulas** [comment]
The docs do state:

> ErrNoTopicsToUpdateMetadata is returned when Meta.Full is set to false but no specific topics were found to update the metadata.

I too don't get the intuition of this though.
