### ISSUE TITLE
Seed Broker Connection Leak

### ISSUE THREAD

**Issue by kadaan** [IBM/sarama#2074]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|-----|
|  1.29.1  |   N/A   | N/A |

##### Configuration

N/A

##### Logs

N/A

##### Problem Description

The [Client.RefreshBrokers](https://github.com/Shopify/sarama/blob/556ddf712c31a475ec4e08b3550156c35a62ede1/client.go#L450) function can cause connection leaks when the seedBrokers are not a subset of the brokers.  [Here](https://github.com/Shopify/sarama/blob/556ddf712c31a475ec4e08b3550156c35a62ede1/client.go#L463) the seed brokers are nilled out, but never closed.  This causes a leak of connections which eventually will cause an OOM.  In the [Client.Close](https://github.com/Shopify/sarama/blob/556ddf712c31a475ec4e08b3550156c35a62ede1/client.go#L236) function the seedBrokers are [explicitly closed](https://github.com/Shopify/sarama/blob/556ddf712c31a475ec4e08b3550156c35a62ede1/client.go#L256).  Similar behavior in Client.RefreshBrokers resolved the connection leak.

https://github.com/kadaan/sarama/commit/d0c162ca6c1f9ece88036494ea0eb2d9e07dcd20

**Comment by hindessm** [comment]
This was fixed by 132afa552e
