### ISSUE TITLE
message size incorrectly calculated (smaller than actual size)

### ISSUE THREAD

**Issue by Frefreak** [IBM/sarama#2085]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 635bcf3  |  2.12-2.0.0 | 1.17 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	c := sarama.NewConfig()
	c.Producer.Return.Successes = true
	c.Producer.Return.Errors = true
	// Wait only the local commit to succeed before responding.
	c.Producer.RequiredAcks = sarama.WaitForLocal
	// Because sarama does not accept a Context for every message, set the Timeout here.
	c.Metadata.Full = true
	c.Metadata.Retry.Max = 3
	c.Metadata.Retry.Backoff = time.Millisecond * 250
	c.Producer.MaxMessageBytes = 1000000
```
kafka: default config (local instance started with `bin/kafka-server-start.sh config/server.properties`)

##### Problem Description

It seems sarama under-calculate the message size at least in the version given above. For a simple message with value size of 999964, sarama calculate the total message size as 1000000 (the default maximum) and will try to send it, but from a packet capture the actual size is 1000082 and thus will be rejected.
![image](https://user-images.githubusercontent.com/7122156/144981713-00031fd0-f3bd-482f-9717-0c1be59354c9.png)
![image](https://user-images.githubusercontent.com/7122156/144981767-8a448aab-4dff-4fa8-9bbc-6608b59462a1.png)
  

test program:

```go
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/Shopify/sarama"
)

func main() {
	c := sarama.NewConfig()
	c.Producer.Return.Successes = true
	c.Producer.Return.Errors = true
	// Wait only the local commit to succeed before responding.
	c.Producer.RequiredAcks = sarama.WaitForLocal
	// Because sarama does not accept a Context for every message, set the Timeout here.
	c.Metadata.Full = true
	c.Metadata.Retry.Max = 3
	c.Metadata.Retry.Backoff = time.Millisecond * 250
	c.Producer.MaxMessageBytes = 1000000

	producer, err := sarama.NewSyncProducer([]string{"localhost:9092"}, c)
	if err != nil {
		fmt.Println("error in NewSyncProducer: ", err)
		os.Exit(1)
	}
	sz, err := strconv.Atoi(os.Args[1])
	if err != nil {
		fmt.Println("invalid size:", err)
		os.Exit(1)
	}
	bytes := []byte(strings.Repeat("x", sz))
	message := sarama.ProducerMessage {
		Topic: "test",
		Value: sarama.ByteEncoder(bytes),
	}
	err = producer.SendMessages([]*sarama.ProducerMessage{&message})
	if err != nil {
		value := err.(sarama.ProducerErrors)
		fmt.Println("error in SendMessages", value[0].Err.Error())
	}
}
```

**Comment by Frefreak** [comment]
But even with value of size 999964 it fails, because the actually size is 1000082. (please see my second pics above)

**Comment by dnwe** [comment]
We should ensure we are synced up with the similar record size estimation code from the Java client [org/apache/kafka/common/record/AbstractRecords.java#L89-L157](https://github.com/apache/kafka/blob/da65af02e5856e3429259e26eb49986122e34747/clients/src/main/java/org/apache/kafka/common/record/AbstractRecords.java#L89-L157)

**Comment by Frefreak** [comment]
From a quick look of both the java and sarama implementation, for version >= 2 it looks like in the java side it will use  `DefaultRecordBatch.RECORD_BATCH_OVERHEAD` as the `RecordBatch` overhead, which is 61 bytes and is in sync with this document: https://kafka.apache.org/documentation/#recordbatch (all the fields size before the records field + the 4 byte length field of the array itself). Sarama is using `maximumRecordOverhead` which is 36 bytes though.

Besides the java side is using `sizeOfVarint` and friends to get the actually size of the varint, whereas sarama is using max size of the corresponding int type.

If we are just providing an estimated size check I think it would be acceptable for current implementation, otherwise maybe we can make it really the same as the java code which seems is the accurate size.
