### ISSUE TITLE
 AWS MSK Kafka migration -- error connecting to kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?

### ISSUE THREAD

**Issue by johnson101119** [IBM/sarama#2087]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
"github.com/Shopify/sarama" --> I am not sure with the version below version copied from config
config.Version = sarama.V0_10_0_0 | kafka_2.12-2.2.1

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` config := sarama.NewConfig()
		config.Producer.RequiredAcks = sarama.WaitForAll
		config.Producer.Retry.Max = 1
		config.Producer.Return.Successes = true
		config.Version = sarama.V0_10_0_0
		//	config.Producer.Compression = sarama.CompressionSnappy
		Producer, Error = sarama.NewSyncProducer(configStore.ConfigStruct.GetTomlInstance().Kafka.KafkaBrokerList, config)
```

AWS broker endpoint TLS
kafkaBrokerList = ["b-2.test-kafka-dev.kafka.us-west-2.amazonaws.com:9094","b-1.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094","b-3.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094"]
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

2021/12/09 14:17:16 kafka.go:74: Attempting to connect to Kafka
2021/12/09 14:17:16 kafka.go:85: error connecting to kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

##### Problem Description
On trying to attempt Kafka connect --> AWS MSK from ECS docker image noticed following error below.
 
Error
2021/12/06 16:58:04 kafka.go:85: error connecting to kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

Kafka topic is successfully created
 bin/kafka-topics.sh --describe --topic session_info --zookeeper z-3.test-kafka-dev.6sn6tf.c4.kafka.us-west-2.amazonaws.com:2181.....
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Topic:wisp_session_info PartitionCount:3        ReplicationFactor:3     Configs:
        Topic: session_info        Partition: 0    Leader: 1       Replicas: 1,3,2 Isr: 1,3,2
        Topic: session_info        Partition: 1    Leader: 3       Replicas: 3,2,1 Isr: 3,2,1
        Topic: session_info        Partition: 2    Leader: 2       Replicas: 2,1,3 Isr: 2,1,3

The broker endpoint configured is
kafkaBrokerList = ["b-2.test-kafka-dev.kafka.us-west-2.amazonaws.com:9094","b-1.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094","b-3.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094"]
 
------

To validate the broker endpoint, 
I tested with sample docker image and able to connect to AWS broker endpoint and publish the event from the container.

Note: At on premise kafka broker connection string is configured with IP Address and works fine, Where as in AWS it is b-2.test-kafka-dev.kafka.us-west-2.amazonaws.com:9094","b-1.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094","b-3.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094 and throws an error as above.

Any help will be appreciated.

Thanks & Regards
Johnson

**Comment by johnson101119** [comment]
will update the log file asap.
Meanwhile replaced aws broker endpoint to broker VPC ipaddress but still same error.

From
kafkaBrokerList = ["b-2.test-kafka-dev.kafka.us-west-2.amazonaws.com:9094","b-1.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094","b-3.test-kafka-dev.c4.kafka.us-west-2.amazonaws.com:9094"]
To
kafkaBrokerList = ["10.0.1.1:9094", "10.0.12.1:9094","10.0.15.1:9094] //The IP address are the sample ones where as port is common

Error
2021/12/09 14:17:16 kafka.go:74: Attempting to connect to Kafka
2021/12/09 14:17:16 kafka.go:85: error connecting to kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by johnson101119** [comment]
Here is the output of Sarama log, I created the new Cluster without TLS and to have only plain text.

021/12/18 03:06:01 Attempting to connect to Kafka
2021/12/18 03:06:01 Kafka broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092

sarama] 2021/12/18 03:06:01 Initializing new client
[sarama] 2021/12/18 03:06:01 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2021/12/18 03:06:01 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2021/12/18 03:06:01 client/metadata fetching metadata for all topics from broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092
[sarama] 2021/12/18 03:06:01 Failed to connect to broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: dial tcp: address b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: too many colons in address

[sarama] 2021/12/18 03:06:01 client/metadata got error from broker -1 while fetching metadata: dial tcp: address b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: too many colons in address
[sarama] 2021/12/18 03:06:01 client/metadata no available broker to send metadata request to
[sarama] 2021/12/18 03:06:01 client/brokers resurrecting 1 dead seed brokers
[sarama] 2021/12/18 03:06:01 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2021/12/18 03:06:02 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2021/12/18 03:06:02 client/metadata fetching metadata for all topics from broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092
[sarama] 2021/12/18 03:06:02 Failed to connect to broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: dial tcp: address b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: too many colons in address
[sarama] 2021/12/18 03:06:02 client/metadata got error from broker -1 while fetching metadata: dial tcp: address b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092: too many colons in address
[sarama] 2021/12/18 03:06:02 client/metadata no available broker to send metadata request to
[sarama] 2021/12/18 03:06:02 client/brokers resurrecting 1 dead seed brokers
[sarama] 2021/12/18 03:06:02 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama] 2021/12/18 03:06:02 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2021/12/18 03:06:02 client/metadata fetching metadata for all topics from broker b-2.notls-kafka.us-west-2.amazonaws.com:9092,b-3.notls-kafka.us-west-2.amazonaws.com:9092,b-1.notls-kafka.us-west-2.amazonaws.com:9092

.....
....
sarama] 2021/12/18 03:06:02 client/metadata no available broker to send metadata request to
[sarama] 2021/12/18 03:06:02 client/brokers resurrecting 1 dead seed brokers
[sarama] 2021/12/18 03:06:02 Closing Client

---
with IP address too got same result
[sarama] 2021/12/18 03:19:21 Failed to connect to broker 10.6.1.1:9092,10.6.4.3:9092,10.6.4.10:9092: dial tcp: address 10.6.1.1:9092,10.6.4.3:9092,10.6.4.10:9092: too many colons in address

---
With only one IP  , it is timeout error

Trying few more options

**Comment by dnwe** [comment]
In this most recent log it looks like you’ve put the comma separated three broker addresses in the config as a single string rather than as a slice of strings as the Dial is setting all three and refusing to permit more than one colon (:)

**Comment by johnson101119** [comment]
I could able to resolve the connectivity issue after slice of a strings for Plaintext AWS MSK Kafka Connectivity. 

However for TLS based Kafka connectivity for GoLang with Sarama package did not find the relevant documentation,
I referred following link below for the steps but not  success on creating the server-cer.pem, client-cer.pem and client-key.pem using keytool.
https://www.process-one.net/blog/using-tls-authentication-for-your-go-kafka-client/

**Comment by binbinshi** [comment]
see the same error 
`kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`
i add sarama config version ， the error disappeared
`config := sarama.NewConfig()
 config.Version = sarama.V0_11_0_0`

**Comment by dnwe** [comment]
From the linked issue it looks like TLS connectivity to AWS MSK was fixed by including the full chain in the client cert pem for tls client authentication

> Sorted out by appending the Intermediate CA file to the client_cert .

**Comment by Deeptanshu-sankhwar** [comment]
> see the same error `kafka: client has run out of available brokers to talk to (Is your cluster reachable?)` i add sarama config version ， the error disappeared `config := sarama.NewConfig() config.Version = sarama.V0_11_0_0`

this worked for me! not entirely sure, why
