### ISSUE TITLE
Management of goroutines count for message consuming

### ISSUE THREAD

**Issue by coderGitGit** [IBM/sarama#2089]
Could you please tell me if there is a tool for managing of goroutines count for message consuming?
As I understand it, a separate goroutine is created for each topic section within the consumer group by default?

**Comment by dnwe** [comment]
Correct, we don’t have any configuration options for capping the number of goroutines or pooling them, but there typically shouldn’t be a need to. Are you hitting some resource limits due to a large number of partitions or something similar?
