### ISSUE TITLE
Kafka 2.8.1 error messages are not Nullable strings anymore ?

### ISSUE THREAD

**Issue by agriffaut** [IBM/sarama#2095]
##### Versions
Working
| Sarama | Kafka | Go |
|--------|-------|----|
| 1.30.1 | 2.7.0 | 1.16 |

Fail
| Sarama | Kafka | Go |
|--------|-------|----|
| 1.30.1 | 2.8.1 | 1.16 |

##### Logs
<details><summary>logs: CLICK ME</summary>
<p>
Error detected while describing quotas
</p>
</details>

##### Problem Description
For some reason, Kafka 2.8.1 doesn't return a nullable string anymore for DescribeClientQuotasResponse.ErrorMsg on that [API (key: 48)](https://kafka.apache.org/protocol#The_Messages_DescribeClientQuotas).
When no error occurs, a pointer to an empty string is returned.
In the packetDecoder, the getNullableString function reads a 0 in Kafka 2.8.1 rather than -1 in Kafka 2.7.0.

I'll submit a PR to handle this one, **but maybe other APIs are impacted too**

**Comment by dnwe** [comment]
Fixed by https://github.com/IBM/sarama/pull/2096
