### ISSUE TITLE
Go take a lot of heap on CompressionSnappy

### ISSUE THREAD

**Issue by marsccm** [IBM/sarama#2104]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.29.1  | 1.1.1 | 1.16.5 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	sarama.Logger = LogReWriter{}
	cfg := sarama.NewConfig()
	cfg.ClientID = groupID
	cfg.Version = sarama.V1_1_1_0
	cfg.Consumer.Offsets.AutoCommit.Enable = true
	cfg.Consumer.Offsets.AutoCommit.Interval = 3 * time.Second
	cfg.Consumer.Offsets.Initial = sarama.OffsetNewest
	cfg.Consumer.Fetch.Default = 524288
	cfg.Consumer.Fetch.Max = 1048576
	cfg.Consumer.MaxWaitTime = 1000 * time.Millisecond
	sarama.MaxResponseSize = 1049825
	cfg.Metadata.Full = false
	cfg.Metadata.Retry.Max = 1
	cfg.Metadata.Retry.Backoff = 1000 * time.Millisecond
	cfg.Consumer.Return.Errors = true
	cfg.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRange
	cfg.Consumer.Group.Session.Timeout = 30 * time.Second
	cfg.Consumer.Group.Rebalance.Timeout = 60 * time.Second

	cfg.Producer.Compression = sarama.CompressionSnappy
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

![image](https://user-images.githubusercontent.com/15801794/148876725-0ef1e7e0-9cc1-47c2-8b38-80577a82b410.png)

**Comment by dnwe** [comment]
We use [eapache/go-xerial-snappy](eapache/go-xerial-snappy) which is just a lightweight framing wrapper around [golang/snappy](/golang/snappy). I don't think the latter provides any tuning parameters around its internal buffer usage.

We _might_ be able to do more if we adopt [s2](https://github.com/klauspost/compress/tree/master/s2) via @klauspost 's [compress](/klauspost/compress) library (which we already use for zstd) to provide our snappy support

**Comment by klauspost** [comment]
Yes, it is a fairly easy wrapper to do, however to make a bigger dent you would need to refactor the interface to be an `io.Reader` wrapper, otherwise you need to have the compressed and decompressed sizes in memory at the same time.

**Comment by klauspost** [comment]
I added a [xerial-snappy fork](https://github.com/klauspost/compress/tree/master/snappy/xerial#fork), which eliminates allocations if the destination buffer is big enough to contain the decoded content.

There is also [DecodeCapped](https://github.com/klauspost/compress/blob/master/snappy/xerial/xerial.go#L209), which allows to completely control the maximum output size. This prevents "zip bombs". 

Even though Snappy is limited to ~21:1 expansion, the xerial streaming can potentially fill up memory if the input isn't limited.

**Comment by burungbangkai** [comment]
is this solved? i got the same issue as described here.
