### ISSUE TITLE
[Question]how can i recover from panic while using consume group

### ISSUE THREAD

**Issue by Rorke76753** [IBM/sarama#2105]
I wrote my recovery code like this
``` go
func (b MyWrapConsumer) Consume(ctx context.Context, handler *WrapHandler) {
//WrapHandler which implements ConsumerGroupHandler
	defer func() {
		if err := recover(); err != nil {
			//do some log
		}
                 b.Consume(ctx,handler)
	}()
	for {
		err := b.consumerGroup.Consume(ctx, b.topics, handler)
		if err != nil {
			//do some log
		}
	}
}
```
I figured out that the recover does not work,
should i put the recovery code into `WrapHandler.ConsumeClaim`?

**Comment by dnwe** [comment]
hmm, `consumerGroup.Consume` itself shouldn't be panic'ing, it only calls internal Sarama code — do you have an example of a panic you've seen?

If the panic is in your own code then yes it would need to be in your implementation of the `ConsumerGroupHandler` interface

**Comment by dnwe** [comment]
Closing as presumed to have bee solved. Please reopen if not
