### ISSUE TITLE
retries and timeout when managing ACLs with the ClusterAdmin

### ISSUE THREAD

**Issue by nkostoulas** [IBM/sarama#2112]
👋  We're trying to use the ACL methods of the `ClusterAdmin` and noticed there's no option for retries or timeouts even though these are specified in the `Admin` part of the `Config` and are used with Topics related methods. Is there a reason behind this? Can it be assumed that these are less likely to flake or drag on or should we be managing this on our end?

**Comment by dnwe** [comment]
No they're equally likely to hit a condition of `ErrNoController` so you're correct that they should really be wrappered in a similar `ca.retryOnError(isErrNoController, ...) { ... }` call

**Comment by dnwe** [comment]
@hindessm similar to https://github.com/IBM/sarama/pull/2520

**Comment by hindessm** [comment]
Is it similar though? Looking at [KIP-140](https://cwiki.apache.org/confluence/display/KAFKA/KIP-140%3A+Add+administrative+RPCs+for+adding%2C+deleting%2C+and+listing+ACLs), it says:

> CreateAclsRequest contains a list of ACLs to add.  It can be sent to any broker.

and:

> Just like CreateAclsRequest, DeleteAclsRequest can be sent to any broker.

I didn't spot an explicit statement regarding the Describe request but I don't imagine that would be more strict.
