### ISSUE TITLE
Paused Consumer still sends FetchRequest (with empty blocks)

### ISSUE THREAD

**Issue by dnwe** [IBM/sarama#2125]
Whilst trying out the new "pause consumer" support (https://github.com/Shopify/sarama/pull/2005) on main, I noticed that Sarama will submit empty FetchRequests if all of the assigned partitions are paused. This is because we only use Pause to skip adding the topicPartition blocks to the FetchRequest and still go ahead and send the Fetch even if it is essentially empty:

https://github.com/Shopify/sarama/blob/f214fdd60afa75e28e1d40308b64029033fc6f9d/consumer.go#L1071-L1077

Ideally we should work the same way as the Java client and not send any FetchRequest if there are no active assigned partitions to consume from

@raulnegreiros might you be able to take a look into what it would take to achieve this?

**Comment by raulnegreiros** [comment]
Sure, I'll try to check it at the weekend.

**Comment by raulnegreiros** [comment]
hi @dnwe , I've submitted a proposal, please check if this is a valid way. But I fear that skipping the `handleResponses` can have some collateral effect, I'm not so sure about it. I think you can give some guidance if this is the best way to follow.

**Comment by pkoutsovasilis** [comment]
ok @dnwe I see that you merged this one, but there is corner case which I am not sure that it is covered by this issue. 

So when all topics and the respective partitions are paused then this PR addresses that case and does not send a request, so far so good. But if you have a ConsumerGroup that consumes from two or more topics, and all the partitions of just one topic are paused, the same error resurfaces. My proposed fix to cover that case as well fix would be the following

```
                for child := range bc.subscriptions {
+                       if _, ok := response.Blocks[child.topic]; !ok {
+                               bc.acks.Done()
+                               continue
+                       }
+
+                       if _, ok := response.Blocks[child.topic][child.partition]; !ok {
+                               bc.acks.Done()
+                               continue
+                       }
+
                        child.feeder <- response
                }
                bc.acks.Wait()
```

would you like me to do a separate issue and maybe a PR about that case?

**Comment by dnwe** [comment]
@pkoutsovasilis yes that sounds interesting, please do raise an issue. 

Hearing from users who are consuming from multiple topics (potentially of differing partition numbers) from the same consumer group is always interesting as this isn’t as common a scenario and it usually teases out new and unforeseen behaviour

**Comment by dnwe** [comment]
The CPU load issue should have been fixed by https://github.com/IBM/sarama/pull/2532 in [v1.41.0](https://github.com/IBM/sarama/releases/tag/v1.41.0) and newer
