### ISSUE TITLE
consumer group can not consume

### ISSUE THREAD

**Issue by go-slark** [IBM/sarama#2132]
When producer did not produce msg to kafka for long time,after long time producer produces msg again, but consumer group does not consume msg, if not restart consumer. Why ?

**Comment by smallfish-root** [comment]
This is my consumer group code like this:
consumer group config:
	config.Consumer.Offsets.Initial = sarama.OffsetOldest
	config.Consumer.Offsets.AutoCommit.Enable = false
	config.Consumer.Return.Errors = true

func (kc *KafkaConsumerGroup) Consume() {
	for {
		err := kc.ConsumerGroup.Consume(context.TODO(), kc.Topics, kc.ConsumerGroupHandler)
		if err != nil {
			fmt.Printf("consumer group consume fail, err:%+v\n", err)
			break
		}
	}
}

func (*Kafka) Setup(_ sarama.ConsumerGroupSession) error   { return nil }
func (*Kafka) Cleanup(_ sarama.ConsumerGroupSession) error { return nil }
func (k *Kafka) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for msg := range claim.Messages() {
                sess.MarkMessage(msg, "")
		sess.Commit()
}

**Comment by dnwe** [comment]
@longit644 the consumer should attempt to re-join the group automatically if it is evicted


@go-slark did you ever resolve your problem? Is this still an issue for you?
