### ISSUE TITLE
ErrMessageSizeTooLarge indicates a kafka server response when the error is in the Producer

### ISSUE THREAD

**Issue by shermanCRL** [IBM/sarama#2137]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.29.0 |  any | 1.17  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
defaults
```

##### Logs

Logs aren’t especially important here (not a bug), except to say that the relevant error is `kafka server: Message was too large, server rejected it to avoid allocation error.`  

##### Problem Description

When the message size [exceeds](https://github.com/Shopify/sarama/blob/54a84a712aa0640cc71b27d6ad1d68a293e64e62/async_producer.go#L369-L372) `Producer.MaxMessageBytes`, the [error message](https://github.com/Shopify/sarama/blob/a37f45dcee6b1e95240c17a4c60c4a960d50eaeb/errors.go#L248-L249) indicates that the error is coming from the Kafka server, when in fact it’s a Producer error.

In our application, we recently spent a fair amount of time working with a customer, chasing down this issue -- we unproductively focused on the server while the error was in our software. https://github.com/cockroachdb/cockroach/issues/76258. The downstream server had a very large max message size (hundreds of MB), but the errors persisted, and it took a while to recognize that `Producer.MaxMessageBytes` (defaulted to 1MB) was the culprit.

We’d like to see a more accurate and descriptive error message.

Thanks for the consideration, I can mock up a PR to illustrate a preferred solution if it would be helpful.

**Comment by dnwe** [comment]
Fixed by https://github.com/IBM/sarama/pull/2628
