### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by subbu05** [IBM/sarama#2141]
##### Versions
sarama@v1.29.2-0.20210920231520-94c8136ff710

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|v1.29  |2.4.1  |go1.17.6  |

##### Configuration
```
kafka.KafkaOptions{
		Enabled:             false,
		Name:                name,
		Topic:               "test",
		Brokers:             []string{},
		BufferMemory:        2147483648,
		LingerInterval:      time.Millisecond * 10,
		BatchSize:           65536,
		CompressionType:     "none",
		ProducerLatencyTime: time.Millisecond * 60,
		SaslEnabled:         false,
		SaslMechanism:       "SASLTypePlaintext",
		SslEnabled:          false,
		SslCertificate:      "",
		SslCertificateKey:   "",
		SslCaCertificate:    "",
		MaxMessageBytes:     10485760,
		Version:             sarama.MaxVersion,
		SslSkipVerify:       false,
		MsgTimeoutWarn:      time.Millisecond * 10000,
		KeySerializer:       "org.apache.kafka.common.serialization.ByteArraySerializer",
		ValueSerializer:     "org.apache.kafka.common.serialization.ByteArraySerializer",
		Acks:                "local",
		Retry:               5,
		Workers:             1,
		SendBufferBytes:     10485760,
		ReceiveBufferBytes:  10485760,
		MaxRequestSize:      10485760,
```

panic: send on closed channel

goroutine 74 [running]:
github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc0003080e0)
        /Users/a/go/pkg/mod/github.com/!shopify/sarama@v1.29.2-0.20210920231520-94c8136ff710/async_producer.go:1057 +0xa8
github.com/Shopify/sarama.withRecover(0x0)
        /Users/a/go/pkg/mod/github.com/!shopify/sarama@v1.29.2-0.20210920231520-94c8136ff710/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
        /Users/a/go/pkg/mod/github.com/!shopify/sarama@v1.29.2-0.20210920231520-94c8136ff710/async_producer.go:322 +0x9d
exit status 2

##### Problem Description
When trying to shutdown Kafka producer using producer.Close() we are seeing this issue.

**Comment by dnwe** [comment]
Closing as duplicate of #1441 — feel free to re-open if that's not the case
