### ISSUE TITLE
brokerProducer is nil, panic

### ISSUE THREAD

**Issue by simon28082** [IBM/sarama#2184]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.32.0 |  2.8.7 | 1.18 |

##### Problem Description

This is not an inevitable situation, but it happens many times
This is a crash triggered by `brokerProducer=nil`
Test scenario:
A message is sent every second, and the network connection is interrupted during the sending process. During the process, the producer will asynchronously close the producer, and Panic will occur in some cases in about 3-5 minutes
In `github.com/Shopify/sarama/async_producer.go` 560 lines
```go
if msg.retries > pp.highWatermark {
	// a new, higher, retry level; handle it and then back off
	pp.newHighWatermark(msg.retries)
	pp.backoff(msg.retries)
}

func (pp *partitionProducer) newHighWatermark(hwm int) {
	Logger.Printf("producer/leader/%s/%d state change to [retrying-%d]\n", pp.topic, pp.partition, hwm)
	pp.highWatermark = hwm

	
	pp.retryState[pp.highWatermark].expectChaser = true
	pp.parent.inFlight.Add(1)
//  Note: This is going to cause panic, because brokerProducer=nil
	pp.brokerProducer.input <- &ProducerMessage{Topic: pp.topic, Partition: pp.partition, flags: fin, retries: pp.highWatermark - 1}


	Logger.Printf("producer/leader/%s/%d abandoning broker %d\n", pp.topic, pp.partition, pp.leader.ID())
	pp.parent.unrefBrokerProducer(pp.leader, pp.brokerProducer)
	pp.brokerProducer = nil
}
```
I also took a quick look at the Dispatch method, but couldn't figure out the specific reason
This problem, only in 1.32.0, I have tested other versions without this problem

**Comment by niamster** [comment]
Hi @crcms Can you please test this with https://github.com/Shopify/sarama/pull/2182 ? Thank you!

**Comment by slaunay** [comment]
Line 560 for `1.32.0` does not seem to dereference a `brokerProducer`:
https://github.com/Shopify/sarama/blob/9baf7a651a68631e143039fafd7a7bb13ebdceca/async_producer.go#L560

Would you be able to post the panic trace, confirm the version and ideally provide some Sarama logs?

Also what do you mean by `During the process, the producer will asynchronously close the producer`?

**Comment by crcms** [comment]
@slaunay I am just disconnecting the network during the running process.

**Comment by slaunay** [comment]
@crcms if you can share the panic trace that would go a long way.

**Comment by crcms** [comment]
@slaunay This is a stack of panic.
```text
goroutine 58 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc000218600, 0x1)
        vendor/github.com/Shopify/sarama/async_producer.go:618 +0x19d
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc000218600)
        vendor/github.com/Shopify/sarama/async_producer.go:562 +0x4f7
github.com/Shopify/sarama.withRecover(0x0)
        vendor/github.com/Shopify/sarama/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        vendor/github.com/Shopify/sarama/async_producer.go:513 +0x1fb
```
This is a must-have BUG, as long as you interrupt the network in the running process, this problem will occur about 3-5 minutes, and the number of retries set by Producer is the default.

**Comment by slaunay** [comment]
Thanks @crcms, the stack points us to line `618` for the `nil` derefencing vs line `560`:
https://github.com/Shopify/sarama/blob/9baf7a651a68631e143039fafd7a7bb13ebdceca/async_producer.go#L615-L619

One scenario that would lead to the `brokerProducer` being `nil` prior to calling `newHighWatermark` would be if  the following `case <-pp.brokerProducer.abandoned` matches:
https://github.com/Shopify/sarama/blob/9baf7a651a68631e143039fafd7a7bb13ebdceca/async_producer.go#L547-L558

We need a unit test case to reproduce the issue in order to implement the proper fix.
Such test case can be used as well to confirm whether it still happens with #2182.

**Comment by crcms** [comment]
@slaunay thank you very much, but the issue #2182 I used it, and it's still problematic

**Comment by NewbieOrange** [comment]
We are having the same issue, any updates on this?

**Comment by yusronhanan** [comment]
> As this seems to be related, on our production system (sarama v1.36.0, go 1.19; kafka v2.8.0) a pod just crashed with:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x877330]
> 
> goroutine 1168 [running]:
> github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0x40008e38c0, 0x2)
> 	/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:620 +0x1e0
> github.com/Shopify/sarama.(*partitionProducer).dispatch(0x40008e38c0)
> 	/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:564 +0x4a4
> github.com/Shopify/sarama.withRecover(0xdf5190?)
> 	/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/utils.go:43 +0x40
> created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
> 	/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:515 +0x208
> ```
> 
> Are there any updates on this?
> 
> @crcms You mentioned that this is a must have BUG? So is this panic expected behavior if there is a connection issue for some minutes?

I face the same issue

**Comment by thothothotho** [comment]
got the same issue with sarama@1.37.2 on prod  when we lost our kafka:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xfca3b0]
goroutine 469 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0x40006bc5a0, 0x1)
        /home/jenkins/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/async_producer.go:708 +0x1e0
github.com/Shopify/sarama.(*partitionProducer).dispatch(0x40006bc5a0)
        /home/jenkins/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/async_producer.go:648 +0x4a4
github.com/Shopify/sarama.withRecover(0x0?)
        /home/jenkins/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/utils.go:43 +0x40
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        /home/jenkins/go/pkg/mod/github.com/!shopify/sarama@v1.37.2/async_producer.go:599 +0x208
```

**Comment by wangfe1024** [comment]
Just met the issue on sarama v1.29.1 and go v1.15, any updates to solve it?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ded78f]

goroutine 799 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc0045287e0, 0x1)
	/root/go/src/git.garena.com/shopee/seller-server/crm/crm-proactive-push/vendor/github.com/Shopify/sarama/async_producer.go:617 +0x1cf
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc0045287e0)
	/root/go/src/git.garena.com/shopee/seller-server/crm/crm-proactive-push/vendor/github.com/Shopify/sarama/async_producer.go:561 +0x589
github.com/Shopify/sarama.withRecover(0xc003fcde00)
	/root/go/src/git.garena.com/shopee/seller-server/crm/crm-proactive-push/vendor/github.com/Shopify/sarama/utils.go:43 +0x49
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
	/root/go/src/git.garena.com/shopee/seller-server/crm/crm-proactive-push/vendor/github.com/Shopify/sarama/async_producer.go:512 +0x1aa
```

**Comment by edoger** [comment]
I have a currently feasible mitigation solution: first set the panic handler, rebuild all producers when any panic is caught, and because the panic handler is set, the producer will not automatically close when the producer internally crashes, and the input channel will be fast is filled and blocked, a producer rebuild is also required when this is detected.

**Comment by asddongmen** [comment]
seems this issue was fixed by:[fix: add nil check while producer is retrying (](https://github.com/Shopify/sarama/commit/237925756e46ac948e583fceb81e8738c9f1e04b)

**Comment by dnwe** [comment]
Closing as fixed by https://github.com/IBM/sarama/pull/2387
