### ISSUE TITLE
In my service,can I need to keep the consumers offset?

### ISSUE THREAD

**Issue by smdzz** [IBM/sarama#2189]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| lasted | kafka_2.13-3.1.0 | 1.16 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Problem Description

if my kafka consumer is down, When I start the consumer, I don't want consumers to start reading from the latest offset,
can I need in my service record is a consumer spending offset?
if not need,What should I do?
Please forgive my poor English.

**Comment by dnwe** [comment]
If you're using the consumer group functionality, Kafka will track your committed offset(s) for you. When your consumer group goes down and comes back again, it will start reading from the last committed offset that it saw, not the latest offset.
