### ISSUE TITLE
Error while fetching metadata from broker

### ISSUE THREAD

**Issue by kbsivacse** [IBM/sarama#2195]
##### Versions

| Sarama | Kafka | Go |
|  1.26.4   |  2.0.0   | 1.17 |

##### Configuration
brokers, topics

##### Logs
[Sarama] 2022/03/23 13:12:48 Initializing new client
[Sarama] 2022/03/23 13:12:48 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2022/03/23 13:12:48 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2022/03/23 13:12:48 client/metadata fetching metadata for all topics from broker {broker-ip}:9092
[Sarama] 2022/03/23 13:12:48 Connected to broker at {broker-ip}:9092 (unregistered)
[Sarama] 2022/03/23 13:13:18 client/metadata got error from broker -1 while fetching metadata: read tcp {pod-ip}:44182-> {broker-ip}:9092: i/o timeout
[Sarama] 2022/03/23 13:13:18 Closed connection to broker {broker-ip}:9092
[Sarama] 2022/03/23 13:13:18 client/metadata no available broker to send metadata request to
[Sarama] 2022/03/23 13:13:18 client/brokers resurrecting 1 dead seed brokers
[Sarama] 2022/03/23 13:13:18 client/metadata retrying after 250ms... (3 attempts remaining)
. . .

##### Problem Description
Sarama client is enable make a connection to the broker, but its getting i/0 timeout while getting metadata. Can someone help in fixing this?

**Comment by crcms** [comment]
has retry params

**Comment by dnwe** [comment]
Please reopen if still a problem here
