### ISSUE TITLE
The GitHub Pages link returns `404  File not found`

### ISSUE THREAD

**Issue by techeverri** [IBM/sarama#2207]
_Found it while checking the projects listed here https://shopify.github.io/_

## Problem Description

The GitHub Pages link returns `404  File not found`

https://shopify.github.io/sarama

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/3720424/162246785-327c0ddd-ac5e-4f2e-9c61-2fb1b285f2eb.png">

**Comment by dnwe** [comment]
Yes for a long time it seems that the `gh-pages` branch hasn't been deploying out to the pages.github.com site correctly. Unfortunately I don't have access to the "settings" tab of this repo to explore the GitHub Pages setup

@methodmissing can you help here? I think @bai mentioned that you might have access in the past

**Comment by dnwe** [comment]
No longer an issue since ownership handover
