### ISSUE TITLE
suggestion: incorporate goroutine leak detection into the build

### ISSUE THREAD

**Issue by k-wall** [IBM/sarama#2209]
I'm wondering if incorporating goroutine leak detection into the tests would be a useful increment.     I recently discovered several  goroutine leaks (in both tests and production code) by way of #2202. It would be desirable to prevent regressions 

I am suggesting to incorporate leak detection into the build.

Sketch of an idea:

* `TestMain` invokes the the go.uber.org/goleak leak detector.  This would wired up for both unit tests and functional tests using conditional compilation.
* Leak testing would be off by default and would be enableable by setting a Go Build Tag.  
* Makefile enhanced to enable the developer to run the tests with l[eak detection enabled](https://github.com/uber-go/goleak#determine-source-of-package-leaks).  This allows the test associated with the leak to be identified quickly.
* The existing dependency on github.com/fortytw2/leaktest would be removed.

A later increment would be to have CI perform the leak test too and fail the build if a PR introduces a goroutine leak.

**Comment by dnwe** [comment]
@k-wall yes this sounds like an excellent plan
