### ISSUE TITLE
stringEncoder how to decode to json/map/struct/ ？

### ISSUE THREAD

**Issue by 825644691** [IBM/sarama#2211]
msg := &sarama.ProducerMessage{}
msg.Topic = "aaa"
item := {'aa':aa,'bb':bb} (struct)
res,_ := json.Marshal(item)
msg.Value = sarama.StringEncoder(res)

has any way  decode the `StringEncoder` to `json/struct/map`?

**Comment by dnwe** [comment]
Closing as presumed to have been resolved. Please reopen if not
