### ISSUE TITLE
Consumer stops consuming a single partition in a topic

### ISSUE THREAD

**Issue by nearih** [IBM/sarama#2219]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  v1.30.1|  2.8 |  1.16.5|

##### Configuration
Assignment strategy is round robin

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

My app consume many topics. I have been running for a month. Right now, it cannot consume one partition from one topic. However, the other topics partitions are still get consumed. I wonder what can cause this partition stick problem.
Right now, I resolve it by restarting the application.

**Comment by robertchengzy** [comment]
i have the same issues.

**Comment by huster-hbl** [comment]
I also encountered the same problem, did you solve it?

**Comment by dnwe** [comment]
@huster-hbl @nearih hmm, you’ve seen this with modern versions of sarama? Please can you detail your topics and clients, server version and general config. It’s not immediately obvious to me how this could occur

**Comment by david-bergman** [comment]
its happening to me with the latest version of sarama v1.43.1 , @nearih did you ever figure out a resolution?
