### ISSUE TITLE
AsyncProducer produce wrong message to Kafka

### ISSUE THREAD

**Issue by MasterKenway** [IBM/sarama#2220]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.32.0 | bitnami/kafka:3.1.0 | 1.16.4 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
func GetKafkaAsyncProducer() sarama.AsyncProducer {
	if kafkaProducer != nil {
		return *kafkaProducer
	}

	kafkaEtcdConfBytes, err := GetConfig(constant.EtcdKeyKafkaConfig)
	if err != nil {
		panic(err)
	}

	err = json.Unmarshal(kafkaEtcdConfBytes, &KafkaConf)
	if err != nil {
		panic(err)
	}

	kafkaConfig := sarama.NewConfig()
	sarama.Logger = log2.New(os.Stdout, "[sarama] ", log2.LstdFlags)
	kafkaConfig.Net.SASL.Enable = false
	version, err := sarama.ParseKafkaVersion("3.1.0")
	if err != nil {
		panic(err)
	}
	kafkaConfig.Version = version
	kafkaConfig.Producer.RequiredAcks = sarama.WaitForAll
	kafkaConfig.Producer.Partitioner = sarama.NewRandomPartitioner
	kafkaConfig.Producer.Return.Errors = true

	p, err := sarama.NewAsyncProducer(KafkaConf.Endpoint, kafkaConfig)
	if err != nil {
		panic(err)
	}
	kafkaProducer = &p
	return *kafkaProducer
}
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

</p>
</details>

##### Problem Description

When using AsyncProducer, will lead to message deliver problem.
The bahvior is the first message is work as expect, but when recieve the scoend message, the message getting mess up.
My sitution is put message ` {"L":"INFO","T":"2022-04-24T20:45:22+08:00","M":"User-Agent: PostmanRuntime/7.26.10","RID":"43447343-dbcf-4056-a99b-cde0d9ebb5b7"}` into AsyncProducer.Input(), and the consumer get `"RID":"43447343-dbcf-4056-a99b-cde0d9ebb5b7""M":"User-Agent: PostmanRuntime/7.26.10","RID":"43447343-dbcf-4056-a99b-cde0d9ebb5b7"}`
This problem will not show up when using SyncProducer and kafka_console_producer.sh.

**Comment by dnwe** [comment]
@MasterKenway you don't show the snippet of code where you're putting a *ProducerMessage  into the AsyncProducer.Input() channel — you're definitely creating a new &ProducerMessage{...} for each message yes? Not re-using an existing one that you've already sent to the channel?
