### ISSUE TITLE
Producer performance degradation when upgrading Sarama from 1.27.2 to 1.34.1

### ISSUE THREAD

**Issue by mbarbon** [IBM/sarama#2266]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.34.1 | 2.6  | 1.16.3 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	c.Metadata.Timeout = 20 * time.Second

	c.Producer.Return.Successes = true
	c.Producer.Return.Errors = true

	c.Producer.RequiredAcks = sarama.WaitForLocal
	c.Producer.Compression = sarama.CompressionZSTD

        c.Net.MaxOpenRequests = 5 // and 1, see below
	c.Net.DialTimeout = 10 * time.Second
	c.Net.ReadTimeout = 10 * time.Second
	c.Net.WriteTimeout = 10 * time.Second
	c.Producer.Timeout = 5000 * time.Millisecond

	c.Net.KeepAlive = 60 * time.Second

	c.ChannelBufferSize = 128

	c.Producer.Retry.Max = 5
	c.Producer.Retry.Backoff = 200 * time.Millisecond

```

##### Problem Description

We tried upgrading Sarama, and the overall time it takes to produce to Kafka roughly doubled.

I bisected the slowdown to 8104f4def3af703ca9dba49d7d96d5f93f84a5a5 I see there were subsequent change in async producer/pipelining, but they did not improve the performance for my use case.

I do not have a synthetic benchmark yet (sorry, will try to make one in the coming days)

The measurements below are for a set of processes with an average throughput (after compression) of: 
~233MB/min
~2.58M msgs/min
~95 bytes/msg
with the data produced in 20-or-so batches per minute.

Send is the per-batch producer time averaged over <Samples> batches>

```
Type:       1.27.2,MaxOpenRequests=1
Samples:    106
Send:       26.08

Type:       1.27.2,MaxOpenRequests=5
Samples:    138
Send:       25.52

Type:       1.34.1,MaxOpenRequests=1
Samples:    178
Send:       31.31

Type:       1.34.1,MaxOpenRequests=5
Samples:    162
Send:       53.02

Type:       8104f4def3af703ca9dba49d7d96d5f93f84a5a5,MaxOpenRequests=1
Samples:    81
Send:       32.81
```

What I find puzzling is that, with recent versions, using `MaxOpenRequests=1` improves performance.

**Comment by mbarbon** [comment]
@xujianhai666 and @slaunay maybe you have some insight since this seems to be related to your changes in Sarama 1.31.0?

**Comment by dnwe** [comment]
@mbarbon the bit I'm not clear on here is whether the actual throughput of Sarama's producer writing messages to kafka has degraded or whether the internal goroutine mechanism for returning the producer successes is less performant and so stalling your execution. The benchmark timings here are obviously based around receiving on the Successes channel and that also gates when you send the next batch.
