### ISSUE TITLE
Unrelated Responses are pushed to paused subscription children

### ISSUE THREAD

**Issue by pkoutsovasilis** [IBM/sarama#2316]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.34.1 | 7.2.1-ccs (Commit:80334008361592c187b36a27536f10f33fe93aa3) | go1.17.13 |

##### Problem Description

This [PR](https://github.com/Shopify/sarama/pull/2143) fixes [this issue](https://github.com/Shopify/sarama/issues/2125) and it prevents sending requests with no blocks when all the respective child subscriptions for all partiotions of all topics in a consumer group are paused. However, there is a corner-case where only the respective child subscriptions for all partitions of only a single topic is paused, given that the consumergroup contains more than one topics. In this case, the request will have some blocks in it and thus we will try and fetch a response, but when we push back to the paused children this response, this won't contain anything about their partition or topic altogether, and we will hit again this issue

```
2022-08-11T23:29:50.054934Z	debug	[kafka: error while consuming test_topic_1/2: kafka: response did not contain all the expected topic/partition blocks]
2022-08-11T23:29:50.055004Z	debug	consumer/broker/[1 %!d(string=test_topic_1) 2 1374391067872] abandoned subscription to %!s(MISSING)/%!d(MISSING) because %!s(MISSING)
```

**Comment by dnwe** [comment]
@pkoutsovasilis hmm thanks, that's not good — another reason that we need more FV testing in the Pause+Resume consumer group codepath
