### ISSUE TITLE
Should a Paused consumer immediately stop delivering buffered FetchResponse records and only deliver those on Resume?

### ISSUE THREAD

**Issue by huange7** [IBM/sarama#2323]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|v1.34.1  | v2.7.1 |  1.17.6 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	c.Admin.Retry.Max = 5
	c.Admin.Retry.Backoff = 100 * time.Millisecond
	c.Admin.Timeout = 3 * time.Second

	c.Net.MaxOpenRequests = 5
	c.Net.DialTimeout = 30 * time.Second
	c.Net.ReadTimeout = 30 * time.Second
	c.Net.WriteTimeout = 30 * time.Second
	c.Net.SASL.Handshake = true
	c.Net.SASL.Version = SASLHandshakeV0

	c.Metadata.Retry.Max = 3
	c.Metadata.Retry.Backoff = 250 * time.Millisecond
	c.Metadata.RefreshFrequency = 10 * time.Minute
	c.Metadata.Full = true
	c.Metadata.AllowAutoTopicCreation = true

	c.Producer.MaxMessageBytes = 1000000
	c.Producer.RequiredAcks = WaitForLocal
	c.Producer.Timeout = 10 * time.Second
	c.Producer.Partitioner = NewHashPartitioner
	c.Producer.Retry.Max = 3
	c.Producer.Retry.Backoff = 100 * time.Millisecond
	c.Producer.Return.Errors = true
	c.Producer.CompressionLevel = CompressionLevelDefault

	c.Consumer.Fetch.Min = 1
	c.Consumer.Fetch.Default = 1024 * 1024
	c.Consumer.Retry.Backoff = 2 * time.Second
	c.Consumer.MaxWaitTime = 500 * time.Millisecond
	c.Consumer.MaxProcessingTime = 100 * time.Millisecond
	c.Consumer.Return.Errors = false
	c.Consumer.Offsets.AutoCommit.Enable = true
	c.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
	c.Consumer.Offsets.Initial = OffsetOldest
	c.Consumer.Offsets.Retry.Max = 3

	c.Consumer.Group.Session.Timeout = 10 * time.Second
	c.Consumer.Group.Heartbeat.Interval = 3 * time.Second
	c.Consumer.Group.Rebalance.Strategy = BalanceStrategyRange
	c.Consumer.Group.Rebalance.Timeout = 60 * time.Second
	c.Consumer.Group.Rebalance.Retry.Max = 4
	c.Consumer.Group.Rebalance.Retry.Backoff = 2 * time.Second
	c.Consumer.Group.ResetInvalidOffsets = false

	c.ClientID = defaultClientID
	c.ChannelBufferSize = 256
	c.ApiVersionsRequest = true
	c.Version = DefaultVersion
	c.MetricRegistry = metrics.NewRegistry()
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
When the pause() method is called, the unprocessed data in the pipeline will be processed, and the pause() method will still be triggered at this time, but the original data that led to pause cannot be obtained after resume().

Is it possible to record the offset when the pause() is triggered and continue to consume from that offset after the resume()?

**Comment by dnwe** [comment]
@huange7 hmm, are calling pause() the client will stop fetching new records and any buffered records should be delivered on the messages channel. Are you saying you would want the auto-commit to also pause when pause is called and re-fetch and re-deliver them on resume?

**Comment by huange7** [comment]
> Are you saying you would want the auto-commit to also pause when pause is called and re-fetch and re-deliver them on resume?

Thanks for your reply!  That's exactly what I thought, but I don't know if the latest version has this feature or not

**Comment by dnwe** [comment]
No worries, and thanks for clarifying. I need to investigate what we can do here, currently we don't have good FV coverage of the Pause and Resume behaviour, just a mock-based unittest [here](https://github.com/IBM/sarama/blob/d2dba29e9545c5af80169e541b1170c3dd34b3b9/consumer_test.go#L150-L229) — so we'd probably need to start by adding a fuller FV test to verify what the current behaviour is, and then compare it with the Java client implementation (starting with [KAFKA-2350](https://github.com/apache/kafka/commit/be82a2afc9e38adc0109dc694834ca5947128877)  but also being mindful of [KAFKA-7548](https://github.com/apache/kafka/commit/1546fc30af))
