### ISSUE TITLE
SASL_SSL settings are not working with sarama pkg

### ISSUE THREAD

**Issue by vjakka-intel** [IBM/sarama#2324]
Go  client for Kafka version used as github.com/Shopify/sarama v1.32.0

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

	config := sarama.NewConfig()
	config.Net.SASL.Mechanism = sarama.SASLTypePlaintext  //"PLAIN"
	config.Net.SASL.Enable = true
	config.Net.SASL.User = "admin"
	config.Net.SASL.Password = "admin"
	config.Net.SASL.Version = 1
	config.Net.SASL.Handshake = false
	config.Metadata.Full = true
       config.Producer.RequiredAcks = sarama.WaitForAll

        brokers := []string{"localhost:9092"}
	producer, err := sarama.NewAsyncProducer(brokers, config)   ===> getting error in this line with above config values

What configuration values are you using for Sarama and Kafka?
``` 
server.properties
listeners=SASL_PLAINTEXT://localhost:9092
security.protocol=SASL_PLAINTEXT
sasl.enabled.mechanisms=PLAIN
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
plain.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=admin password=admin

WIth above server.properties,  I am able to run the Kafka Server successfully.
```

##### Logs

PS C:\Users\vjakka\vjSaramaClient> go run .\main.go
[sarama] 2022/08/27 16:18:55 Initializing new client
[sarama] 2022/08/27 16:18:55 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2022/08/27 16:18:55 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2022/08/27 16:18:55 client/metadata fetching metadata for all topics from broker localhost:9092
[sarama] 2022/08/27 16:18:56 Failed to read response while authenticating with SASL to broker localhost:9092: EOF
[sarama] 2022/08/27 16:18:56 Closed connection to broker localhost:9092
[sarama] 2022/08/27 16:18:56 client/metadata got error from broker -1 while fetching metadata: EOF
[sarama] 2022/08/27 16:18:56 client/metadata no available broker to send metadata request to
[sarama] 2022/08/27 16:18:56 client/brokers resurrecting 1 dead seed brokers
[sarama] 2022/08/27 16:18:56 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2022/08/27 16:18:56 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2022/08/27 16:18:56 client/metadata fetching metadata for all topics from broker localhost:9092
[sarama] 2022/08/27 16:18:57 Failed to read response while authenticating with SASL to broker localhost:9092: EOF

```
```

</p>
</details>

##### Problem Description

Kafka Server is enabled with SASL_SSL with username and password.  I am unable to  create producer to produce the message. 

I am unable to create consumer also.

I am not sure, how we can pass this parameter security.protocol=SASL_SSL to config file ??

Can someone help us in this ?

**Comment by imorte** [comment]
@iwpnd many thanks!

**Comment by dnwe** [comment]
Looks like this was resolved
