### ISSUE TITLE
config option to disable validation

### ISSUE THREAD

**Issue by tooptoop4** [IBM/sarama#2366]
need a way to skip https://github.com/Shopify/sarama/blob/fb9a93150c8468e731102e6908cc298aeaecf17b/client.go#L170 so that other apps can pass in MSK IAM SASL code without being blocked

**Comment by tooptoop4** [comment]
crunch

**Comment by dnwe** [comment]
@tooptoop4 can you elaborate a little more on what you’re trying to do?

**Comment by tooptoop4** [comment]
MSK IAM support

**Comment by dnwe** [comment]
The intention was that would come in v2 https://github.com/IBM/sarama/pull/2482

Its not obvious how disabling config validation helps you
