### ISSUE TITLE
TLS communication between MSK and kafka

### ISSUE THREAD

**Issue by oussemabhouri** [IBM/sarama#2367]
##### Configuration

What configuration values are you using for Sarama and Kafka?
``` 
        type Config struct {
	ConsumerBrokers []string       `envconfig:"consumer_brokers"`
	ProducerBrokers []string       `envconfig:"producer_brokers"`
	ClientConfig    *sarama.Config `envconfig:"client_config"`
	ConsumerTopic   string         `default:"Firehose" envconfig:"consumer_topic"`
	ConsumerGroup   string         `default:"router" envconfig:"consumer_group"`
	ProducerPrefix  string         `default:"" envconfig:"producer_prefix"`
	LogLevel        string         `default:"info" envconfig:"log_level"`
	HttpAddr        string         `default:":8080" envconfig:"http_addr"`
}
        var conf Config
        conf.ClientConfig = sarama.NewConfig()
		tlsConfig := tls.Config{}
		conf.ClientConfig.Net.TLS.Enable = true
		conf.ClientConfig.Net.TLS.Config = &tlsConfig
		conf.ClientConfig.Net.TLS.Config.InsecureSkipVerify = false
	}
```

##### Logs

{"level":"panic","method":"main","msg":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","package":"main","time":"2022-10-19T14:36:46Z"}

##### Problem Description
I want to enable TLS communication between my component and MSK ! setting up InsecureSkipVerify to true makes it work, but with false it fails with the above error.
I don't have any server certificate.
I am using TLS MSK endpoints

**Comment by dnwe** [comment]
@oussemabhouri I’m hoping that you’ve resolved this issue by now, but feel free to re-open if not. 

If your Sarama connectivity succeeded with InsecureSkipVerify but failed without, then either your server side certificate wasn’t trusted by the client or your broker hostnames didn’t match one of the SubjectALtNames in the certificate
