### ISSUE TITLE
ResetOffset not working when start up using local checkpoint

### ISSUE THREAD

**Issue by npsables** [IBM/sarama#2379]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.37.2 | 3.2.3 |  1.17 |

##### Problem Description

Hi guys, I'm trying to create a local checkpoint in case consumer offsets in kafka are gone. And in that case, I get that it will restart at the earliest or latest. 

Is this intentional? Can we get pom to reset at desired offset?

**Comment by yexinhua1998** [comment]
I encouter the same problem and I will try to create a PR to fix it.
