### ISSUE TITLE
Is there any solution to use consumer group / groupID if my Kafka version is lower than 0.10.2.0

### ISSUE THREAD

**Issue by Baytwt** [IBM/sarama#2395]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.37.2  |  0.10.1.1 |  1.18|

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
// Version: "0.10.1.1"
version, _ := sarama.ParseKafkaVersion(options.Version)
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

My Kafka broker version is 0.10.1.1, while according to `consumer_group.go:126` , "consumer groups requireVersion to be >= V0_10_2_0".

Is there any solution if I want to use consumer group or group ID?

**Comment by dnwe** [comment]
Unfortunately not. The sarama consumer group support was coded at the 0.10.2.0 protocol as a baseline and I don't think it's something we'd look to retrofit to releases older than 2017. I'd strongly recommend upgrading your kafka cluster to newer versions for the numerous reliability and performance improvements
