### ISSUE TITLE
Add an ErrorLogger to distinguish info from errors

### ISSUE THREAD

**Issue by blrnw3** [IBM/sarama#2401]
##### Versions

All

##### Configuration

What configuration values are you using for Sarama and Kafka?
default

##### Logs
n/a

##### Problem Description

Sarama has a `StdLogger` and a `DebugLogger`, but no `ErrorLogger`.
We override the existing loggers and push the messages to our logging stack, with either debug or info log level. However we'd like to know what messages are actually errors and push those with an error level so our systems can notify and record them correctly. It looks like Sarama uses the  `StdLogger` for both informational and error messages, so we cannot easily extract the errors.

Examples of error messages:
`Failed to connect to broker %s: %s`
`Error while performing SASL handshake %s`

Examples of informational messages:
`consumer/broker/%d added subscription to %s/%d`
`producer/leader/%s/%d selected broker %d`

One alternative I can see is to shift the informational logs to the debug logger, since most of the messages do seem to be errors.

If you think this is reasonable, I'm happy to contribute a PR.

Thanks!

**Comment by dnwe** [comment]
@blrnw3 yes I think the intention was to move all informational messages over to DebugLogger over time and StdLogger would only be intended for the out of the ordinary problems/warnings/errrors
