### ISSUE TITLE
Timeline on supporting kafka version 3.3.1 (Kraft)

### ISSUE THREAD

**Issue by Derek-Hardy** [IBM/sarama#2405]
##### Versions

latest (v1.37.2)

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
V3_2_3_0  = newKafkaVersion(3, 2, 3, 0)
```

##### Problem Description

What is the timeline on supporting the latest Kraft production-ready Kafka version 3.3.1?

The latest Sarama only has version variables until v3.2.3

**Comment by dnwe** [comment]
So https://github.com/Shopify/sarama/pull/2406 adds 3.3.1 constants and includes it in the fvt testing matrix — this is still using it in zookeeper mode though, I'll probably look at making an fv run that deploys it in kraft mode too, although that should only effect server-side and the client doesn't need to change its behaviour
