### ISSUE TITLE
How can I identify a commit operation is successful?

### ISSUE THREAD

**Issue by ZzIris** [IBM/sarama#2417]
hello! it's i first time to learn to use sarama. I find that there is not a error return when i call sarama.ConsumerGroupSession.Commit,  i should use sarama.ConsumerGroup.Errors() if i want to get a error, but i don't know the error which i get from sarama.ConsumerGroup.Errors() is really from commit operation or other operation,  how can i identify a error is a commit error in another word? please give me example, thanks!!!

**Comment by ZzIris** [comment]
@dnwe for example, in some case, my application encountering a network error for a long time, and the application will recrod the offset have consumed but fail to commit when i restart the application at this moment to prevent process again，the application will nerver know which offset is consumed but fail to commit if i can't match the error from commit operation~ how can i do? what key word of the error that I can get from sarama.ConsumerGroup.Errors()? i try to find a definition about commit error, but just find sarama.ErrTxnOffsetCommit、sarama.ErrUnstableOffsetCommit、sarama.ErrInvalidCommitOffsetSize，the commit errors are not always related to them in my opinion.

**Comment by joewreschnig** [comment]
Would it be acceptable (in terms of API stability) to also have `Commit` return the error from the offset manager (as well as forwarding it through the handlers)? All existing code should be compatible, but it would trigger some popular linters.

**Comment by dnwe** [comment]
@joewreschnig thanks, I pull in your changes and rebased them under PR #2635 so we can have a think about the API compatibility changes
