### ISSUE TITLE
Feature: Support for Kerberos authentication using a credentials cache.

### ISSUE THREAD

**Issue by mrogaski** [IBM/sarama#2421]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.38.0 | any | any |

##### Problem Description

We would like to use Sarama in on platforms where Kerberos credential caches are exposed, but no password credentials or keytabs are available.

This feature would require a new GSSAPI auth type (e.g. KRB_CCACHE) that would result in `NewKerberosClient` returning a Kerberos client produced by the [NewFromCCache](https://pkg.go.dev/github.com/jcmturner/gokrb5/v8@v8.4.3/client#NewFromCCache) function.

**Comment by mrogaski** [comment]
We're still interested in having this feature for use cases where a pure-Go client is needed.

**Comment by dnwe** [comment]
Implemented by https://github.com/IBM/sarama/pull/2457
