### ISSUE TITLE
Broker abandoning subscription because consuming is taking too long.

### ISSUE THREAD

**Issue by rhammonds1-kr** [IBM/sarama#2425]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.37.2 | 3.2.0 | 1.19.2 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
c.Admin.Retry.Max = 5
c.Admin.Retry.Backoff = 100 * time.Millisecond
c.Admin.Timeout = 3 * time.Second

c.Net.MaxOpenRequests = 5
c.Net.DialTimeout = 30 * time.Second
c.Net.ReadTimeout = 30 * time.Second
c.Net.WriteTimeout = 30 * time.Second
c.Net.SASL.Handshake = true
c.Net.SASL.Version = SASLHandshakeV0

c.Metadata.Retry.Max = 3
c.Metadata.Retry.Backoff = 250 * time.Millisecond
c.Metadata.RefreshFrequency = 10 * time.Minute
c.Metadata.Full = true
c.Metadata.AllowAutoTopicCreation = true

c.Consumer.Fetch.Min = 1
c.Consumer.Fetch.Default = 1024 * 1024
c.Consumer.Retry.Backoff = 2 * time.Second
c.Consumer.MaxWaitTime = 500 * time.Millisecond
c.Consumer.MaxProcessingTime = 100 * time.Millisecond
c.Consumer.Return.Errors = false
c.Consumer.Offsets.AutoCommit.Enable = true
c.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
c.Consumer.Offsets.Initial = OffsetNewest
c.Consumer.Offsets.Retry.Max = 3

c.Consumer.Group.Session.Timeout = 10 * time.Second
c.Consumer.Group.Heartbeat.Interval = 3 * time.Second
c.Consumer.Group.Rebalance.GroupStrategies = []BalanceStrategy{BalanceStrategyRange}
c.Consumer.Group.Rebalance.Timeout = 60 * time.Second
c.Consumer.Group.Rebalance.Retry.Max = 4
c.Consumer.Group.Rebalance.Retry.Backoff = 2 * time.Second
c.Consumer.Group.ResetInvalidOffsets = true
```

##### Logs

12/15/2022, 2:56:12.857 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:56:12.478 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:56:12.478 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:55:07.792 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:55:06.674 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:55:06.674 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:54:03.893 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:54:03.082 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:54:03.082 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:52:53.157 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:52:52.722 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:52:52.722 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:51:49.094 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

We continually have issues across higher volume topics that one of the instances running will stop consuming from a specific partition. I think it may be correlated to log rolling events on the partition. However, it never seems to recover and lag just continues to grow.

Removing all members and rebalancing does show that non/slow consuming instances do not rejoin immediately but eventually will after 4-5 minutes which causes a relabalancing loop for awhile. It's easier to just kill the instances and start over.

**Comment by dnwe** [comment]
@rhammonds1-kr it looks like you've set [MaxProcessingTime](https://github.com/Shopify/sarama/blob/6acb2767144a840d9cc423f2917617e3372da7be/config.go#L383-L400) to 100ms (which is also the default) in your consumer configuration and haven't changed [ChannelBufferSize](https://github.com/Shopify/sarama/blob/6acb2767144a840d9cc423f2917617e3372da7be/config.go#L470-L474) 

The "timed out feeding messages to the user" is that "feeder" channel queue filling up and not being removed quickly enough by your own channel reader in your [ConsumeClaim](https://github.com/Shopify/sarama/blob/0b1569510cac5d149fda024dcc173f4dd0dcfc7c/examples/consumergroup/main.go#L176-L195) implementation. If you have too much application logic or potential contention on resources within that loop then your code may not be reading messages off the channel quickly enough to drain it faster than it gets filled up

**Comment by tongyi24** [comment]
> [@rhammonds1-kr](https://github.com/rhammonds1-kr) it looks like you've set [MaxProcessingTime](https://github.com/Shopify/sarama/blob/6acb2767144a840d9cc423f2917617e3372da7be/config.go#L383-L400) to 100ms (which is also the default) in your consumer configuration and haven't changed [ChannelBufferSize](https://github.com/Shopify/sarama/blob/6acb2767144a840d9cc423f2917617e3372da7be/config.go#L470-L474)看起来你在消费者配置中设置了 MaxProcessingTime 为 100ms（这也是默认值），并且没有更改 ChannelBufferSize
> 
> The "timed out feeding messages to the user" is that "feeder" channel queue filling up and not being removed quickly enough by your own channel reader in your [ConsumeClaim](https://github.com/Shopify/sarama/blob/0b1569510cac5d149fda024dcc173f4dd0dcfc7c/examples/consumergroup/main.go#L176-L195) implementation. If you have too much application logic or potential contention on resources within that loop then your code may not be reading messages off the channel quickly enough to drain it faster than it gets filled up"向用户传递消息时超时"是指"feeder"通道队列填满，而你的通道读取器在 ConsumeClaim 实现中未能足够快地清除。如果你在该循环中有太多应用逻辑或资源潜在争用，那么你的代码可能没有足够快地从通道读取消息，以使其排空的速度快于填满的速度

@dnwe So why it causes a relabalancing loop? Would you help me with this[https://github.com/IBM/sarama/issues/3200]. Thanks!
