### ISSUE TITLE
DATA RACE

### ISSUE THREAD

**Issue by why444216978** [IBM/sarama#2439]
WARNING: DATA RACE
Write at 0x00c000127638 by goroutine 101:
  github.com/Shopify/sarama.(*Broker).registerMetrics()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:1651 +0x12c
  github.com/Shopify/sarama.(*Broker).Open.func1()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:227 +0x11d1
  github.com/Shopify/sarama.withRecover()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:43 +0x48
  github.com/Shopify/sarama.(*Broker).Open.func2()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:180 +0x39

Previous read at 0x00c000127638 by goroutine 57:
  github.com/Shopify/sarama.(*Broker).Fetch.func1()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:496 +0x95
  runtime.deferreturn()
      /usr/local/go19/src/runtime/panic.go:476 +0x32
  github.com/Shopify/sarama.(*brokerConsumer).fetchNewMessages()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:1111 +0xf1d
  github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:935 +0x155
  github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer-fm()
      <autogenerated>:1 +0x39
  github.com/Shopify/sarama.withRecover()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:43 +0x48
  github.com/Shopify/sarama.(*consumer).newBrokerConsumer.func2()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:874 +0x39

Goroutine 101 (running) created at:
  github.com/Shopify/sarama.(*Broker).Open()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:180 +0x592
  github.com/Shopify/sarama.(*client).Coordinator()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/client.go:621 +0xcf
  github.com/Shopify/sarama.(*nopCloserClient).Coordinator()
      <autogenerated>:1 +0x6f
  github.com/Shopify/sarama.(*consumerGroupSession).heartbeatLoop()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:927 +0x430
  github.com/Shopify/sarama.newConsumerGroupSession.func3()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:754 +0x39

Goroutine 57 (running) created at:
  github.com/Shopify/sarama.(*consumer).newBrokerConsumer()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:874 +0x3c4
  github.com/Shopify/sarama.(*consumer).refBrokerConsumer()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:245 +0x127
  github.com/Shopify/sarama.(*consumer).ConsumePartition()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer.go:192 +0x7b6
  github.com/Shopify/sarama.newConsumerGroupClaim()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:1037 +0xbb
  github.com/Shopify/sarama.(*consumerGroupSession).consume()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:845 +0x23e
  github.com/Shopify/sarama.newConsumerGroupSession.func2()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:793 +0xfb
  github.com/Shopify/sarama.newConsumerGroupSession.func5()
      /home/users/weihaoyu/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/consumer_group.go:794 +0x63
==================

**Comment by napallday** [comment]
After investigation, I find this issue was introduced in #2299.

It's not guaranteed https://github.com/IBM/sarama/blob/v1.40.1/broker.go#L218 
```		
b.fetchRate = metrics.GetOrRegisterMeter("consumer-fetch-rate", b.metricRegistry)
```
happens before https://github.com/IBM/sarama/blob/v1.40.1/broker.go#L495
```
if b.fetchRate != nil {
	b.fetchRate.Mark(1)
}
```
