### ISSUE TITLE
How consumer group support multiple consumers consume the same group?

### ISSUE THREAD

**Issue by yitian108** [IBM/sarama#2446]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.37.0 |2.5.0  | 1.17.11 |

Now, I try to use Shopify/sarama library(kafka go client) to implement multiple consumers in the same consumer group, and I have the following testing:
Suppose the topic have 3 partitions, and the group Id is "groupId":

###### TEST-1  

(1) 
```go
newClient, err := sarama.NewClient(brokerList, &cfg)
```
(2)
```go
 group1, err := sarama.NewConsumerGroupFromClient(groupId, newClient)
 group2, err := sarama.NewConsumerGroupFromClient(groupId, newClient)
 group3, err := sarama.NewConsumerGroupFromClient(groupId, newClient)
```
The testing is try to use a kakfa client(newClient) to create multiple groups, and the program will block one group, and the other two groups will not response, it seems to block the following code:
```go
group.Consume(ctx, strings.Split(topics, ","), consumer)
```
and then a moment later, the program rebalance (setup/clean up) repeatly, the result is that the consumer consumed all partitions, not each consumer consume per partition.

###### TEST-2

(1) 
```go
newClient1, err := sarama.NewClient(brokerList, &cfg)
group1, err := sarama.NewConsumerGroupFromClient(groupId, newClient1)
```
  
(2) 
```go
newClient2, err := sarama.NewClient(brokerList, &cfg)
group2, err := sarama.NewConsumerGroupFromClient(groupId, newClient2)
```
 
(3) 
```go
newClient3, err := sarama.NewClient(brokerList, &cfg)
group3, err := sarama.NewConsumerGroupFromClient(groupId, newClient3)
```
In this testing, we can see each consumer group with a new client, the result indicates that each consumer will consume a partition, which accord with expection.

So, How can I  implement multiple consumer groups bind the same kafka client, rather than creating a new client per consumer group?

**Comment by yitian108** [comment]
Multiple kakfa consumer with the same groupId and the shared one kafka client @eapache @dnwe Could you please check this would be an issue?

**Comment by simon28082** [comment]
The partition feature of kafka doesn't support such behavior, but there is another idea to consume it and redistribute it downstream, similar to a proxy, which we are doing and it works well

**Comment by Pkfire26** [comment]
> Multiple kakfa consumer with the same groupId and the shared one kafka client @eapache @dnwe Could you please check this would be an issue?

Hi, I'm just wondering what the goal would be to have multiple consumer groups on the same client. I'm not sure what sharing a client would accomplish. Just inquiring for the sake of understanding the kafka better.
