### ISSUE TITLE
Transition sarama ownership

### ISSUE THREAD

**Issue by dmariassy** [IBM/sarama#2461]
Shopify's Streaming team has decided to shift away from native Kafka libraries (such as sarama or [ruby-kafka](https://github.com/zendesk/ruby-kafka)), and to favour bindings of [librdkafka](https://github.com/confluentinc/librdkafka) (e.g. [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go) and [rdkafka-ruby](https://github.com/appsignal/rdkafka-ruby)) instead. As a result we don't believe that Shopify is the best positioned to act as an effective steward of sarama in the long term. Therefore, we would like to begin the process of finding a new owner for this popular and widely adopted project.

In the coming days and weeks our team will reach out to the most active sarama contributors and some of its largest adopters to discuss options for a smooth transition of ownership. We also welcome volunteers' expression of interest in the comments below! Our goal is to execute this handover in a way that minimizes disruption for existing users, and ensures the level of continued support that the project deserves.

**Comment by ninadingole** [comment]
@dmariassy what was the reason to move towards librdkafka and confluent-kafka-go? I know the confluent go library was not that performant as compared to sarama

**Comment by dmariassy** [comment]
Hi @ninadingole, the tl;dr is that we have a number of C-style languages that our platform team needs to support (Go, Ruby, Python, Rust), and so zeroing in on a C engine (librdkafka) provides us with economies of scale.

**Comment by napallday** [comment]
hi @dmariassy , may I know if there is any update on this one? 

In my company Shopee, I have built an enhanced Kafka client library on top of Sarama, and ensuring the stability and continuity of Sarama is of utmost importance to us. 

While our company may not have the resources to fully take over the project, I personally have a strong interest in contributing as an one of the individual maintainers. I have participated in the Sarama community, submitting several pull requests over the past year, and I'm committed to supporting and improving the project going forward.

**Comment by dmariassy** [comment]
Hi @napallday , I should be able to share more details on this soon but it looks like we're on track to secure the future of the project 🤞🏻

**Comment by dmariassy** [comment]
https://github.com/IBM/sarama ✅

**Comment by lizthegrey** [comment]
Congrats @dnwe and thank you @IBM!
