### ISSUE TITLE
broker.Produce sporadically fails with network errors

### ISSUE THREAD

**Issue by gfazenda** [IBM/sarama#2462]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.33.0 | 2.3.0  | 1.19.1 |

Hello,

I have an implementation of a transactional kafka producer,
which uses the low-level methods from Sarama v1.33 as it was developed before the official transactional feature.

The logic works as expected in most scenarios, however when running with one specific kafka MSK instance (version 2.3.0),
the **broker.Produce** method simply fails with network related errors such as

```
i/o timeout
connection reset by peer
```
and so on.

Example:

`read tcp <IP> -> <IP>: i/o timeout `

The issue is that the errors are not consistent at all, they can happen after a random number of messages/transactions,
after the producer is running for 10, 20, 50minutes, etc.
What I did notice is that the errors become way less likely to happen when transaction commits happen in around 120sec (and higher values).
When the commit interval is lower than that: 15, 30, 90sec, ... the error happens.
The number of messages in each transaction does not affect this. 

Considering this, I suspect that the errors are actually not correct, what may be happening is that there is an actual issue being reported by the Kafka Server, but Sarama only reports there network messages that are not helpful, 
specially considering that other instances of such producer in sync mode can run in parallel against the same server without any of such errors. 
Nothing helpful was found in the kafka logs as well. 

The most strange fact is that even with the same exact setup and intervals this cannot be reproduced on other kafka instances (multi/single-brokers), even with very similar/same set of configs.

Could this be somehow related to a server configuration?
Does anyone have any suggestion to better identify the actual root cause of such errors? 
I can provide more details if necessary, but even with DEBUG level traces on Sarama side there are no further details about the issue.

**Comment by dnwe** [comment]
@gfazenda yeah my guess is that MSK broker instance is just locking up or hitting some sort of protocol error on the server side and closing the remote socket end

My understanding is that you can get broker logs out of MSK (via CloudWatch?) so I'd suggest that you look into enabling that and hopefully that will identify the issue
