### ISSUE TITLE
Could anyBroker()  be made more relient?

### ISSUE THREAD

**Issue by vinhtbcasoft** [IBM/sarama#2488]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.38.1 |2.3.0 | 1.18 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
```
config := sarama.NewConfig()
config.Version = version
config.Consumer.Offsets.Initial = sarama.OffsetOldest
ConsumerGrpClient, err =  sarama.NewConsumerGroup(core.KafkaInitialBrokers, consumerGrpId, config)
```

##### Logs
```
[sarama] 2023/06/18 18:12:34 tryRefreshMetadata(): client/metadata fetching metadata for [__consumer_offsets] from broker 10.8.13.1:9092
[sarama] 2023/06/18 18:12:34 tryRefreshMetadata(): successfully fetched metadata for topics.
[sarama] 2023/06/18 18:12:34 Unexpected topic-level metadata error: kafka server: Replication-factor is invalid.
[sarama] 2023/06/18 18:12:34 ERROR:  tryRefreshMetadata(): successfully fetched metadata but failed on updateMetadata, err: kafka server: Replication-factor is invalid.
[sarama] 2023/06/18 18:12:34 ERROR:  client/coordinator the __consumer_offsets topic is not initialized completely yet. Waiting 2 seconds...
[sarama] 2023/06/18 18:12:34 tryRefreshMetadata(): successfully fetched metadata for topics.
[sarama] 2023/06/18 18:12:34 Unexpected topic-level metadata error: kafka server: Replication-factor is invalid.
[sarama] 2023/06/18 18:12:34 ERROR:  tryRefreshMetadata(): successfully fetched metadata but failed on updateMetadata, err: kafka server: Replication-factor is invalid.
[sarama] 2023/06/18 18:12:34 ERROR:  client/coordinator the __consumer_offsets topic is not initialized completely yet. Waiting 2 seconds...
```

</p>
</details>

##### Problem Description
Within client.go::findCoordinator() and tryRefreshMetadata(), it asks anyBroker() for the endpoint of the request.  anyBroker() will return the same endpoint (first one of the client.seedBrokers list).  This is an issue if the chosen endpoint is misconfigured (it will return a error response).  In this use case, the broker is not evicted from the client.seedBrokers list.

Could anyBroker() be more resilient with the following enhancement?

- What is the downside of anyBroker() returning a random endpoint from client.seedBrokers()?
- Base on Sarama's wiki page (https://github.com/Shopify/sarama/wiki/Cluster-metadata), a suggestion was made to use client.brokers list and ignore client.seedBrokers once initialization is completed.

**Comment by dnwe** [comment]
Although the code gives the appearance of always choosing the first seed broker, there are a few code paths that randomise the seed brokers slice via [client.randomizeSeedBrokers](https://github.com/IBM/sarama/blob/849c8b10c89397fe096f3ed3d78f624706a73060/client.go#L683) such that this should be a different order at various points in time

**Comment by dnwe** [comment]
I believe that the changes made under https://github.com/IBM/sarama/pull/2645 have improved this area so I'm going to go ahead and close this issue as fixed by that. Feel free to re-open if you have further concerns
