### ISSUE TITLE
 kafka: error decoding packet: invalid array length

### ISSUE THREAD

**Issue by yehaotong** [IBM/sarama#2524]
[[[[##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
](kafka: error decoding packet: invalid array length)]

**Comment by dnwe** [comment]
@yehaotong this generally means that the server has sent a response in a version that we don’t yet understand or haven’t correctly added support for, but we’d need to know your config settings, your broker version(s) and some sarama debug logs as per the issue template

**Comment by yehaotong** [comment]
> @yehaotong this generally means that the server has sent a response in a version that we don’t yet understand or haven’t correctly added support for, but we’d need to know your config settings, your broker version(s) and some sarama debug logs as per the issue template

I use the kafka-exporter to scrape kafka metrics, and it miss some consumergroup metric,and I find the log on the kafka-exporter: Cannot get consumer group: kafka: error decoding packet: invalid array length

**Comment by yehaotong** [comment]
> @yehaotong this generally means that the server has sent a response in a version that we don’t yet understand or haven’t correctly added support for, but we’d need to know your config settings, your broker version(s) and some sarama debug logs as per the issue template

the sarama version is: 1.38.1 , and the kafka version is: confluentinc/cp-kafka:5.0.3

**Comment by dnwe** [comment]
Hmm, I know the DescribeGroups response is somewhat undocumented in the member metadata area. I did fixup some issues in https://github.com/IBM/sarama/pull/2111 in the past but it sounds like kafka-exporter would already have that fix

**Comment by dnwe** [comment]
cp-kafka:5.0.3, so Kafka 2.0.1 afaik. What clients do you have connected to your (missing) consumer group?

**Comment by yehaotong** [comment]
> cp-kafka:5.0.3, so Kafka 2.0.1 afaik. What clients do you have connected to your (missing) consumer group?

what is mean clients connected to consumer group?
the missing consumer group can still scrape a few days ago, but at a certain moment, some indicators of the consumer group are all lost at the same time，and log begins to appear Cannot get consumer group: kafka: error decoding packet: invalid array length

**Comment by dnwe** [comment]
My guess is that something about the metadata recorded by the consumers in the group is causing the decoding error when Sarama describes it, but I’m not sure what clients you are using in the group to actually consume the messages

**Comment by yehaotong** [comment]
> My guess is that something about the metadata recorded by the consumers in the group is causing the decoding error when Sarama describes it, but I’m not sure what clients you are using in the group to actually consume the messages

How should I verify if there are any issues with the metadata you mentioned
