### ISSUE TITLE
consumer receive multiple message with the same offset

### ISSUE THREAD

**Issue by 3AceShowHand** [IBM/sarama#2530]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.38.1 | v3.0.0  | v1.20  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

<img width="1687" alt="Screenshot 2023-07-28 at 18 20 41" src="https://github.com/IBM/sarama/assets/7138436/9f80bf00-76c9-4303-a8a5-d21244c4028b">

##### Problem Description

We found that there are messages have the same offset, is this normal? Will this cause data loss problem ?

**Comment by dnwe** [comment]
@3AceShowHand did you solve your issue?
