### ISSUE TITLE
[PlaceHolder] Refresh metadata more often when broker status is changed 

### ISSUE THREAD

**Issue by shangxinli** [IBM/sarama#2535]
##### Versions

1.40.0 and below 

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` default
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
When broker status is changed, we would like the Sarama client can get the status change and update to let the producer continue working.

**Comment by dnwe** [comment]
That should already happen when leadership changes or a broker is abandoned, the producer will refresh the leader by immediately updating metadata:
 
https://github.com/IBM/sarama/blob/bbee916137c1e0668744136f9ee8886d6de6a74e/async_producer.go#L754-L770

If the metadata response is still returning the old broker, it may attempt to reconnect to that old broker one or more times until the metadata returns a new broker to use
