### ISSUE TITLE
Instana instrumentation code for sarama

### ISSUE THREAD

**Issue by VipulZopSmart** [IBM/sarama#2610]
Hi team,

We used to use this https://pkg.go.dev/github.com/instana/go-sensor/instrumentation/instasarama for the instana integration with our code, but now as the ownership has been changed for the sarama, how much time will we be able to get the updated one?
Any idea? Any thoughts?

**Comment by dnwe** [comment]
I'm guessing this will be handled by that team under https://github.com/instana/go-sensor/issues/447 — assuming that they're happy to only support 1.40 and newer going forwards, then it would be a simple matter of `sed -e 's|/Shopify/sarama|/IBM/sarama|' -i` on all files
