### ISSUE TITLE
Consumer stops consuming messages and lag increases

### ISSUE THREAD

**Issue by AmiKotia** [IBM/sarama#2621]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.34.1     |  3.3.1  |   1.16    |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
kafkaConfigs:
  brokers:
    - "localhost:9092"
  group.id: "GroupId"
  producerConfig:
    acks: "1"
    compression.type: "lz4"
    request.timeout.ms: 5000
    max.request.size: 2097152
  consumerConfig:
    auto.offset.reset: "latest"
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

![image](https://github.com/IBM/sarama/assets/33386462/b6c852bb-4e4a-4fa7-a99c-57f3494a6d58)

</p>
</details>

##### Problem Description
Hi,

We are seeing this issue where the consumer stops consuming messages all of a sudden from a single partition and consumer lag increases and reaches up to 90K. We have faced this issue twice each one month apart in our production env. In order to resolve this issue, we had to restart the pod, and the messages were consumed successfully after that.
There is only one consumer in our consumergroup and it is expected to read from all the partitions of the topic.
Can we please get some help to identify what can cause the consumer to get stuck?

**Comment by VipulZopSmart** [comment]
The same behavior was observed by our team as well in all the envs, the consumer stopped consumption after some time without any errors and lag increases, we've tried to modify some configs but unfortunately nothing helped. We use confluent for the Kafka managed service.

**Comment by dnwe** [comment]
@AmiKotia / @VipulZopSmart if you're both on v1.34.1 or older then I'd strongly suggest upgrading to the latest version ([v1.41.0](https://github.com/IBM/sarama/releases/tag/v1.41.0)) as there have been a few fixes to the consumer group code since then and we've also overhauled the kafka protocol in the most recently release to bring it up to a higher level of API compatibility

There's not much we can identify from the screenshot alone, apart from that lag is increasing. It would be helpful if you could capture kafka server/broker logs when the problem has occurred and ideally sarama debug logging too by setting `sarama.Logger` to a `log.Logger`

**Comment by AmiKotia** [comment]
@dnwe 
Do you think there is any 30-31 days kafka/sarama config that could have caused this issue for the consumer to get stuck?
The weird part is that it happened like a month apart from the previous restart and was wondering if we are missing out on any config here.

**Comment by dnwe** [comment]
Nothing builtin to Sarama that would do that. If your Kafka cluster or topics have custom config then I guess it’s possible that you have log retention or offset retention that might have been set to 30 days and some cleanup operation was happening at that time that somehow triggered the consumer freezing. That should show up in your Kafka broker logs

**Comment by KrylixZA** [comment]
Hey all. New to the Sarama community 👋

Just jumping on to this thread. As you might see, I have mentioned this issue on an issue I listed against Dapr. I am busy working on a system which processes relatively high volumes (in the region of 4000 events per second during peak hours of a day). We're running in Azure Kubernetes Service consuming from Confluent Cloud.

We are experiencing this same problem with our system. Obviously we're using Dapr consumers, which is using this library down below that. What we have in our situation is a Kafka topic in Confluent Cloud configured with 30 partitions. By default, we run 2 pods. However, our scaling configuration allows us to scale out to 30 pods when volumes increase. Right now this is done by HPA, but longer term will be KEDA.

However, what we actually have going is even when we are running the peak amount of 30 pods, we have yet to see the number of consumers match the number of pods actually running.

I've even go so far as to disable HPA and simply set replica counts to match the topic partition sizes. On smaller topics (10 or fewer partitions), we often see 10 pods in the consumer group. But for our topics where we see large volumes of data flowing, in particular when consumer lag is high, new pods are not placed into the consumer group. This despite the pod logs saying it entered the consumer group. From this point onward, the pod simply hangs around doing nothing at all while the pods who were originally placed into the consumer group keep going.

In a weird turn of events, today I toggled off message production into the topic, and restarted all 30 pods. Despite this, only 19 pods entered the consumer group and consumer lag sat at 103K messages with zero consumption. It has remained this way for hours and hours.

I am unsure what could be causing this issue. I have tried using StatefulSets and setting consumerID to that of the pod name in an effort to try make rebalancing the consumer groups a bit more efficient but this has had no impact. I've tried configuring the consumer retry in the hopes that it would force unresponsive consumers out of the group and new ones to replace it. That also did little to solve the problem.

At this point I am at a bit of a loss. Any advice would be appreciated at this point.

**Comment by PatrickZhao12** [comment]
@AmiKotia I also encountered a similar problem. The reasons for the problem were mentioned in the comments of this question.https://github.com/IBM/sarama/issues/2682

**Comment by bbagameri** [comment]
We have the same problem.

Sarama version: v1.41.2
Kafka version: 3.4.1
The topic has 10 partitions, 3 consumers in the consumer group, so each consumer will be responsible for 3 or 4 partitions.

We observe different partitions getting stuck, sometimes for 15-30 minutes, sometimes for hours. Interestingly, the consumer the stuck partition is assigned to consumes other partitions without problem, and eventually the stuck partition will be consumed again without intervention. This happens once or twice every other day.

**Comment by VipulSharma1999** [comment]
@dnwe ^^
