### ISSUE TITLE
createAcls error: failed to create one or more acl rules: kafka server: unexpected (unknown?) server error

### ISSUE THREAD

**Issue by hupeipei888** [IBM/sarama#2643]
##### Description

there was an error when create acl with sarama client and  no log output for kafka server server.log

```go
config := sarama.NewConfig()

config.Version = sarama.V3_4_0_0
config.Net.SASL.Enable = true
config.Net.SASL.Mechanism = sarama.SASLTypePlaintext
config.Net.SASL.User = "admin"
config.Net.SASL.Password = "admin"

admin, err := sarama.NewClusterAdmin([]string{"192.168.0.176:9092"}, config)
if err != nil {
panic(err)
}

rACLs := []*sarama.ResourceAcls{
{
	Resource: sarama.Resource{ResourceType: sarama.AclResourceTopic, ResourceName: "test"},
	Acls: []*sarama.Acl{
		{Host: "localhost", Operation: sarama.AclOperationAlter, PermissionType: sarama.AclPermissionAllow, Principal: "test"},
	},
},
{
	Resource: sarama.Resource{ResourceType: sarama.AclResourceGroup, ResourceName: "test"},
	Acls: []*sarama.Acl{
		{Host: "localhost", Operation: sarama.AclOperationAlter, PermissionType: sarama.AclPermissionAllow, Principal: "test"},
	},
},
}

err = admin.CreateACLs(rACLs)
if err != nil {
panic(err)
}
```

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|     1.41.1   | kafka-2.13_3.4.0       | 1.20.6     |

##### Configuration
![image](https://github.com/IBM/sarama/assets/132990015/9fb702b0-6835-4da9-96ed-cdd0f3e66e06)

![image](https://github.com/IBM/sarama/assets/132990015/f75cd855-3aae-483a-bdd4-0966efdb3133)

sasl info for kafka
kafka_server_jaas.conf
```
KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin"
        user_admin="admin";
};

KafkaClient {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin";
};


Client {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        username="admin"
        password="admin";
};

Server {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin"
        user_admin="admin";
};
```

sasl info for zookeeper
zoo_jaas.conf
```conf
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="admin"
    password="admin"
    user_admin="admin"
    user_kafka="kafka123";
};
Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="admin"
  password="admin";
};
```

##### Logs
![image](https://github.com/IBM/sarama/assets/132990015/c4ec19b2-d55f-425c-8386-c28fdc5ea48e)

<details><summary>logs: CLICK ME</summary>
<p>

</p>
</details>

**Comment by hupeipei888** [comment]
> Solved?

So far, it has not been resolved

**Comment by dnwe** [comment]
OK, I was wondering why you closed the GitHub issue then? 😄 

Happy to take a look into this. From your output, the error code in the CreateACLs response is `-1` which (as shown) is an Unknown Error. However, the CreateACLsResponse struct does additionally have an ErrMsg field that _should_ contain more information and it doesn't appear that we expose that in the admin.go response at the moment

**Comment by hupeipei888** [comment]
![image](https://github.com/IBM/sarama/assets/132990015/33d8c45b-37ad-4fb0-a8e6-494400f9d567)
the returned response fro createAcls

**Comment by hupeipei888** [comment]
![image](https://github.com/IBM/sarama/assets/132990015/a02d42f9-fd56-4f0a-b0ab-50574a87804f)
I change kafka log level to debug, there is some exception
