### ISSUE TITLE
How to improve kafka producer speed

### ISSUE THREAD

**Issue by SincerelyUnique** [IBM/sarama#2649]
Hi Team, 

I am new here and want to use sarama client to send some messages, but I find the current producer config cannot handle these messages, we have so many messages need to send, the speed is not as expect, can you help me check the sarama config here and make some optimizations, thank you so much!

Points:
1. We just want to send the message immediately，doesn't need ack or some other behaviors to validate it
2. Now we find if the messages is too much, the memory of the server will rapidly increase after a critical point, which is our pain point 

![image](https://github.com/IBM/sarama/assets/16249717/b8ed92c8-8c97-414c-aef0-5a2ed0ea9d2e)

**Comment by SincerelyUnique** [comment]
The version of sarama: github.com/Shopify/sarama v1.29.1
Kakfa version: 2.8.1

**Comment by SincerelyUnique** [comment]
Topic config: PartitionCount: 64	ReplicationFactor: 2	Configs: cleanup.policy=delete,segment.bytes=272500000,retention.ms=7200000,file.delete.delay.ms=60000,retention.bytes=1090444000,segment.ms=7200000

**Comment by dnwe** [comment]
@SincerelyUnique thanks for getting in touch, happy to look into this for you.

A few things to clarify:

1. when you say "the memory of the server will rapidly increase after a critical point" — do you mean the Go process in which your Sarama client is running, or do you mean the remove Kafka broker Java process?
2. can you upgrade from github.com/Shopify/sarama v1.29.1 (2021-06-24) to github.com/IBM/sarama v1.41.2 (2023-09-12)? There have been a large number of improvements in producer performance and protocol usage in the last couple of years, so it would be useful to get get your client as up-to-date as possible before getting a baseline
3. are you using SyncProducer or AsyncProducer?
4. can you give a little detail on the message rates you're trying to send and the avg size of each message?

**Comment by Mateusnasciment** [comment]
Make sure to use AsyncProducer for immediate submission.
 Update Sarama to the latest version for performance improvements.
 Provide details on message rates and average size thanks

**Comment by SincerelyUnique** [comment]
Thank you so much, we enable the lz4 compress and the performance was improved, sorry for the late reply.
