### ISSUE TITLE
consumergroup example 'ErrClosedConsumerGroup error' can cause the program to hang

### ISSUE THREAD

**Issue by dakunge** [IBM/sarama#2651]
##### Description

https://github.com/IBM/sarama/blob/main/examples/consumergroup/main.go#L111

[this return will hang at  below code，i think for loop cannot exist 
https://github.com/IBM/sarama/blob/main/examples/consumergroup/main.go#L132
](https://github.com/IBM/sarama/blob/main/examples/consumergroup/main.go#L132)

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|        |       |     |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```

```

</p>
</details>

**Comment by dnwe** [comment]
@dakunge whilst that's true, I thought the only way of triggering ErrClosedConsumerGroup was if the user explicitly called client.Close(), which in the example doesn't happen until after the `for keepRunning { ... }` loop has already exited https://github.com/IBM/sarama/blob/98ec384372ecbb9d86036c6f210f840c45dbfa70/examples/consumergroup/main.go#L146

I guess we could call cancel() before the return, just to be sure both are coordinated in shutdown
