### ISSUE TITLE
regression: unable to handle detect errors related to messages being too large

### ISSUE THREAD

**Issue by ae-govau** [IBM/sarama#2655]
(creating issue from comments I made on #2628 a number weeks ago)

The recent change to error handling in #2628 broke some of our running code. We had code that would:

```golang
if err == sarama.ErrMessageSizeTooLarge {
    // log a message, bump a metric, but don't retry
}
```

ie for our use-case, we want to ignore messages related to a message being too large. It's OK for us to throw these out. We used to check a size before sending into Sarama, but then we had some cases where our payload was under the limit, but once headers etc were added, it was over, so we switched to checking this error code. 

Noting that https://github.com/IBM/sarama/issues/543 reports that previous error code has been returned for at least 8 years, this seems a reasonably significant change... (and a good example of [Hyrum's Law](https://nordicapis.com/what-does-hyrums-law-mean-for-api-design/) )

It's now not clear to me how I should check for size related issues.

Interestingly the last PR which touched that line of code was 4 years ago in 2019 where https://github.com/IBM/sarama/pull/1262 reverts a change a few days earlier (https://github.com/IBM/sarama/pull/1218) that renamed a bunch of error variables because:

> renaming ErrXxx constants is an API changing change https://github.com/IBM/sarama/issues/1261

(that change is arguably less impactful than this one because it could be detected/corrected at compile time whereas we only caught this at runtime)

**Comment by ae-govau** [comment]
We're open to changing our code, but as a result of this change we've had to rewrite it as

```golang
if err == sarama.ErrMessageSizeTooLarge || strings.Contains(err.Error(), "MaxMessageBytes") {
```

and I feel like there should be a better option?

**Comment by dnwe** [comment]
@ae-govau would this be sufficient?

```go
if errors.Is(err, sarama.ConfigurationError) || errors.Is(err, sarama.ErrMessageSizeTooLarge) {
        // log non-retriable error and don’t retry send
}
```

**Comment by hindessm** [comment]
Apologies that my assumption that code would already be handling the configuration error was incorrect. Hopefully @dnwe's suggestion above helps.

@dnwe Perhaps the API should export a generic function to check for retriable/non-retriable errors for cases like this?

**Comment by ae-govau** [comment]
Thanks for the responses. We aren't that keen on checking for a generic configuration error, as we would like to be alerted to any other config errors - we just want to know when the problem is that the message is too big - since we deal with that failure mode quite differently than others.

Noting that the calculated size of the message (as I understand it) is bigger than the payload itself, it's not clear how we can calculate that before trying to send it and thus we need to be able to figure it out from the error itself.

An API for "is this a message too big error" would also be fine.

**Comment by shou1dwe** [comment]
Ran into the exact problem, and I am really reluctant to put in a string-based error type check like `errors.Is(err, sarama.ConfigurationError) && strings.HasPrefix(string(err), "Attempt to produce message larger than configured Producer.MaxMessageBytes")` for example.

I am afraid someone will make a "error message readability improvement" or a casing change that is seemingly harmless and cause a problem for us.

I appreciate the need to distinguish a client side error from broker error. But reusing "ConfigurationError" here doesn't sound right either. Arguably this isn't a "ConfigurationError", because we configure the threshold correctly, and message produced can be sourced from other places so the size of it is a runtime behavior that is not entirely in the control of the system hosting producer. It is some flavor of "Bad Request" or "Invalid Argument" imho.

**Comment by ae-govau** [comment]
This is still an issue for us. I might make a PR to try to address.

**Comment by ae-govau** [comment]
PR #2848 is opened so that clients can call:

```golang
// IsMessageSizeTooLarge returns true if the error relates the message size
// being either too large as reported by the broker, or too large because it
// exceeds the configured maximum size.
func IsMessageSizeTooLarge(err error) bool {
...
```
