### ISSUE TITLE
Metadata refresh should skip updates when metadata response is empty

### ISSUE THREAD

**Issue by HaoSunUber** [IBM/sarama#2664]
##### Description

After my [PR](https://github.com/IBM/sarama/commit/98ec384372ecbb9d86036c6f210f840c45dbfa70), the Sarama client will always pick up a least loaded broker from cached brokers to fetch metadata. Then the metadata response will update our cached brokers ([updateBroker](https://github.com/IBM/sarama/blob/main/client.go#L723-L745)). 

But if the chosen broker returns a response with empty brokers, updateBroker will clear our cached brokers into empty. The client will fall back to the seed broker to refresh metadata in the next metadata refresh because cached brokers are empty. This is what we want to avoid using the seed broker after bootstrap due to the stale metadata issue ([issues](https://github.com/IBM/sarama/issues/2637)).

Technically, the broker should not return an empty broker in the response. But we do come across this situation where the broker returns empty brokers without any error and emptys our cached brokers. It looks like a bug in [Kafka](https://issues.apache.org/jira/browse/KAFKA-7924). The Java client skips the empty response to update the metadata cache ([code](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L1149)). 

In Sarama, we should also implement the same logic to skip the update when the response is empty and move to the next candidate broker. 

I can make a PR if you think it is reasonable.

**Comment by dnwe** [comment]
@HaoSunUber thanks for reporting this. It does look like a bug that could be easy to hit during a rolling restart of a kafka cluster. I agree that we should match the Java client and ignore empty metadata like this

**Comment by HaoSunUber** [comment]
Thanks. I will do a change soon

**Comment by HaoSunUber** [comment]
Thanks @dnwe for your quick response. Would you mind building a new release so that we can use it in our company?
