### ISSUE TITLE
GoRoutine Leak

### ISSUE THREAD

**Issue by ajeyprasad** [IBM/sarama#2679]
##### Description
We are seeing GoRoutine leak as below. Any suggests would be helpful.
```
goroutine profile: total 12539
3750 @ 0x44c3d6 0x41778c 0x4171f8 0x1310b05 0x136f3be 0x47cfc1
#	0x1310b04	github.com/IBM/sarama.(*partitionProducer).dispatch+0x1a4	/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:644
#	0x136f3bd	github.com/IBM/sarama.withRecover+0x3d				/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43

2805 @ 0x44c3d6 0x41778c 0x4171f8 0x131211e 0x136f3be 0x47cfc1
#	0x131211d	github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func2+0xbd	/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:853
#	0x136f3bd	github.com/IBM/sarama.withRecover+0x3d					/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43

2805 @ 0x44c3d6 0x41778c 0x4171f8 0x1312345 0x136f3be 0x47cfc1
#	0x1312344	github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func1+0x64	/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:797
#	0x136f3bd	github.com/IBM/sarama.withRecover+0x3d					/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43

2805 @ 0x44c3d6 0x45be92 0x1312853 0x136f3be 0x47cfc1
#	0x1312852	github.com/IBM/sarama.(*brokerProducer).run+0x192	/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:916
#	0x136f3bd	github.com/IBM/sarama.withRecover+0x3d			/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43

128 @ 0x44c3d6 0x41778c 0x4171f8 0x13255d7 0x136f3be 0x47cfc1
#	0x13255d6	github.com/IBM/sarama.(*Broker).responseReceiver+0x76	/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/broker.go:1121
#	0x136f3bd	github.com/IBM/sarama.withRecover+0x3d			/go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
```
##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|   v1.40.1     |  3.x     |  1.18   |

**Comment by subbu05** [comment]
We are also observing the issue - too many go routines? Is this expected?

goroutine profile: total 14983
4320 @ 0x44c3d6 0x41778c 0x4171f8 0x1310b05 0x136f3be 0x47cfc1
#       0x1310b04       github.com/IBM/sarama.(*partitionProducer).dispatch+0x1a4       /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:644
#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                          /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x41778c 0x4171f8 0x131211e 0x136f3be 0x47cfc1
#       0x131211d       github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func2+0xbd     /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:853
#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x41778c 0x4171f8 0x1312345 0x136f3be 0x47cfc1
#       0x1312344       github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func1+0x64     /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:797
#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x45be92 0x1312853 0x136f3be 0x47cfc1
#       0x1312852       github.com/IBM/sarama.(*brokerProducer).run+0x192       /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:916
#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43

**Comment by subbu05** [comment]
We are observing same issue with too many go routines.

`goroutine profile: total 14983
4320 @ 0x44c3d6 0x41778c 0x4171f8 0x1310b05 0x136f3be 0x47cfc1`
`#       0x1310b04       github.com/IBM/sarama.(*partitionProducer).dispatch+0x1a4       /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:644`
`#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                          /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x41778c 0x4171f8 0x131211e 0x136f3be 0x47cfc1`
`#       0x131211d       github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func2+0xbd     /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:853`
`#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x41778c 0x4171f8 0x1312345 0x136f3be 0x47cfc1`
`#       0x1312344       github.com/IBM/sarama.(*asyncProducer).newBrokerProducer.func1+0x64     /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:797`
`#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43
3336 @ 0x44c3d6 0x45be92 0x1312853 0x136f3be 0x47cfc1
0x1312852       github.com/IBM/sarama.(*brokerProducer).run+0x192       /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/async_producer.go:916`
`#       0x136f3bd       github.com/IBM/sarama.withRecover+0x3d                  /go/pkg/mod/github.com/!i!b!m/sarama@v1.40.1/utils.go:43`

**Comment by dnwe** [comment]
These look like AsyncProducer instances that were created but never closed. Are you re-creating producers in your app code?

**Comment by ajeyprasad** [comment]
Hi @dnwe, We are creating 8 async producers and producing the messages continuously. We are recreating the producers. We are using the same producer instance for producing the messages. Attaching the goroutine pprof png for reference.
![goroutine](https://github.com/IBM/sarama/assets/32671789/04dca0a2-752d-4d9d-9daf-73ed0ed4e1c2)
And i saw in the sarama code that go routines created in this method is singleton
<img width="697" alt="image" src="https://github.com/IBM/sarama/assets/32671789/2787d19c-8823-4ec1-b1d0-e133d4c2033a">
So these many number of goroutines should not be created right? can you please have a look on this?

**Comment by ajeyprasad** [comment]
Hi @dnwe, will sarama create separate goroutine for each partition while creating the async producers?
