### ISSUE TITLE
Consumer stops consuming messages and lag increase

### ISSUE THREAD

**Issue by PatrickZhao12** [IBM/sarama#2682]
##### Description

In our production environment, when the message production speed is much greater than the consumption speed, consumers will stop consuming every 3-4 days and the consumer offset will continue to rise. I did a test to simulate the impact of slow consumption and found that the consumer stopped consuming after 1-2 hours. In my test environment, because the production speed is very fast, the topic will delete expired files in about 1-2 hours.Then I checked kafka's log during this time and found that kafka was deleting files. I don’t know the impact of kafka deleting files on consumption. I would like to ask whether kafka will delete the corresponding data files during the consumer consumption process, and what impact will it have on sarama consumers?
Related issues: https://github.com/IBM/sarama/issues/2621

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|  v1.41.2      |  2.6.0     | 1.19    |

##### Configuration

```go
kafkaConfigs:
  brokers:
    - "localhost:9092"
  group.id: default
  consumerConfig:
    auto.offset.reset: "latest"
  topicConfig:
    retention.ms: 1440000
```

##### Logs

In the attached file, kafka.txt is the log of kafka, stop_consumption_log.txt is the log of the test program, and then test_stop_consumption.go is the code of the test program.
<details><summary>logs: CLICK ME</summary>
<p>

```

```

</p>
</details>

##### Additional Context

[stopconsumption.zip](https://github.com/IBM/sarama/files/13068596/stopconsumption.zip)

**Comment by PatrickZhao12** [comment]
![Xnip2023-10-23_18-32-54](https://github.com/IBM/sarama/assets/52538349/29a456bc-0ad6-42a8-8cfd-9e2ee5ed6136)

I captured packets from kafka in the test environment and found that no fetch_reqeust was initiated for the abnormal topic origdata_log_http, but fetch_request was sent to other topics.

**Comment by PatrickZhao12** [comment]
I think I have found the cause of the problem. I read the source code of sarama. When multiple shards of a topic return ErrOutofRange, the brokerConumer.subscriptions will eventually become empty, resulting in no more consumption of messages. It should be on the client Handle the OutOfRange error and restart the kafka consumer.

**Comment by phallstrom** [comment]
@PatrickZhao12 Can you link to the sarama code in question? Also, do you mean that sarama should handle the OutOfRange error? Or _our_ code should handle it? Thx!

**Comment by PatrickZhao12** [comment]
![image](https://github.com/IBM/sarama/assets/52538349/3d8f11b1-80cb-4132-909d-bf42d879f9c4)
![image](https://github.com/IBM/sarama/assets/52538349/05d3811c-c208-4b77-a97b-b757cfd3eb66)
![image](https://github.com/IBM/sarama/assets/52538349/b8e844f9-1a2b-426b-b527-c93b8c6c32be)
I think sarama should handle this OutOfRangeError, because for users, they don't know how to handle this error, but the final result is that consumers stop consuming. If the user sets Consumer.Offsets.Initial = OffsetNewest, then the sarama library should ensure that the latest messages are consumed, even if kakfa is deleting expired or exceeding disk space messages. Because this bug is very hidden, this problem can only be triggered when the consumption speed is much slower than the production speed and after consumption for a period of time. At least for me, this problem is difficult to troubleshoot.
