### ISSUE TITLE
Intended lifetime of ClusterAdmin question

### ISSUE THREAD

**Issue by codyrehm** [IBM/sarama#2714]
Hello. 

We are running a service that uses a single ClusterAdmin for repeated admin operations over the life of the service. We only call Close() on service termination. Over the course of the service's lifetime we eventually begin receiving many broken pipe errors when doing things like listing topics etc. If we create a new ClusterAdmin and close it for each request we do not have this issue.

My question is should we be creating and closing ClusterAdmin clients so freely or is there a configuration setting that we are perhaps missing that will allow us to use a single ClusterAdmin for the lifetime of the service?

**Comment by dnwe** [comment]
@codyrehm so it _should_ be possible to maintain a ClusterAdmin client for the lifetime of your app and it will close and re-open connections as it needs to.

However, from your issue (and previous issues I've seen on this topic) it's likely that idle tcp connections are being closed remotely without the ClusterAdmin client receiving the closure packets, so when you ask it to ListTopics and it goes to use those connections it will hits broken pipe errors before it re-creates them. It _should_ automatically re-create them though, do you not see that occurring?

**Comment by codyrehm** [comment]
We do see the connections get re-created but it does cause our clients to have only 50% or so of their requests be successful. I was looking for a way to stabilize this and improve the service's availability. I suppose I'll stick with close the client after servicing each request as see how that goes. Thank you.
