### ISSUE TITLE
Seeing EOF/panic with v1.42.1 against MSK (Amazon) 2.4.1.1 that is not seen in v1.42.0

### ISSUE THREAD

**Issue by JeffBNimble** [IBM/sarama#2719]
Is anyone having trouble with the latest v1.42.1 release? I pulled it in and now my service panics with either a "broken pipe" error or an EOF error when attempting to consume. I reverted back to 1.42.0 and everything works fine.

_Originally posted by @JeffBNimble in https://github.com/IBM/sarama/discussions/2712#discussioncomment-7515236_

My Kafka information:
Kafka version 2.4.1.1
Provider: MSK (Amazon)
Using SSL (Port 9094)

**Comment by dnwe** [comment]
@JeffBNimble can you add logs from Sarama and/or Kafka to help show your problem? You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug output.

Can you also double check and confirm that your apps sarama.Config has `sarama.Config{Version: sarama.V2_4_1_1}` or lower set?

**Comment by dnwe** [comment]
@JeffBNimble did you manage to resolve this issue? any update?

**Comment by JeffBNimble** [comment]
> @JeffBNimble did you manage to resolve this issue? any update?

Hello @dnwe. I'm incredibly sorry for the delay in responding. I saw your response a few weeks ago and have been at an AWS conference and then I'm on PTO through the end of the year. I will verify this in early January when I return and will reply. Thank you for checking back on this.

**Comment by dnwe** [comment]
No worries, enjoy the holidays and lets catch up in the New Year

**Comment by dnwe** [comment]
@JeffBNimble any more we can do here?

**Comment by JeffBNimble** [comment]
We are good. The problem was what you said so good to close this out. Thank
you!

Thank you,
Jeff Roberts

**Comment by dnwe** [comment]
Cool, thanks Jeff
