### ISSUE TITLE
Can't run sample code in Windows. Getting `dial tcp: lookup kafka: no such host`

### ISSUE THREAD

**Issue by ThadeuFerreira** [IBM/sarama#2747]
##### Description

I'm getting error `dial tcp: lookup kafka: no such host` almost every after creating a consumer.
And I'm not able to get any messages.
I'm running locally with Kafka brokers running in Docker.
The more curious is that the consume topics are created correctly.
There is only one partition.

```
func testKafka() {

	consumer, err := kafka.NewConsumer([]string{"127.0.0.1:9092"}, nil)
	if err != nil {
		log.Fatalln(err)
	}

	defer func() {
		if err := consumer.Close(); err != nil {
			log.Fatalln(err)
		}
	}()

	partitionConsumer, err := consumer.ConsumePartition("incoming_orders_v3", 0, kafka.OffsetOldest)
	if err != nil {
		//just log the error
		log.Println(err)
	}

	// Trap SIGINT to trigger a shutdown.
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)

	consumed := 0
ConsumerLoop:
	for {
		select {
		case msg := <-partitionConsumer.Messages():
			log.Printf("Consumed message offset %d\n", msg.Offset)
			consumed++
		case <-signals:
			break ConsumerLoop
		}
	}

	log.Printf("Consumed: %d\n", consumed)
}
```
##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|    github.com/IBM/sarama v1.42.1    |   7.5.2-ccs    | 1.21.5    |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
2023/12/18 19:15:29 dial tcp: lookup kafka: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc2d7d8]

goroutine 1 [running]:
main.testKafka()
	C:/Users/Thadeu/Documents/BHub/back/main.go:76 +0x558
main.main()
	C:/Users/Thadeu/Documents/BHub/back/main.go:21 +0x17
```

</p>
</details>

**Comment by dnwe** [comment]
> I'm running locally with Kafka brokers running in Docker

So it looks like your kafka broker(s) in docker is/are using 'kafka' as the hostname in the advertised.listeners field for the port you are connecting. This hostname is only visible within your docker network and isn't registered on your host machine so your laptop cannot connect.

A common pattern when running kafka in docker and wanting to connect to it from your local machine is to define an additional listener that uses 'localhost' as the advertized hostname and a different unique port for each broker (which you can expose from docker as a mapping)

e.g., see https://github.com/IBM/sarama/blob/6ab4e2b0dda33ebebf1b160b76a8239acef4987d/docker-compose.yml#L69-L70 in our docker-compose

**Comment by dnwe** [comment]
Closing as assumed to be resolved now, feel free to re-open if you are still having issues
