### ISSUE TITLE
Inquiry about behaviour when refreshMetadata is called with empty argument

### ISSUE THREAD

**Issue by wenyihu6** [IBM/sarama#2755]
#### Description

Hi! 

Not sure if there is a better place to ask these questions. I’m wondering if someone can help me better understand the code path when `refreshMetadata` is called with an empty list of topics and `conf.Metadata.Full` is set to true. Upon code reading, it seems Sarama just forwards a request with empty topics to broker https://github.com/IBM/sarama/blob/228c94e423f068fa75293e12f68cb6cf249d38d3/client.go#L1034 without populating or fetching topics. I'm curious about the underlying mechanism. 

Does the broker identify topics created on the server and fetch metadata accordingly? My confusion arises because I expected (`refreshMetadata()` with empty topics & metadata.full == true) to work roughly in a similar way as (`refreshMetadata()` with specific topics & metadata.full == false) but I got an error about ` an invalid replication factor in Kafka servers` when using the latter. After some research, this seems to imply that the number of brokers is too small on the kafka server side. My guess is that even when metadata.full is set to true, kafka never really refreshed the metadata for all topics for a cluster that had just started - possibly because the kafka topics haven’t been created at that point? Any insights into this issue would be appreciated.

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| sarama@v1.38.1|       |     |

##### Configuration

```go
config := sarama.NewConfig()
config.Producer.Return.Successes = true
config.Producer.Partitioner = newChangefeedPartitioner
config.Metadata.Full = false
```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>
I231213 18:34:52.883283 12346 github.com/Shopify/sarama/sarama.go:132 ⋮ [kafka-producer] 376  ‹Initializing new client›
I231213 18:34:52.883365 12346 github.com/Shopify/sarama/sarama.go:132 ⋮ [kafka-producer] 377  ‹Successfully initialized new client›
I231213 18:34:52.883392 12346 github.com/Shopify/sarama/sarama.go:129 ⋮ [kafka-producer] 378  client/metadata fetching metadata for [‹auth_test_table›] from broker ‹10.1.0.128:9093›
I231213 18:34:52.883747 12359 github.com/Shopify/sarama/sarama.go:129 ⋮ [kafka-producer] 379  Connected to broker at ‹10.1.0.128:9093› (unregistered)
I231213 18:34:52.976467 12346 github.com/Shopify/sarama/client.go:1103 ⋮ [kafka-producer] 380  Unexpected topic-level metadata error: ‹kafka server: Replication-factor is invalid›
I231213 18:34:52.976584 12346 github.com/Shopify/sarama/sarama.go:132 ⋮ [kafka-producer] 381  ‹Closing Client›
I231213 18:34:52.976803 12372 github.com/Shopify/sarama/sarama.go:129 ⋮ [kafka-producer] 382  Closed connection to broker ‹10.1.0.128:9093›
</p>
</details>

**Comment by dnwe** [comment]
@wenyihu6 I replied in the cockroachdb issue, but copying here too

> When calling refreshMetadata(sink.Topics()) instead of an empty argument, sarama returns pq: kafka server: Replication-factor is invalid for kafka-auth roachtest.

The difference here is that by refreshing metadata with an explicit set of topics, you go into the Kafka code path that permits automatic topic creation (which is disabled when you've done Metadata.Full and passed an empty topic list)

https://github.com/IBM/sarama/blob/5f63a84f47c39bf08a1c276f1f6b5f1d754e9fc3/client.go#L1022-L1028

The fact that you're getting 'Replication-factor is invalid' in that scenario suggests that the number of running/active brokers you have in the Kafka cluster is fewer than the default replication factor, so Kafka is returning INVALID_REPLICATION_FACTOR to Sarama because it doesn't have enough active brokers to satisfy the create request

**Comment by wenyihu6** [comment]
Closing. Thanks again for helping me understand here! 

(For posterity interested in this discussion, we discussed more in https://github.com/cockroachdb/cockroach/issues/116872.)
