### ISSUE TITLE
Not automatically balancing partitions within the same consumption group？

### ISSUE THREAD

**Issue by yezhenli** [IBM/sarama#2765]
When there is a backlog of Kafka tasks, there will be an automatic imbalance of partitions. What should I do?

**Comment by yezhenli** [comment]
For example, with 10 pods and 10 partitions, there will be no consumption.

**Comment by dnwe** [comment]
@yezhenli I'm not sure what you mean here? If there are 10 partitions and 10 active consumers in the group, then each will be assigned one partition from the group. If one of the consumers shuts down then the 10 partitions will be spread across the remaining 9 consumers and one will be consuming from 2 partitions whilst the rest only have 1. That is the only automatic balancing of partitions that takes place, an even distribution of number across the group. There's no understanding of one client being "more performant" than the others and hence able to handle more partitions.
