### ISSUE TITLE
PartitionOffsetManager.Close deadlock without autocommit

### ISSUE THREAD

**Issue by maciej** [IBM/sarama#2772]
##### Description

`PartitionOffsetManager.Close()` function deadlocks when 

```go
config.Consumer.Offsets.AutoCommit.Enable = false
```

The `Close()` function relies on `pom.errors` channel being closed. 

```go
// offset_manager.go, line 605 to 617 in github.com/IBM/sarama v1.41.2
func (pom *partitionOffsetManager) Close() error {
	pom.AsyncClose()

	var errors ConsumerErrors
	for err := range pom.errors {  // <-- happens here
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return errors
	}
	return nil
}
```

It never is as the offset manager `mainLoop` is never initialized if auto-commit is disabled.

```go
// offset_manager.go, line 79-82 in github.com/IBM/sarama v1.41.2
	if conf.Consumer.Offsets.AutoCommit.Enable {
		om.ticker = time.NewTicker(conf.Consumer.Offsets.AutoCommit.Interval)
		go withRecover(om.mainLoop)
	}
```

I believe this behaviour is not acceptable. As a Sarama user I'd expect the called functions to return an error (or panic) if used inappropriately, but never deadlock.

Gist with code reproducing the issue: https://gist.github.com/maciej/d5be479a3576b01a1f5f145aaa803ca1

##### Versions

(listing Go and Kafka versions, but these are irrelevant to this bug)

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|  v1.42.1      | 2.5.0      | 1.21.6    |

##### Configuration

Already specified.

##### Logs

N/A

##### Additional Context

N/A

**Comment by dnwe** [comment]
Thanks for reporting this issue!

**Comment by maciej** [comment]
I can still reproduce the issue in Sarama v1.43.2:
https://gist.github.com/maciej/c6d0f65d8b1155b39beaba3eada92cdb

Any chance this will get fixed?
