### ISSUE TITLE
not seeing CreateTopic ConfigEntries reflect on created topic

### ISSUE THREAD

**Issue by sicoyle** [IBM/sarama#2779]
##### Description

I'm creating a topic:
```
	var zero = "0"
	
		k.logger.Infof("automatically creating topic %s", topic)
		err := k.adminClient.CreateTopic(topic, &sarama.TopicDetail{
			NumPartitions:     -1,
			ReplicationFactor: -1,
			ConfigEntries: map[string]*string{
				"max.message.bytes": &zero,
			},
		}, false)
```
		
However, when I exec into the pod, I don't see the config entries `max.message.bytes` field reflect in the configuration:

```

I have no name!@shared-kafka-controller-0:/opt/bitnami/kafka/bin$ ./kafka-topics.sh --describe --bootstrap-server shared-kafka-controller-0.shared-kafka-controller-headless.shared-kafka.svc.cluster.local:9092 --command-config ~/tmp/hi/client.properties
Topic: 5-5-b-topic      TopicId: <redacted> PartitionCount: 1       ReplicationFactor: 1    Configs: 
        Topic: 5-5-b-topic      Partition: 0    Leader: 1       Replicas: 1     Isr: 1
Topic: 5-aa-topic       TopicId: <redacted> PartitionCount: 1       ReplicationFactor: 1    Configs: 
        Topic: 5-aa-topic       Partition: 0    Leader: 2       Replicas: 2     Isr: 2
Topic: 5-b-topic        TopicId: xP-<redacted> PartitionCount: 1       ReplicationFactor: 1    Configs: 
        Topic: 5-b-topic        Partition: 0    Leader: 0       Replicas: 0     Isr: 0
```

Am I doing something wrong? I've tried various fields in the config entries field, and don't see any reflect.

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| 1.42.1 | bitnami 26.8.3 | 1.21 |

	github.com/IBM/sarama v1.42.1

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```

```

</p>
</details>

**Comment by sicoyle** [comment]
Follow up: are there integration / E2E tests that confirm the ConfigEntries reflect in the Kafka configurations?

**Comment by sicoyle** [comment]
is this a bug in the break down of the configs?

In my controller I'm seeing config empty even when I specify values:
```
[2024-01-30 16:16:24,050] INFO [QuorumController id=0] CreateTopics result(s): CreatableTopic(name='5-different-topic', numPartitions=-1, replicationFactor=-1, assignments=[], configs=[]): SUCCESS (org.apache.kafka.controller.ReplicationControlManager)
```

**Comment by sicoyle** [comment]
any ideas here? I've tried different sarama pkg versions and bitnami kafka versions and still do not see topic configurations applying.

**Comment by dnwe** [comment]
@sicoyle 👋🏻 thanks for getting in touch — certainly your code looks reasonable to me, and running against kafka myself I can run your code and also see the config entry reflected using Sarama's DescribeConfigs request:

```go
	zero := "0"
	if err := adminClient.CreateTopic(topicName, &sarama.TopicDetail{
		NumPartitions:     -1,
		ReplicationFactor: -1,
		ConfigEntries: map[string]*string{
			"max.message.bytes": &zero,
		},
	}, false); err != nil {
		if !errors.Is(err, sarama.ErrTopicAlreadyExists) {
			log.Fatal(err)
		}
	}

	metadata, err := adminClient.DescribeConfig(sarama.ConfigResource{
		Type:        sarama.TopicResource,
		Name:        topicName,
		ConfigNames: []string{"max.message.bytes"},
	})
	if err != nil {
		log.Fatal(err)
	}
	for _, entry := range metadata {
		fmt.Printf("%s = %s\n", entry.Name, entry.Value)
	}
```

However, it is also reflected on my `kafka-topics.sh` output:

```
% ./kafka-topics.sh --bootstrap-server 127.0.0.1:29091 --topic dnwe --describe 2>/dev/null
Topic: dnwe     TopicId: <redacted> PartitionCount: 1       ReplicationFactor: 2    Configs: max.message.bytes=0
        Topic: dnwe     Partition: 0    Leader: 2       Replicas: 2,4   Isr: 2,4
```

So there's definitely something odd going on here

**Comment by sicoyle** [comment]
I can try the `cfg.Version = sarama.V3_6_0_0` to see if that helps, but I'm not sure what else to try next. Do you need anything further from me to pin point what the problem could be @dnwe ?

**Comment by sicoyle** [comment]
Turns out it was something on my setup testing these changes, and not a bug with sarama. Thank y'all for the input here!

**Comment by dnwe** [comment]
@sicoyle ah I was just about to send you a debug branch to print the protocol out 😅 

OK cool, glad you got it working!
