### ISSUE TITLE
not sure where to start with crash report

### ISSUE THREAD

**Issue by R4wm** [IBM/sarama#2781]
hi, im not sure what to make from the output, if anyone has any pointers, itd be much appreciated. 
ref: 	github.com/Shopify/sarama v1.27.0

`goroutine 650 [chan receive]:
github.com/Shopify/sarama.(*partitionConsumer).responseFeeder(0xc0004240a0)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:446 +0x92
github.com/Shopify/sarama.withRecover(0xc000124050?)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*consumer).ConsumePartition
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:158 +0x33a
 
goroutine 649 [chan receive, 22 minutes]:
github.com/Shopify/sarama.(*partitionConsumer).dispatcher(0xc0004240a0)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:337 +0x3d
github.com/Shopify/sarama.withRecover(0xc000124b10?)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*consumer).ConsumePartition
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:157 +0x2c5
 
goroutine 758 [chan receive, 22 minutes]:
github.com/Shopify/sarama.newConsumerGroupClaim.func1()
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:848 +0x98
created by github.com/Shopify/sarama.newConsumerGroupClaim
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:847 +0x191
 
goroutine 651 [select]:
github.com/Shopify/sarama.(*brokerConsumer).subscriptionManager(0xc000950190)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:748 +0x23e
github.com/Shopify/sarama.withRecover(0x0?)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*consumer).newBrokerConsumer
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:721 +0x19a
 
goroutine 652 [select]:
github.com/Shopify/sarama.(*Broker).sendAndReceive(0xffffffffffffffff?, {0xd45588, 0xc001017500}, {0xd455d0, 0xc001017540})
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/broker.go:774 +0x12c
github.com/Shopify/sarama.(*Broker).Fetch(0xc000b39e30?, 0xc0009d3560?)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/broker.go:356 +0x4f
github.com/Shopify/sarama.(*brokerConsumer).fetchNewMessages(0xc000950190)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:913 +0x653
github.com/Shopify/sarama.(*brokerConsumer).subscriptionConsumer(0xc000950190)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:781 +0xda
github.com/Shopify/sarama.withRecover(0x1c?)
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*consumer).newBrokerConsumer
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer.go:722 +0x216
 
goroutine 759 [chan receive, 22 minutes]:
github.com/Shopify/sarama.(*consumerGroupSession).consume.func1()
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:675 +0x9c
created by github.com/Shopify/sarama.(*consumerGroupSession).consume
        /home/rmintz/go/pkg/mod/github.com/!shopify/sarama@v1.27.0/consumer_group.go:674 +0x1d9
 `

**Comment by dnwe** [comment]
@R4wm there's nothing obviously wrong in the goroutine dump there, did you have an associated panic?

Sarama v1.27.0 is pretty old now (2020-08-11) so it would be worth you upgrading to the latest v1.42.2 to pickup a large number of fixes and improvements over the last few years

**Comment by R4wm** [comment]
@dnwe  thanks for the input, iv upgraded version to v1.42.2 , ill test with this and see if i run into the same issue
