### ISSUE TITLE
module declares its path as: github.com/IBM/sarama but was required as: github.com/Shopify/sarama, how could fix this ?

### ISSUE THREAD

**Issue by gopherhiro** [IBM/sarama#2819]
go: github.com/Shopify/sarama@v1.43.0: parsing go.mod:
	module declares its path as: github.com/IBM/sarama
	        but was required as: github.com/Shopify/sarama

**Comment by dnwe** [comment]
@gopherhiro in your application code you need to replace all references to 'github.com/Shopify/sarama' with 'github.com/IBM/sarama'

If you're on MacOS or Linux you can replace using sed:
e.g.,
```
git ls-files | grep .go$ | xargs sed -e 's|/Shopify/sarama|/IBM/sarama|g' -i
```

**Comment by dnwe** [comment]
No worries, you're welcome!

**Comment by puellanivis** [comment]
Outside of source control, you can also operate on all `.go` files directly through `find . -name "*.go" -exec sed -e 's|/Shopify/sarama|/IBM/sarama|g' -i {} +`
