### ISSUE TITLE
Concern Regarding the rcrowley/go-metrics Dependency

### ISSUE THREAD

**Issue by PaigeOmmen** [IBM/sarama#2832]
I noticed that there had been discussion in [Sarama roadmap](https://github.com/IBM/sarama/issues/1732#issuecomment-648706522) around the replacement of [rcrowley/go-metrics](https://github.com/rcrowley/go-metrics/tree/master) with something like [prometheus's Golang client](https://github.com/prometheus/client_golang). However, that conversation is nearly 4 years old and the rcrowley/go-metrics project remains generally unmaintained. So, I wanted to open a unique issue to bring attention to that particular concern. I understand that such a replacement of that dependency would introduce breaking changes to any projects leveraging those metrics, but I think upgrading Sarama's metric gathering component to depend on something with regular updates would benefit the project's security and integrability.

**Comment by RainbowMango** [comment]
+1 on replacement of `rcrowley/go-metrics`
