### ISSUE TITLE
Module name is github.com/IBM/sarama but expected github.com/Shopify/sarama

### ISSUE THREAD

**Issue by alanmcdade** [IBM/sarama#2833]
##### Description

alan@XXXX ships % go get github.com/Shopify/sarama
go: downloading github.com/Shopify/sarama v1.43.0
go: github.com/Shopify/sarama@upgrade (v1.43.0) requires github.com/Shopify/sarama@v1.43.0: parsing go.mod:
        module declares its path as: github.com/IBM/sarama
                but was required as: github.com/Shopify/sarama

##### Versions

v1.43.0

alan@XXXX ships % go version
go version go1.21.6 darwin/arm64

##### Configuration

N/A

**Comment by dnwe** [comment]
github.com/IBM/sarama is the correct module path since the change of ownership, so use that in your source code imports and as your ‘go get’ argument

**Comment by alanmcdade** [comment]
Sure thanks.
