### ISSUE TITLE
Too many goroutines in gopark state

### ISSUE THREAD

**Issue by ajeyprasad** [IBM/sarama#2839]
##### Description

We have implemented a single Kafka producer using Sarama, which multiple goroutines utilize to produce messages to Kafka. However, we have observed an excessive number of goroutines in the gopark state. What could be the possible cause for this?

Below is the image of goroutine dump:

<img width="600" alt="gopark" src="https://github.com/IBM/sarama/assets/32671789/0da4a863-06a4-4d59-af4b-19d3b2f5e130">

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| v1.40.1 | 2.8.1 |  1.18 |

**Comment by dnwe** [comment]
So from the displayed goroutine image it looks fairly normal. Your producer is writing to one or more topics totalling 2093 partitions. Sarama dedicates a parititionProducer to each partition. Each of these has a `dispatch()` loop which is [waiting on an input channel](https://github.com/IBM/sarama/blob/f21c5125746f9d10fd731dfdff54a494098626d1/async_producer.go#L645) to receive messages that you'd like it to send. When that input channel is empty they will block on the chanrecv waiting for input and the Go scheduler will park the goroutine until it needs to be woken when the channel receives input.
