### ISSUE TITLE
Error not handled

### ISSUE THREAD

**Issue by ajeyprasad** [IBM/sarama#2840]
##### Description

Why error is handled in https://github.com/IBM/sarama/blob/f21c5125746f9d10fd731dfdff54a494098626d1/async_producer.go#L632 ? What will happen when an error sent back from Leader method?

Here is the code
```	
pp.leader, _ = pp.parent.client.Leader(pp.topic, pp.partition)
if pp.leader != nil {
	pp.brokerProducer = pp.parent.getBrokerProducer(pp.leader)
	pp.parent.inFlight.Add(1) // we're generating a syn message; track it so we don't shut down while it's still inflight
	pp.brokerProducer.input <- &ProducerMessage{Topic: pp.topic, Partition: pp.partition, flags: syn}
}
```

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| v1.41.0 | 2.8.1 | 1.18  |

**Comment by puellanivis** [comment]
The comment immediately preceding should explain, right?
> we'll do a proper call to `updateLeader` on the first message

**Comment by dnwe** [comment]
Closing as answered
