### ISSUE TITLE
Error not being thrown when multiple consumer groups are created with the same group ID

### ISSUE THREAD

**Issue by AhmedNSidd** [IBM/sarama#2842]
#### Description

The issue is simple: 
```
consumerGroup1, err := sarama.NewConsumerGroup(same_kafka_broker, "groupId", sarama.NewConfig())
consumerGroup2, err := sarama.NewConsumerGroup(same_kafka_broker, "groupId", sarama.NewConfig())
```

The above code should given an error because you're not supposed to be able to create two consumer groups with the same group ID, but you're able to do so here.

#### Additional context

N/A

**Comment by dnwe** [comment]
👋🏻 hi and thanks for raising this question

> The above code should given an error because you're not supposed to be able to create two consumer groups with the same group ID, but you're able to do so here

Why would it not be allowed? A consumer group is intended to contain more than one consumer. Whilst unusual, if you use the same `groupId` for two sarama.NewConsumerGroup(...) calls within the same Go process, it is really no different functionally to you running two separate Go processes that both join the same group. You'll just have two members within your single process, with different partition assignments within the same group.

**Comment by AhmedNSidd** [comment]
> Why would it not be allowed? A consumer group is intended to contain more than one consumer. Whilst unusual, if you use the same groupId for two sarama.NewConsumerGroup(...) calls within the same Go process, it is really no different functionally to you running two separate Go processes that both join the same group. You'll just have two members within your single process, with different partition assignments within the same group.

Alright, fair enough. It just wasn't something that was clear to me from looking at the function's signature / documentation because as far as I know in Kafka, if you try to create a _new_ consumer group with the same group ID as one that already exists, you can't generally do that. What you're referring to seems to be adding new consumers to the existing consumer group (I could be wrong, I'm still learning Kafka).

Anyway, I think we can close this issue.
