### ISSUE TITLE
One bad issure

### ISSUE THREAD

**Issue by GitHub-huyuan** [IBM/sarama#2872]
On my kafka broker, it is too many close_wait about ten minutes; It is a coordinator. The consumerGroup is about 6000+  consumer；In the sarama log， i can not get some information about it.
![image](https://github.com/IBM/sarama/assets/40454512/17ada9eb-fd4b-455c-885b-1afd6892b3d6)

**Comment by Gorgonx7** [comment]
@GitHub-huyuan please could you provide more information in to what you believe the bug in Sarama is? From the description/logs above this could be anything from a transient network issue, a broker issue or a config issue and in order to investigate a fix in Sarama we'll need more information

**Comment by Gorgonx7** [comment]
@dnwe can we close this due to no reply?
