### ISSUE TITLE
Should share the max retries of metadata?

### ISSUE THREAD

**Issue by yitian108** [IBM/sarama#2895]
#### Description

When reviewing the function tryRefreshMetadata() in client.go, I noticed a shared variable attemptsRemaining (initialized as Metadata.Retry.Max) within the subfunction retry(). Every call to the function retry() decreases the value of attemptsRemaining. For instance, if the initial value of attemptsRemaining is 3, when _**the broker is unavailable**_, it decreases by 1. In another scenario where there is _**no leader for some partitions**_, attemptsRemaining decreases from 2 instead of the initial value of 3. Shouldn't it be reset for different reasons?

#### The snippet of the func tryRefreshMetadata()

![image](https://github.com/IBM/sarama/assets/3113836/e389a1ca-9f38-40cb-baa1-985834aa357d)

Sarama version: 1.42.2

**Comment by puellanivis** [comment]
I’ve not really heard of a situation where attempts are per specific error issue, rather than just generically for any issue.
