### ISSUE TITLE
Sincerely ask, is this redundant?

### ISSUE THREAD

**Issue by Trinoooo** [IBM/sarama#2923]
Version：Latest, v1.43.2
Description：
```
func safeAsyncClose(b *Broker) {
	tmp := b // local var prevents clobbering in goroutine
	go withRecover(func() {
		if connected, _ := tmp.Connected(); connected {
			if err := tmp.Close(); err != nil {
				Logger.Println("Error closing broker", tmp.ID(), ":", err)
			}
		}
	})
}
```
annotation says "local var prevents clobbering in goroutine", how it works? I mean when  `safeAsyncClose` is called, the local var `b` is just a copy pointing to the `Broker`, even if goroutine overwrites b, other goroutines will not perceive it.

thanks for help :)

**Comment by puellanivis** [comment]
Looking at this, the code originates from https://github.com/IBM/sarama/commit/237cfb5380c1d4322b8f2b90f132a90f98e1778e

In this change, we can see that originally, the code had to duplicate the variable loop-local to avoid the issue solved by `loopvar`:
```
	for _, broker := range client.brokers {
		myBroker := broker // NB: block-local prevents clobbering
		go withRecover(func() { myBroker.Close() })
	}
```

But when this was extracted into a synchronous function call, that copying indeed became unnecessary.
