### ISSUE TITLE
Need help to understand supported Kafka versions

### ISSUE THREAD

**Issue by chaithraav** [IBM/sarama#2949]
I need to understand the behaviour of sarama upgrade post v1.40, few versions of Kafka config are failing to connect.

My docker kafka version: 2.3.0

Sarama v1.40
Supports 1.0, 2.2, 2.6, 3.1, 3.2, 3.3

Sarama v1.43
Supports 1.0, 2.0, 2.2
Fails for 2.4, 2.6, 2.8.2, 3.3.0, 3.1.1, 3.2.3, 3.4

Why is there is inconsistency and how can I resolve this?

**Comment by dnwe** [comment]
@chaithraav see the release notes for [v1.41.0](https://github.com/IBM/sarama/releases/tag/v1.41.0), but ultimately we started to implement support for more features of the newer kafka protocols and hence our adherence to the use of the right Kafka protocol versions for the given Config Version. As such you should never exceed your remote broker version (2.3.0) when configuring your sarama config version
