### ISSUE TITLE
crash in github.com/IBM/sarama.(*asyncProducer).newPartitionProducer 

### ISSUE THREAD

**Issue by dnj12345** [IBM/sarama#2990]
##### Description

Hi,
Seeing a crash in `withRecover` function called from `(*asyncProducer).newPartitionProducer`. The partitionedProducer struct is getting created in this function. Not sure why `pp.dispatch` argument passed to withRecover is showing up as nil in the crash.

The sarama producer configuration is shown below in the configuration section. Rest of the config uses defaults. Not sure if I am missing some config that is leading to this crash.
Any help is appreciated.

-Dnj

##### Versions

| Sarama | Kafka | Go  |
| v1.43.3 | 3.7.0 | 1.22.0 |

##### Configuration

```
config.Producer.RequiredAcks = sarama.NoResponse
config.Producer.Compression = sarama.CompressionSnappy
config.Producer.Partitioner = sarama.NewHashPartitioner
config.Producer.Retry.Max = 1
config.Producer.Flush.MaxMessages = 100
config.Producer.Flush.Frequency = time.Duration(250) * time.Millisecond
config.Producer.Return.Successes = true
```

##### Logs

```
kafka-producer:     /go/pkg/mod/github.com/!i!b!m/sarama@v1.43.3/async_producer.go:645 +0x191
kafka-producer: github.com/IBM/sarama.withRecover(0x0?)
kafka-producer:     /go/pkg/mod/github.com/!i!b!m/sarama@v1.43.3/utils.go:43 +0x33
kafka-producer: created by github.com/IBM/sarama.(*asyncProducer).newPartitionProducer in goroutine 241
kafka-producer:     /go/pkg/mod/github.com/!i!b!m/sarama@v1.43.3/async_producer.go:600 +0x1b6
```

**Comment by puellanivis** [comment]
Can you please include the whole traceback from your logs? The `0x0?` in the traceback is not from the `pp.dispatch` being nil, because it actually calls into the `pp.dispatch` function, which crashes at line 645.

We need from the `panic` message itself and starting the traceback from there until the lines that you have already included.

**Comment by dnj12345** [comment]
Hi @puellanivis,
Unfortunately, that's all I have at this point. Someone who was using our application which uses sarama library sent me this. I'll try to find out more info and share here. Is there anything else I need to look for besides trying to get the complete stack trace?

**Comment by dnj12345** [comment]
After more investigation, found out there was an error in my applications causing an issue which led to this. Closing it. Apologize of the inconvenience.
