### ISSUE TITLE
Why are SASL Handshake errors not logged ?

### ISSUE THREAD

**Issue by pierDipi** [IBM/sarama#2994]
Is there a security concern that prevents Sarama from logging SASL handshake errors?

I'm trying to debug an issue and the logger is only logging `Error while performing SASL handshake kafka-1:9093` since the actual error is not logged, it's not clear what went wrong:

https://github.com/IBM/sarama/blob/893978c87fe7af13a2b6849ba62b003493f97f25/broker.go#L1243-L1252
https://github.com/IBM/sarama/blob/893978c87fe7af13a2b6849ba62b003493f97f25/broker.go#L260-L275

**Comment by puellanivis** [comment]
Huh… I’m not at all sure why these would want to be logged at `Info` at all. They definitely seem like something that should be logged at error. Huh… they came in during PR https://github.com/IBM/sarama/pull/2234 with no comments.
