### ISSUE TITLE
TCP packet capture found that the Partitions.Offset returned by Fetch V1 Request increased, but MessageSet was empty

### ISSUE THREAD

**Issue by memory-overflow** [IBM/sarama#3006]
##### Description

A topic consumption is suddenly stuck.

Using the packet capture tool, it is found that for normal topics, the return packet of Fetch V1 Request will have an increased offset and will return MessageSet.

As shown below, the normal request and response packets:
<img width="1920" alt="企业微信截图_83187aba-8ff5-4100-a316-479c2939f5e5" src="https://github.com/user-attachments/assets/437b8227-a8b2-4169-b55e-a50fcb9f61f1">

<img width="1765" alt="企业微信截图_d895bbe6-d225-4e73-a73e-eaaacef7f9e4" src="https://github.com/user-attachments/assets/158530d2-ff9c-4615-b954-dafd488c0f37">

Abnormal request and response packets:
<img width="1920" alt="企业微信截图_19aa65b9-8c6c-49b9-b42b-13f8d97262f2" src="https://github.com/user-attachments/assets/5387e41f-e568-46d0-988b-afb6b14d28f6">

<img width="1920" alt="企业微信截图_a2249e23-e5ed-4c3b-8792-67608929d7e7" src="https://github.com/user-attachments/assets/93382d4e-f748-4658-a5e9-d3b2dc1eb478">

Once an exception occurs, the consumer will keep retrying indefinitely, causing the topic consumption to be stuck.

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| v1.29.1 | v3.5.1  |  1.18   |

##### Configuration

```go
func setupKafka() (c *cluster.Consumer, err error) {
	topics := []string{}
	for {
		topics, err = dao.TIMatrixTemplateDao{}.GetAllTopics(context.Background())
		if err != nil {
			log.Error("get all topics error: ", err)
		}

		if len(topics) > 0 {
			break
		}
		log.Error("topic_id not update yet")
		time.Sleep(2 * time.Second)
	}

	clusterConfig := cluster.NewConfig()
	clusterConfig.Consumer.Return.Errors = true
	clusterConfig.Group.Return.Notifications = true
	clusterConfig.Consumer.Offsets.Initial = sarama.OffsetNewest
	clusterConfig.Consumer.Offsets.CommitInterval = time.Second
	clusterConfig.Consumer.Fetch.Default = int32(config.GetKafkaConsumer().KafkaMaxMessageBytes)
	if len(config.Get().Kafka.User) > 0 {
		clusterConfig.Net.SASL.Enable = true
		clusterConfig.Net.SASL.User = config.Get().Kafka.User
		clusterConfig.Net.SASL.Password = config.Get().Kafka.PassWord
	}
	consumer, err := cluster.NewConsumer(strings.Split(config.Get().Kafka.Host, ","),
		config.GetKafkaConsumer().KafkaGroupName, topics, clusterConfig)
	go dynamicConsumerTopic(consumer, topics)
	log.Infof("create kakfa consumer success, topics: %v", topics)
	return consumer, nil
}
```

##### additional

We have some complete packet capture data, but it involves sensitive information and cannot be provided directly. If you need it, you can contact me for assistance at willzhen@tencent.com

**Comment by memory-overflow** [comment]
I need help urgently, please！！！

**Comment by memory-overflow** [comment]
https://github.com/IBM/sarama/pull/2057, is this fix to solve this problem?

**Comment by dnwe** [comment]
@memory-overflow did you resolve this issue?

**Comment by memory-overflow** [comment]
> @memory-overflow did you resolve this issue?

Yes, we found that the v1 version of the fetch protocol will force the max_bytes check. If a packet larger than max_bytes appears, the client will be stuck and can neither get the message nor skip it.
