### ISSUE TITLE
sync producers to send truncated data

### ISSUE THREAD

**Issue by Mr-TianLang** [IBM/sarama#3029]
kafka 3.6.1
sarama 1.34.1
go 1.20

The messages recorded by Kafka are occasionally truncated, and occasionally two messages are truncated and merged together, which looks like concurrency. At present, no issues have been identified. Is it related to compatibility between Sarama and Kafka versions?

**Comment by puellanivis** [comment]
I think we would need more data to know? As described this could meet any number of possibilities? But also, yes, it does sound important.
